### ISSUE TITLE
Mehr neue / auch unerfahrene Vortragende gewinnen

### ISSUE THREAD

**Issue by titanoboa** [rughh/planning#10]
Ich würde gerne mehr neue, ggf. auch unerfahrene Vortragende auf der usergroup sehen als derzeit. Dazu habe ich ein paar Vorschläge. 
Was meint Ihr dazu?
- deutlich machen, dass Vorträge auf Englisch und Deutsch gleichermaßen willkommen sind (Ansagen, Webseite, usw)
- mit den Vortragenden absprechen, welche Sprache sie bevorzugen und ob sie ggf. bereit sind spontan auf die andere Sprache zu wechseln (im Vorfeld absprechen und _nicht_ auf der Bühne vor der Gruppe fragen)
- die Talks entsprechend auf onruby ankündigen, so dass das Publikum weiß, was sie erwartet
- bei der Q&A Fragen in beiden Sprachen zulassen und ggf. übersetzen
- deutlich machen, dass Q&A optional ist
- mit den Vortragenden klären, ob sie eine Q&A mit der Gruppe machen möchten oder Fragen lieber nur in informellen Gesprächen beantworten möchten, und dies bei der Moderation berücksichtigen (auch hier: im Vorfeld abklären und _nicht_ auf der Bühne vor der Gruppe)

Wichtig ist dabei klarzumachen, dass der Verzicht auf Q&A oder die Festlegung auf eine Sprache weder ein Makel noch ein 'Newbiebonus' ist. Sprachkenntnisse haben nichts mit Fachkenntnissen zu tun, und nicht alle Themen eignen sich für eine offene Q&A. 
## Langfassung/Begründung

Gegenwärtig fragen wir zu Beginn der usergroup, ob jemand kein Deutsch spricht, und wechseln dann ggf. zu Englisch. Das ist prima, um Leute einzubinden, die kein Deutsch sprechen, aber eine deutliche Hürde für neue Vortragende. Zwischen diesen beiden Punkten sollten wir eine bessere Balance finden.

Für uns alte Häsinnen und Hasen sowieso Leute mit übergroßem Ego oder besonders dickem Fell ist das alles kein Problem. Wir hören uns gerne reden, selbst in schauerlich akzentbehaftetem Englisch, und wir machen so oder so Talks. Dazu nehmen wir die usergroup als eine Art Familientreffen war, bei dem eh schon alle wissen wie schlau wir sind und ein Vortrag, der mal nicht so gut ist, dem auch keinen Abbruch tut.

Alle anderen, insbesondere wenn sie neu in der Gruppe und/oder in Tech generell sind, lassen sich durch etliche Überlegungen davon abhalten, einen Talk zu machen:
- Kenne ich mein Thema gut genug für einen Talk in einer Gruppe, in der hauptsächlich fortgeschrittene Themen verhandelt werden?
- Traue ich mich, vor vielen fremden Leuten sprechen? Das ist für viele Leute ungewohnt und einschüchternd, selbst wenn die Gruppe eher freundlich ist
- Q&A - was, wenn die mich was fragen, dass ich nicht verstehe und/oder nicht beantworten kann?
- Ist mein Thema überhaupt interessant oder relevant, oder wissen die das eh alles schon, wo die doch alle so fortgeschritten sind (oder zumindest so tun)?

Jeder einzelne dieser Punkte kann bereits dazu führen, dass jemand keinen Talk einreicht. 

Jetzt legen wir die Stange nochmal deutlich höher, in dem wir erwarten, dass Leute das Ganze auch noch in einer anderen Sprache machen - die sie möglicherweise nicht gut beherrschen und nicht gewohnt sind zu sprechen. Das dann womöglich noch spontan, weil gerade heute ausnahmsweise jemand da ist, der oder die kein Deutsch spricht.

Was die Q&A angeht: Einem englischsprachigen Vortrag zu lauschen, ist eine Sache - anschließend Fragen auf Englisch zu stellen, eine ganz andere. Auch hier könnten wir die Hürde zur Beteiligung absenken.

Das ist jetzt beschrieben unter der Annahme, dass die Beteiligten Deutsch besser beherrschen als Englisch, gilt aber natürlich entsprechend umgekehrt genauso.

Unabhängig von der Sprache ist eine offene Q&A für einige Vortragende abschreckend. Einen Vortrag kann man planen und üben und mit anderen besprechen, eine Q&A nicht. Gerade weil wir immer noch die Gelegenheit haben, hinterher beim Bier zu schnacken, ist eine Q&A m.E. verzichtbar. Oft artet es sowieso in Spezialdiskurse oder 1-zu-1 Unterhaltungen aus, die für den Rest der Gruppe nur mäßig spannend sind.

**Comment by nesQuick** [comment]
My 2 cents: geile idee, auf jedenfall dafür :+1: Bin persönlich auch immer gern bereit mit leutten vorher slides oder den talk durch zugehen. Ich frage mich was da jetzt genau an actionables raus fällt, if any :)

**Comment by phoet** [comment]
huch, überhaupt keine notifications gesehen...

@titanoboa ich würde vorschlagen, wir machen eine wiki seite, auf der wir die informationen für speaker zusammen tragen und wo wir auch gleich eine checkliste für uns/die speaker machen können.

ich würde mich sehr freuen, wenn wir mehr leute finden, die bei uns einen vortrag halten wollen. über die jahre ist mir allerdings ein bissl die motivation ausgegangen mir den mund fusselig zu reden und wie ihr wisst komm ich eh nur für :beers:

**Comment by titanoboa** [comment]
ja, die notifications sind manchmal... ich ping mal @halfbyte und @rubiii an, vielleicht haben die ja bisher auch keine notification bekommen

+1 für eine Wikiseite 

Wenn wir die zusammen erstellen, dann einigen wir uns ja quasi auch dabei, was wir machen wollen und was nicht. Kann ja sein, dass zB jemand findet, dass es viel wichtiger ist die Leute einzubinden, die kein deutsch verstehen, und deshalb alles auf englisch sein soll.

Wenn wir die Wikiseite haben, können wir uns darauf aufbauend dann weitere actionables überlegen. 
Ich fürchte nämlich, mit einer Wikiseite allein ist es nicht getan - die lesen eh nur die Leute, die sich schon fast entschieden haben, einen Talk zu machen. Das mit dem Mund fusselig reden kann ich allerdings auch gut verstehen. Aber vielleicht fallen uns ja noch ein paar Sachen ein, die mit wenig Aufwand zu haben sind (z.B. die Folien für die "Eröffnungsrede" entsprechend anpassen - einmalig und wenig Arbeit, dauerhafte Wirkung ;-) Und nicht alle actionables, die uns einfallen, müssen sofort umgesetzt werden.

Wie auch immer, lasst uns mit der Wikiseite beginnen und dann sehen wir weiter. Aber nicht mehr heute Abend ;-)

**Comment by phoet** [comment]
besser als nüscht: https://github.com/rughh/planning/wiki/Speaker-Checklist
