### ISSUE TITLE
Feedback to the meetup from april 2018

### ISSUE THREAD

**Issue by janz93** [rughh/planning#100]
FYI @halfbyte , @lindtdev , @phoet 

I had asked for some feedback to the meetup in April.
I hadn't had the chance to share it yet.

- no link from the website to GitHub issues
- why the meetup/ what is the purpose of the meetup

- How to submit a talk proposal 
  - website?
  - GitHub?

👍 open on language is good(e.g. talk about js no problem)

**Comment by phoet** [comment]
@janz93 weniger feedback einsammeln, mehr features einbauen https://github.com/phoet/on_ruby/issues/253

**Comment by janz93** [comment]
Wichtig ist aber auch der 2 Feedback punkt
