### ISSUE TITLE
September open mic session

### ISSUE THREAD

**Issue by janz93** [rughh/planning#102]
In order to have a better overview of the open mic session, I created this issue.
If you are interested in giving a talk/lightning talk please add a comment with the following information:

- Title of the talk
- Amount of time you want to talk

**Comment by lindtdev** [comment]
I have participated in a fun project using neural networks for Robocup and want to speak about that. 

Title: Robocup: Neural networks for football robots
10-15 minutes

**Comment by sebs** [comment]
Webcomponents/polymer3.

Could be a talk .... 30 minutes

**Comment by skorfmann** [comment]
Our team at WLW was doing Mob Programming over the course of the last two months, and I could do a quick talk about it.

Title: Full Time Mob Programming for 2 Months
Format: Lightning Talk (5 - 10) minutes

**Comment by MilenaMMay** [comment]
Title: Remote collaboration
Time: 15 to 30 minutes - how detailed should it be?

We've transitioned to a Remote OK company at mindmatters starting end of 2016 and I'd like to share what we've learnt so far about Remote collaboration, i.e. tools and soft skills you need.

**Comment by lindtdev** [comment]
@MilenaMMay I think 15-20 minutes is probably a better time frame especially if we really do get four talks!

**Comment by MilenaMMay** [comment]
@lindtdev Ok, I go for the short version, then. =)

**Comment by sebs** [comment]
I will block a bit less time as well

**Comment by janz93** [comment]
@sebs @skorfmann @MilenaMMay Could you post a link to your slides or sent them to me?

**Comment by lindtdev** [comment]
@sebs ahh cool cool cool, thank you for telling me!

**Comment by skorfmann** [comment]
@janz93 here you go [presentation-small.pdf](https://github.com/rughh/planning/files/2382840/presentation-small.pdf)

**Comment by sebs** [comment]
I found something better than my slides 

https://medium.com/@westbrook/litelement-to-do-app-1e08a31707a4

**Comment by sebs** [comment]
This is the thing I did not tell, but should have and the reason why all is how it is in polymer land ;)
