### ISSUE TITLE
November 14.11.2018

### ISSUE THREAD

**Issue by janz93** [rughh/planning#104]
14.10.2018 19:00

- [x] Location
- [x] [Event anlegen](http://hamburg.onruby.de/admin/)
- [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
- [x] Promo auf Twitter
- [x] [Push-Notification für iOS app senden](http://hamburg.onruby.de/admin/dashboard)
- [x] [Slides anpassen](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)
- [x] [Door Sign anpassen](https://docs.google.com/presentation/d/1IQfnE3TbG3EU5zRnNKdG3kzxdYjT1ryWNWs4WWgpE04/edit?usp=sharing)
- [ ] [Gather slide-decks and other material](http://hamburg.onruby.de/admin/materials/new)

**Comment by andywenk** [comment]
November 14.10. ? 14.11 oder?

Location:

sum.cumo GmbH
Schäferkampsallee 16 
20357 Hamburg

Wir haben einen Talk: "DevOps auf RSpec basierenden Tests" Dauer 20 - 30 Minuten.

Deal?

**Comment by janz93** [comment]
@andywenk ja das stimmt ^^
Okay ist beides vermerkt :)

**Comment by janz93** [comment]
@andywenk weißt du schon wer den talk halten wir?
Ich habe beim Meetup den erstmal unter meinem Namen angelegt.
Es wäre aber noch cool eine Beschreibung und einen Namen des Vortragenden zu haben

**Comment by andywenk** [comment]
Lucas Weatherhog

Beschreibung folgt von Lucas

**Comment by andywenk** [comment]
Lucas ist https://github.com/sergeanthorst

**Comment by janz93** [comment]
@tobstarr Das wäre super.
Ich würde dich bitten auf der [Webseite den Talk anzulegen](http://hamburg.onruby.de/topics/new), sodass er auch auf der Webseite zusehen ist

**Comment by tobstarr** [comment]
@janz93 so, endlich geschafft. http://hamburg.onruby.de/topics/graphql-673
