### ISSUE TITLE
December meetup 12.12.2018

### ISSUE THREAD

**Issue by janz93** [rughh/planning#106]
12.12.2018 19:00

- [x] Location
- [x] [Create Event](http://hamburg.onruby.de/admin/)
- [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
- [x] Promotion on Twitter
- [x] [Send out push notification for iOS app](http://hamburg.onruby.de/admin/dashboard)
- [x] [Adjust Slides](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)
- [x] [Adjust Door Sign](https://docs.google.com/presentation/d/1IQfnE3TbG3EU5zRnNKdG3kzxdYjT1ryWNWs4WWgpE04/edit?usp=sharing)
- [ ] [Gather slide-decks and other material](http://hamburg.onruby.de/admin/materials/new)

**Comment by DonSchado** [comment]
Hi @janz93,

@jhilden and I from railslove/cologne, are planning to visit you next week and we would like to bring a talk. 

Something like: 
```
You might not need React - A Talk about Rails, JavaScript and Trade-offs
```

I would plan for 30 min (maybe 40 + QA).

**Comment by janz93** [comment]
@DonSchado @jhilden That is awesome 🎊 
Yes we are currently looking for talks!
It would be great if you could [add the talk to our website](http://hamburg.onruby.de/topics/new).
