### ISSUE TITLE
Change Twitter Handle

### ISSUE THREAD

**Issue by phoet** [rughh/planning#109]
as proposed on the last meetup, i would like to change the twitter handle to something that can be searched easily and does not need any explanation. it would be great to announce it on the next meetup #107 .

thoughts?

@rughh/all

**Comment by salzig** [comment]
`@rughh` and `@rubyhh` are sadly already taken. 

as of right now those two options are still free to claim: 
- `@HamburgRUG`
- `@HamburgOnRuby'

**Comment by janz93** [comment]
alternatively how about `@rug_hh` to follow the Berlin naming

**Comment by lindtdev** [comment]
I like rug_hh

**Comment by phoet** [comment]
@janz93 i would propose that you use the next meetup to do a voting and then change it throughout the meetup so that everyone can tweet about it and people know whats going on. what do you think?

**Comment by janz93** [comment]
@phoet that is a great idea.
I will go that 👍

**Comment by phoet** [comment]
https://twitter.com/HamburgOnRuby
