### ISSUE TITLE
Meeting Mai 2015

### ISSUE THREAD

**Issue by halfbyte** [rughh/planning#11]
* [x] Location
* [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
* [x] Promo auf Twitter
* [x] [Push-Notification für iOS app senden](http://hamburg.onruby.de/admin/dashboard)
* [x] [Slides anpassen](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)

**Comment by phoet** [comment]
assigned to jan because of shortest stöckchen

**Comment by phoet** [comment]
just because we might be a little busy preparing our sweden trip to @weidenfreak, maybe we want to delegate the organization of this event to @codestars at jimdo in case he is interested?

**Comment by phoet** [comment]
meh, i meant @nesQuick

**Comment by nesQuick** [comment]
Yeah, sure. Happy to take it over. But would appriciate any good pointers for speakers :microphone: Location will be Jimdo, because it's easy :wink:

**Comment by titanoboa** [comment]
@nesQuick http://hamburg.onruby.de/#topics currently has two talks offered

**Comment by phoet** [comment]
i don't know if @skorfmann is back in hamburg yet

**Comment by titanoboa** [comment]
he is sitting next door, more or less

**Comment by titanoboa** [comment]
ah, @ mention, so he can answer himself
(ich sollte lernen dieses neumodische internetzeugs zu bedienen)

**Comment by skorfmann** [comment]
> i don't know if @skorfmann is back in hamburg yet

Yes, I am in Hamburg :) - but I'll be away from 8. - 23. of May. However, June would work.

**Comment by nesQuick** [comment]
Well just figured they are both from @skorfmann I will see, if I will find any cool talks. Any thoughts about mixing one remote talk in?

**Comment by alto** [comment]
I would like to invite people to work in New Zealand (and introduce [Abletech](https://abletech.nz)). Remote via Skype or so. 10 minutes, after 21:00 Hamburg time (7 a.m. New Zealand).

**Comment by nesQuick** [comment]
@alto sounds good. I just checked with our office staff and we will have everything one might need (esp. speakers) so could your add your talk here http://hamburg.onruby.de/topics/new *please*

One (or two) talks slots left :)

**Comment by alto** [comment]
Hmm, Carl from Abletech is not available this month (and I would like to do it together with him). Let's postpone it until later.

Cheers,
Thorsten

**Comment by phoet** [comment]
@nesQuick topic -> http://hamburg.onruby.de/topics/byol-bring-your-own-logging

do you want to fiddle with the admin-backend to setup the event and do a little promotion on the interwebs? you should have twitter access as well, the credentials are [here](https://github.com/rughh/logins)

**Comment by nesQuick** [comment]
ja!

**Comment by nesQuick** [comment]
Ahh, took me a while to realize I had to create the event at onruby, I could have done this way before, sorry :D We are almost done with the programm, @phoet does one talk and I try to find some other talk as well :)

**Comment by nesQuick** [comment]
Also toot'd :bird:

**Comment by nesQuick** [comment]
Two talk confirmed, better late then never :dancer:

**Comment by titanoboa** [comment]
:+1: 

btw I sadly won't make it on Wedenesday
