### ISSUE TITLE
Februar 2019 Meetup

### ISSUE THREAD

**Issue by janz93** [rughh/planning#110]
13.02.2019  19:00
- [x] Location
- [x] [Create Event](http://hamburg.onruby.de/admin/)
- [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
- [x] Promotion on Twitter
- [x] [Adjust Slides](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)
- [x] [Adjust Door Sign](https://docs.google.com/presentation/d/1IQfnE3TbG3EU5zRnNKdG3kzxdYjT1ryWNWs4WWgpE04/edit?usp=sharing)
- [ ] [Gather slide-decks and other material](http://hamburg.onruby.de/admin/materials/new)

**Comment by janz93** [comment]
@crush-157 and @skorfmann could you comment a link to your slides if you want to share so I can link them in our website?

**Comment by crush-157** [comment]
https://docs.google.com/presentation/d/e/2PACX-1vQ3sGjnXpV_AFRdCU084LNORA4E4B9aPBVhjvJwYeWsxCtsmTCK1TgzzLeTgsZOy6UHhVYtJDr7nAq4/pub?start=false&loop=false&delayms=5000

**Comment by skorfmann** [comment]
[geminator.pdf](https://github.com/rughh/planning/files/2917020/geminator.pdf)
