### ISSUE TITLE
March 2019 Meetup

### ISSUE THREAD

**Issue by janz93** [rughh/planning#111]
13.03.2019  19:00
- [x] Location
- [x] [Create Event](http://hamburg.onruby.de/admin/)
- [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
- [x] Promotion on Twitter
- [x] [Adjust Slides](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)
- [ ] [Adjust Door Sign](https://docs.google.com/presentation/d/1IQfnE3TbG3EU5zRnNKdG3kzxdYjT1ryWNWs4WWgpE04/edit?usp=sharing)
- [ ] [Gather slide-decks and other material](http://hamburg.onruby.de/admin/materials/new)

**Comment by phoet** [comment]
@janz93 is there no location yet?

**Comment by janz93** [comment]
@phoet Yes event inc. I didn't had the chance yet to add it to the website

**Comment by seiffert** [comment]
Hey, @phoet mentioned to me that you're looking for speakers. I could give a talk on how we solved monitoring and logging in Jimdo's internal container platform.

**Topics covered in the talk:**
- How the platform works (high level overview)?
- Monitoring with Prometheus and Grafana
- Notifications via Slack and PagerDuty
- Centralized logging based on the Elastic stack
- Being On-Call

Regarding the [checklist](https://github.com/rughh/planning/wiki/Speaker-Checklist): The talk would probably be ~40 minutes in English or German (Slides in English), I like questions at any time, and can propose the talk via the web form if needed.

**Comment by phoet** [comment]
@seiffert that would be great, thx! 😻

**Comment by phoet** [comment]
@janz93 ich habe das mal auf twitter geteilt, damit vielleicht auch jemand kommt

**Comment by phoet** [comment]
@emrox kannst du deine slides hier verlinken? danke!

**Comment by phoet** [comment]
changed the twitter handle https://github.com/rughh/planning/issues/109
