### ISSUE TITLE
x-ion hosting offer

### ISSUE THREAD

**Issue by janz93** [rughh/planning#112]
@bpieck thank you again for your hosting offer.
As discussed we would think about April as possible hosting time.

**Comment by phoet** [comment]
@bpieck as we already talked about, please let me know if you think that there is enough space in the venue. cheers!

**Comment by bpieck** [comment]
As explained: We will clear the developer area, since it's the biggest room. If the average of 19 participants will come, that's enough space. If many more will come, we would get into a problem.

**Comment by phoet** [comment]
@bpieck great 👍 we are going to communicate that there is limited space, so we should be ok

**Comment by bpieck** [comment]
thanks :)
