### ISSUE TITLE
April 2019 Meetup

### ISSUE THREAD

**Issue by phoet** [rughh/planning#113]
10.04.2019  19:00

- [x] Location
- [x] [Create Event](http://hamburg.onruby.de/admin/)
- [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
- [x] Promotion on Twitter
- [x] [Adjust Slides](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)
- [ ] [Adjust Door Sign](https://docs.google.com/presentation/d/1IQfnE3TbG3EU5zRnNKdG3kzxdYjT1ryWNWs4WWgpE04/edit?usp=sharing)
- [x] [Gather slide-decks and other material](http://hamburg.onruby.de/admin/materials/new)

**Comment by phoet** [comment]
location most likely https://github.com/rughh/planning/issues/112

**Comment by phoet** [comment]
@wwwbruno would you like to give your talk on the april edition? https://hamburg.onruby.de/users/wwwbruno-2922

**Comment by phoet** [comment]
@HuldaLa would you like to give your talk on the april edition? https://hamburg.onruby.de/users/huldala-256

**Comment by wwwbruno** [comment]
@phoet sure! I have the presentation ready for the meetup! Count on me 😄

**Comment by HuldaLa** [comment]
Hi Peter,
sorry, da habe ich wohl was missverstanden. Ich wollte dazu keinen Talk
halten, sonder würde liebend gerne einen Talk dazu hören. Besonders
neugierig wäre ich auf das Thema Performance ;-)
Aber dazu was vortragen, kann ich leider nicht.

LG,
Anne

Peter Schröder <notifications@github.com> schrieb am Do., 4. Apr. 2019
16:28:

**Comment by phoet** [comment]
@huldala sorry, da hab ich wohl schief geguckt

**Comment by phoet** [comment]
@wwwbruno do you want to share your slide-deck? i'll link it into the event in case you have it somewhere online.
