### ISSUE TITLE
May 2019 Meetup

### ISSUE THREAD

**Issue by halfbyte** [rughh/planning#114]
{Date of the meetup} {Time of the meetup}

- [x] Location
- [x] [Create Event](http://hamburg.onruby.de/admin/)
- [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
- [x] Promotion on Twitter
- [x] [Adjust Slides](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)
- [x] [Adjust Door Sign](https://docs.google.com/presentation/d/1IQfnE3TbG3EU5zRnNKdG3kzxdYjT1ryWNWs4WWgpE04/edit?usp=sharing)
- [ ] [Gather slide-decks and other material](http://hamburg.onruby.de/admin/materials/new)

**Comment by sebs** [comment]
Since there was a like on twitter: 

* Monorepos with lerna.js with a twist of web components

**Comment by phoet** [comment]
@sebs :tada:

**Comment by halfbyte** [comment]
@sebs If you would still be willing to give this talk at our next meeting (8th of May) could you add this (with a proper abstract) to https://hamburg.onruby.de/topics/new? Then I can add it to the event.

**Comment by sssggr** [comment]
I can give a talk about pair programming: A bit of history, the benefits, challenges and some things that might help to tackle them and of course why you should pair more often. I'll add the topic.

**Comment by halfbyte** [comment]
@sssggr 1000 Dank! As soon as I figure out how to use the new OnRuby admin interface, I'll add your talk to the event.

**Comment by sebs** [comment]
> @sebs If you would still be willing to give this talk at our next meeting (8th of May) could you add this (with a proper abstract) to https://hamburg.onruby.de/topics/new? Then I can add it to the event.

Sorry I am reposnding so shortly. I can come up with a short version of the talk 


>Developing and shipping a web component seems simple at first, but modern frontend stacks come with their own set of challenges: A wide set of browsers implements relatively new specs and not everything is set in stone yet. If you set out to create and ship your own set of custom elements this eventually needs organization and strategies to deploy the code with documentation as easy as possible and continuously while adapting to changes in the underlying frameworks and your own set of features.
> We will make use of NPM to manage dependencies and publish our own elements while we automatically deploy documentation. API resources will be accessed with OpenAPI clients and can be updated via npm as well if the underlying API canges. Lerna.js will help us to keep the repository count small, speed up development and servers as a general access point for a "one button install" and "one button build". A component catalog provides "End-User" documentation to show the components in different contexts. Test Automation helps to keep these old and new browsers at check and keep an eye on a11y issues. Look at a set of self created templates that helps the components to be uniformly structured and dependencies fit your environment.

**Comment by halfbyte** [comment]
@sebs All fine, added the topic to the event.

@sssggr I was finally able to add your talk to the event as well. @phoet's admin backend migration was timed perfectly :-D

**Comment by phoet** [comment]
@halfbyte sorry for the troubles!

**Comment by sebs** [comment]
@halfbyte I will put it into a small motivational thingie - about 10 minutes I try.

**Comment by halfbyte** [comment]
@sebs Knock yourself out. :)
