### ISSUE TITLE
July meetup 2019

### ISSUE THREAD

**Issue by halfbyte** [rughh/planning#117]
10.07. 19:00

- [x] Location
- [x] [Create Event](http://hamburg.onruby.de/admin/)
- [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
- [x] Promotion on Twitter
- [x] [Adjust Slides](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)
- [ ] [Adjust Door Sign](https://docs.google.com/presentation/d/1IQfnE3TbG3EU5zRnNKdG3kzxdYjT1ryWNWs4WWgpE04/edit?usp=sharing)
- [ ] [Gather slide-decks and other material](http://hamburg.onruby.de/admin/materials/new)

**Comment by halfbyte** [comment]
@phoet Sorry for leaving you hanging in June, I thought I made it clear I wasn't going to be able to do anything (I probably didn't).

In any case, I'm up for organising this one. Any pointers for locations? Should we just go for grill-in-the-park?

**Comment by phoet** [comment]
no worries, was a nice ruby-burgers event.

since todays siebenschläfer was the lousiest of days, i would not bet on anything outdoors this summer...

i talked to this developer woman from xing, dont remember the name though, she would like to host something at xing, maybe we could set grilling up there? will try to find out who that was.

**Comment by janz93** [comment]
@phoet her name is `Isobel` I couldn't find her twitter or Github handle so I wrote her an email in which I referred to this issue. We will see what will happen

**Comment by phoet** [comment]
@janz93 thx! next time please add me to CC

**Comment by janz93** [comment]
@phoet Oh sorry will do :)

**Comment by IzzySmith** [comment]
Hi, its `this developer woman from xing`

I am unfortunately at an offsite with my team on the 10.07. (an overnight stay so no chance to make the meetup)

One of my colleagues, Jan Habermann said he would be happy to coordinate it on the 10.07 but would need people to help him out to do that. 

Alternatively, we can host it at Xing in August, where I would be available to help him.

**Comment by haberbyte** [comment]
Unfortunately, I just saw the room is already booked on that date. 😭 
 
But as @IzzySmith already said, happy to host another time!
Sorry for that.

**Comment by phoet** [comment]
@haberbyte @IzzySmith thx, should we aim for 14th of august then? that would probably be organized with @halfbyte then.

**Comment by haberbyte** [comment]
Works for me, I put in a room reservation for the 14th, so we can do it on that day!

**Comment by lindtdev** [comment]
so we don't have a new location yet? should we ask around on twitter if someone is available for next Wednesday?

**Comment by janz93** [comment]
@lindtdev could be a good idea. If we want to stick with the grilling maybe mindmatter or phraseapp are places we could ask as I had at both location a grilling before
