### ISSUE TITLE
Meeting June 2015

### ISSUE THREAD

**Issue by titanoboa** [rughh/planning#12]
* [x] Location
* [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
* [x] Promo auf Twitter
* [x] [Push-Notification für iOS app senden](http://hamburg.onruby.de/admin/dashboard)
* [x] [Slides anpassen](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)

**Comment by halfbyte** [comment]
Kurze Durchsage: Ich scheide als Orga aus, weil abwesend und die meiste Zeit davor auch abwesend.

**Comment by phoet** [comment]
wir sind bei WLW /cc @jensblond

**Comment by phoet** [comment]
@skorfmann wie sieht es eigentlich mit deinen talk proposals aus? hast du lust?

**Comment by skorfmann** [comment]
@phoet ja, bin in Hamburg und hab Lust. Welcher soll's denn sein?

**Comment by phoet** [comment]
@skorfmann der hier hat mehr votes: http://hamburg.onruby.de/topics/rubocop-coding-with-style

wäre supi!

**Comment by skorfmann** [comment]
@phoet alright, dann kommenden Mittwoch, korrekt?

**Comment by phoet** [comment]
Jip

Sebastian Korfmann <notifications@github.com> schrieb am Do., 4. Juni 2015
09:00:

**Comment by skorfmann** [comment]
:+1:

**Comment by phoet** [comment]
haben wir auch noch nen vortrag vom @filtercake

**Comment by filtercake** [comment]
😻
