### ISSUE TITLE
October Meetup @ Publicis Pixelpark

### ISSUE THREAD

**Issue by lindtdev** [rughh/planning#123]
09 October, 19:00:00

- [x] Location
- [x] [Create Event](http://hamburg.onruby.de/admin/) https://hamburg.onruby.de/events/ruby-usergroup-hamburg-october-2019-567
- [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
- [x] Promotion on Twitter https://twitter.com/HamburgOnRuby/status/1176080004716924928
- [ ] [Adjust Slides](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)
- [ ] [Adjust Door Sign](https://docs.google.com/presentation/d/1IQfnE3TbG3EU5zRnNKdG3kzxdYjT1ryWNWs4WWgpE04/edit?usp=sharing)
- [ ] [Gather slide-decks and other material](http://hamburg.onruby.de/admin/materials/new)

**Comment by lindtdev** [comment]
Moin Bente! A talk on doorkeeper sounds great! Could you do a talk focusing on why someone would need to run their own oauth server? Make it on the shorter side, 15-20 minutes if you feel it's not going to be relevant for many, but I for one would love to listen to it.

**Comment by bpieck** [comment]
Ok, I will prepare a talk and focus as you recommended :)

**Comment by lindtdev** [comment]
Great, thank you! Do you mind also entering your talk topic on our meetup page? Under "Add a topic"/"Eigenes Thema eintragen" https://hamburg.onruby.de/events/ruby-usergroup-hamburg-october-2019-567
