### ISSUE TITLE
November Meetup @ Phrase

### ISSUE THREAD

**Issue by lindtdev** [rughh/planning#124]
13 November, 19:00:00

- [x] Location
- [x] [Create Event](http://hamburg.onruby.de/admin/) https://hamburg.onruby.de/events/ruby-usergroup-hamburg-november-2019-568
- [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
- [x] Promotion on Twitter
- [x] [Adjust Slides](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)
- [ ] [Adjust Door Sign](https://docs.google.com/presentation/d/1IQfnE3TbG3EU5zRnNKdG3kzxdYjT1ryWNWs4WWgpE04/edit?usp=sharing)
- [ ] [Gather slide-decks and other material](http://hamburg.onruby.de/admin/materials/new)

**Comment by phoet** [comment]
@nlinn ich habe deinen talk schon mal mit dem event verknüpft. @lindtdev könnte damit jetzt schon mal etwas auf twitter hausieren gehen.

**Comment by lindtdev** [comment]
Oops ja mach ich morgen

**Comment by docstun** [comment]
@lindtdev I proposed a topic that I could talk about the next UG right here at Phrase HQ: https://hamburg.onruby.de/topics/actionview-component-830

Does this need to be approved?

**Comment by lindtdev** [comment]
@docstun thank you!! Peter has connected it to the meetup page, see you next week!
