### ISSUE TITLE
December Meetup @ mindmatters

### ISSUE THREAD

**Issue by lindtdev** [rughh/planning#125]
11 December, 19:00:00

- [x] Location
- [x] [Create Event](http://hamburg.onruby.de/admin/) https://hamburg.onruby.de/events/ruby-usergroup-hamburg-december-2019-574
- [x] Add Issue ID to Event
- [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
- [x] Promotion on Twitter
- [x] [Adjust Slides](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)
- [x] [Adjust Door Sign](https://docs.google.com/presentation/d/1IQfnE3TbG3EU5zRnNKdG3kzxdYjT1ryWNWs4WWgpE04/edit?usp=sharing)
- [ ] [Gather slide-decks and other material](http://hamburg.onruby.de/admin/materials/new)

**Comment by janz93** [comment]
@phoet and @halfbyte if possible could you please share the slides of your talks?

**Comment by phoet** [comment]
@janz93 i did not have any slides

**Comment by halfbyte** [comment]
https://ruby-synth.fun/presentation.html :)
