### ISSUE TITLE
Meeting July 2015

### ISSUE THREAD

**Issue by titanoboa** [rughh/planning#13]
* [ ] Location
* [ ] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
* [x] Promo auf Twitter
* [ ] [Push-Notification für iOS app senden](http://hamburg.onruby.de/admin/dashboard)
* [ ] [Slides anpassen](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)

**Comment by titanoboa** [comment]
ich bin an dem Termin, und auch schon die anderthalb Wochen vorher, im Urlaub. Wäre also praktischer, wenn jemand anders sich um diesen Termin kümmert

**Comment by titanoboa** [comment]
Vielleicht gibt uns @weidenfreak eine sneak preview ihres eurucamp talks?

**Comment by weidenfreak** [comment]
Wenn ich dann schon so weit bin, ja :)

**Comment by phoet** [comment]
@weidenfreak übung macht den kleister!

**Comment by titanoboa** [comment]
@weidenfreak Du musst ja nicht mit dem fertigen Konferenztalk zu uns kommen. Du kannst ja auch eine vorläufige Fassung vorstellen und dann das Feedback nehmen, um die endgültige Version fertigzustellen.

**Comment by phoet** [comment]
wer oganisiert n dis hier eigentlich?

**Comment by phoet** [comment]
vielleicht will der @tubit uns ja mal bei der location findung helfen?

**Comment by titanoboa** [comment]
> wer organisiert n dis hier eigentlich?
auch wenn ich mich jetzt eingemisch und meike angefragt habe - es waere glaub ich besser wenn jemand von euch das organisiert, bin ja dann demnaechst unterwegs

**Comment by nesQuick** [comment]
Location geht halt sonst immer Jimdo :)

**Comment by weidenfreak** [comment]
Leider habe ich jetzt einen Tag vor der Usergroup einen Termin bei dem ein Arzt meinen Fuß malträtiert und ich kann wohl nur spontan beurteilen ob ich am Mittwoch fit genug bin :/

**Comment by phoet** [comment]
@weidenfreak dann lass dir den mal heile machen! gute besserung

**Comment by halfbyte** [comment]
Gah. Weiterhin weitestgehend unter Wasser, deswegen hier sehr leise unterwegs. :( Auf bestimmten Kanälen war von Grillen die Rede, das finde ich ja persönlich sehr gut. Könnte man auch einfach irgendwo im Park machen. Was eignet sich denn da so? Schanngssenpark? Darf man da grillen?

**Comment by phoet** [comment]
![screen shot 2015-07-06 at 11 34 20](https://cloud.githubusercontent.com/assets/48745/8519406/e1073aa0-23d2-11e5-93ec-58189b284bba.png)

ja, da darf man grillen. das mit dem wetter ist halt so ne sache...

**Comment by halfbyte** [comment]
Ah, Stimmt. Das hatte ich schon wieder vergessen. Alternativ versuche ich heute noch mal @weidenfreak davon zu überzeugen, das mit dem Talk-Betatest zu versuchen. Mit Glück können wir beide heute Abend abschätzen, ob das Sinn macht.

**Comment by halfbyte** [comment]
In Absprache mit @phoet, mangels Talks, wegen Orgaphlegma und weil das Wetter nun wirklich nicht nach Grillen aussieht, haben wir beschlossen, spontan eine Sommerpause einzulegen. Ich kommuniziere mal.

**Comment by halfbyte** [comment]
Sigh

**Comment by phoet** [comment]
orgaphlegma trifft es nicht ganz. trotz diverser motivations-versuche hat sich niemand gefunden der etwas erzählen will oder sonst einen kreativen vorschlag hatte was wir diesen mittwoch tun können... 

bei einer stabilen wetterlage hätte ich ein open-air-event organisiert, aber die vorhersage war alles andere als vielversprechend.

im endeffekt bekommt die rughh das was sie sich diesen monat verdient hat, nämlich nix :dancers:

**Comment by halfbyte** [comment]
Okay :) Bei mir war es Orgaphlegma :)

**Comment by titanoboa** [comment]
Mein Phlegma nennt sich Urlaub :-)

**Comment by halfbyte** [comment]
Das BESTE Phlegma ever! :)
