### ISSUE TITLE
XING - Dammtorstrasse 30 - 10.06.2020 - Meetup Hosting

### ISSUE THREAD

**Issue by SuperSlou** [rughh/planning#132]
Thank you for wanting to host the Ruby Usergroup Hamburg!

Everything that there is to know about hosting you will in find in our [README](https://github.com/rughh/planning#ausrichten--hosting) and on [our website](http://hamburg.onruby.de/locations/none?locale=en).

If you are unsure when we are still looking for a location have a look at our [schedule overview](https://github.com/rughh/planning/issues/129)

## Who is the person we can contact in case of questions?
Slim Ben Salah
slim.bensalah@xing.com

## When do you want to host us?
10.06.2020 19:00

## Is the location address still update to date?
On our [website](https://hamburg.onruby.de/locations) we offer directions to the location. Please check if your address is still correct: 
[ ] Yes
[X] No (please comment the correct address below):
Dammtorstrasse 30 20354
8th floor - Spielbudenplatz

## What do you want to offer?
[x] alcohol free beverages
[ ] beer (optional)
[x] snacks (optional) 
[ ] dinner (pizza, pretzels, etc.) (optional)

Thank you for supporting us!

**Comment by janz93** [comment]
@SuperSlou I am closing this issue since we don't plan on having any physical meetups in the near future and since your office space is also closed.
Thanks for your offer and I hope to reschedule this to some time in the future.
