### ISSUE TITLE
March Meetup

### ISSUE THREAD

**Issue by phoet** [rughh/planning#133]
11.03.2020 19:00 @ lokalportal

- [x] Location
- [x] [Create Event](http://hamburg.onruby.de/admin/)
- [x] Add Issue ID to Event
- [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
- [x] Promotion on Twitter
- [x] [Adjust Slides](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)
- [x] [Adjust Door Sign](https://docs.google.com/presentation/d/1IQfnE3TbG3EU5zRnNKdG3kzxdYjT1ryWNWs4WWgpE04/edit?usp=sharing)
- [x] [Gather slide-decks and other material](http://hamburg.onruby.de/admin/materials/new)

**Comment by phoet** [comment]
see https://github.com/rughh/planning/issues/130

**Comment by phoet** [comment]
see https://hamburg.onruby.de/events/ruby-usergroup-hamburg-marz-2020-592

**Comment by phoet** [comment]
@Stex thanks for offering to host the usergroup. i'll contact you directly via email.

**Comment by stex** [comment]
@phoet The map pin seems to point to a slightly wrong location, not sure though why as the tooltip address seems correct.

![2020-02-24 at 10 00](https://user-images.githubusercontent.com/27221/75139322-9dec4880-56ec-11ea-9627-c99540dd9b0a.png)

**Comment by phoet** [comment]
@Stex 🤷‍♂️ geocoder does not like the 14d! i changed it manually

**Comment by phoet** [comment]
@Stex does someone from localportal want to give a talk?

**Comment by stex** [comment]
@phoet Didn't hear anything yet, will ask on Monday.

**Comment by stex** [comment]
> Didn't hear anything yet, will ask on Monday.

Doesn't look like it

**Comment by johanness** [comment]
Hi!

I could give a talk about a project we did replacing an legacy ecommerce landscape. We used a lot ruby for the product synchronization. This would also contain some details about shopify and the struggle we had on the way... Does this sound interesting to you? @phoet @Stex

**Comment by phoet** [comment]
@johanness 👍 could you put your abstract here? https://hamburg.onruby.de/topics/new

i'll be tweeting this out afterwards.

**Comment by johanness** [comment]
@phoet [done](https://hamburg.onruby.de/topics/ecommerce-renewal-with-shopify-and-ruby-glue-855)

**Comment by stex** [comment]
@phoet I adjusted the door sign and will print it out

**Edit**: The pin is wrong again though 🙈

**Comment by phoet** [comment]
@Stex probably some update that geocoded it again... i just removed the c (which is breaking the geocoding) and added the address to the description
