### ISSUE TITLE
Remote June Meetup 2020

### ISSUE THREAD

**Issue by janz93** [rughh/planning#134]
10.06.2020 19:00 @ home via video call

- [x] Location
- [x] [Create Event](http://hamburg.onruby.de/admin/)
- [x] Add Issue ID to Event
- [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
- [x] Promotion on Twitter
- [x] [Adjust Slides](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)
- [x] [Adjust Door Sign](https://docs.google.com/presentation/d/1IQfnE3TbG3EU5zRnNKdG3kzxdYjT1ryWNWs4WWgpE04/edit?usp=sharing)
- [ ] [Gather slide-decks and other material](http://hamburg.onruby.de/admin/materials/new)

**Comment by janz93** [comment]
@SuperSlou you [mentioned](https://github.com/rughh/planning/issues/131#issuecomment-610906360) the possibility of someone giving a presentation. Could you check if this is still the case?

**Comment by janz93** [comment]
@SuperSlou any updates on the remote-talks option?

**Comment by SuperSlou** [comment]
Hey @janz93!
I'm waiting for answers from volunteers, will update you as soon as I have answers!
So far I have volunteers to attend, not yet to present.

**Comment by SuperSlou** [comment]
Hey again!
So, unfortunately we only have people interested in attending the Ruby meetup, but they told me they will think about presentations for the next events.

**Comment by janz93** [comment]
Hello @SuperSlou Thanks for the feedback.

@developer88 thanks for your email. We have two talks for this meetup

But it would be great if they could add the talk onto our [website](https://hamburg.onruby.de/topics/new?locale=en).
