### ISSUE TITLE
Remote Meetup July 2020

### ISSUE THREAD

**Issue by janz93** [rughh/planning#135]
08.07.2020 19:00 @ Home 🏠 

- [x] Location
- [x] [Create Event](http://hamburg.onruby.de/admin/)
- [x] Add Issue ID to Event
- [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
- [x] Promotion on Twitter
- [x] [Adjust Slides](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)
- [x] [Adjust Door Sign](https://docs.google.com/presentation/d/1IQfnE3TbG3EU5zRnNKdG3kzxdYjT1ryWNWs4WWgpE04/edit?usp=sharing)
- [ ] [Gather slide-decks and other material](http://hamburg.onruby.de/admin/materials/new)

**Comment by janz93** [comment]
Hello, @developer88 would you have time to give your presentation this meetup?

If so I would add your talk to the meetup

**Comment by developer88** [comment]
@jaz93 yep. Sounds good

**Comment by developer88** [comment]
@janz93 hi. What is zoom url? On the website it says to check *zoom* section, but I cannot find it.

**Comment by janz93** [comment]
@developer88 the zoom link will appear if you *attend* the meetup.

As we had trouble in the past that people crashed a remote meetup before.
