### ISSUE TITLE
Remote Meetup December

### ISSUE THREAD

**Issue by alster-wasser** [rughh/planning#137]
09.12.2020 19:00 @ Zoom

- [x] Location
- [x] [Create Event](http://hamburg.onruby.de/admin/)
- [ ] Add Issue ID to Event
- [ ] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
- [ ] Promotion on Twitter
- [ ] [Adjust Slides](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)

**Comment by stex** [comment]
My slides and demo application for the Cypress on Rails talk: https://stex.codes/programming/2020/12/09/cypress-on-rails-talk.html
