### ISSUE TITLE
[Talk Proposal] Cypress on Rails 2 - Electric Boogaloo

### ISSUE THREAD

**Issue by stex** [rughh/planning#139]
I could offer an updated version of [my talk on how to use cypress.io with Rails](https://stex.codes/2020/12/09/cypress-on-rails-talk.html) as only 3 people ever heard it anyway 🙈 

It would cover how to set it up, create test data with `factory_bot` directly from cypress and some best practices and comparisons to `capybara`

**Comment by stex** [comment]
@janz93 I'm on vacation in September, but could hold this talk in October, including how to use cypress in (Gitlab) CI with backend and other dependencies as services

**Comment by janz93** [comment]
@Stex Thanks for the update.

I will add you to the speaker list for October 🎉 

#147

**Comment by janz93** [comment]
I saw that you will attend the November meetup.
Does this mean you also could give your talk there?

#148

**Comment by stex** [comment]
Yes, sounds good :)
