### ISSUE TITLE
code.talks

### ISSUE THREAD

**Issue by phoet** [rughh/planning#14]
ich habe grade eine email von @galan bekommen:

> ich bin Daniel von der Java User Group Hamburg. Am 29./30. September
findet erneut die code.talks Konferenz statt, und wir planen einen
lockeren Community-Corner. In der aktuellen Form würde jede
Usergroup/Meetup einen Zeitslot (ca. 30-60m) den Corner für sich
beanspruchen können. Dieses würde dann auch im Konferenzplan stehen, so
dass Interessierte vorbei schauen können. Wie dann der Slot und
Community-Corner gestaltet wird, steht im großen und ganzen der
jeweiligen Gruppe frei.

> Von daher meine Frage an Dich ob Du und/oder andere Organisatoren bzw.
Repräsentanten Deiner Gruppe bei der Konfernz vor Ort sein werden?

> Natürlich muss man erst einmal schauen wie viele Usergroups anwesend
sein können, damit die Planung weiter gehen kann, insofern bin ich auf
Dein Zeitnahes Feedback gespannt.

hat die konferenz schon jemand aufm radar?

/cc @halfbyte @titanoboa

**Comment by nesQuick** [comment]
Ich bin als speaker vor ort, die PHPUG hat die mail auch bekommen

2015-05-31 14:53 GMT+02:00 Peter Schröder <notifications@github.com>:

**Comment by titanoboa** [comment]
Ich hab bisher nicht geplant, die Konferenz zu besuchen.

**Comment by phoet** [comment]
sieht wohl nicht so aus als wenn jemand hin geht
