### ISSUE TITLE
[Talk Proposal] Turbo, Stimulus and Github's ViewComponents in Rails 7

### ISSUE THREAD

**Issue by stex** [rughh/planning#140]
A talk about *modern, dynamic and modular* ™️ Rails views with Hotwire and ViewComponents, including Turbo Frames and `shakapacker`/Importmaps

**Comment by janz93** [comment]
@Stex do you think you will be able to give the talk at the [August Meetup](https://github.com/rughh/planning/issues/144)?

**Comment by janz93** [comment]
@stex is this something you still would like to present?

**Comment by stex** [comment]
I'd likely go with `phlex` instead of `view_copmonents` now, but yes.
Unfortunately, I currently don't have the time to prepare a talk :/

**Comment by janz93** [comment]
Okay, in this case, I would suggest closing this issue and you create a new one when you have the time to create a talk.
What do you think about this plan?

**Comment by stex** [comment]
sounds good 🙂
