### ISSUE TITLE
[Talk Proposal] TTY::Toolkit

### ISSUE THREAD

**Issue by JoschkaSchulz** [rughh/planning#142]
A talk about the collection of the tty toolkit collection. It's not the newest stuff out there, but it could be nice for those who haven't heard about it.

https://ttytoolkit.org/

maybe could be a live coding talk

**Comment by janz93** [comment]
Hey @JoschkaSchulz would it be possible for you to give your talk next week #143
Or would some different time work better for you

**Comment by JoschkaSchulz** [comment]
Hey, 

Not sure if I get everything together that quick. Can I tell you Monday? I would try to build a presentation on Sunday.

**Comment by janz93** [comment]
Yeah sorry for the late info.
We had trouble finding a location 🙈 

If a big presentation is to much to ask I would suggest to maybe have it as a lighting talk and see if others are willing to make one as well.

**Comment by JoschkaSchulz** [comment]
Hey @janz93, 
I think I'm not able to hold the talk... Sadly can't make it to ruby usergroup this week, but I would prepare everything for next months usergroup if that would be fine?

**Comment by janz93** [comment]
Yes this will be fine as well 😄

**Comment by janz93** [comment]
Hey @JoschkaSchulz do you think you will be able to give the talk at the #144 August Meetup?

**Comment by JoschkaSchulz** [comment]
sorry, thought I answered already :) I think I will be able to hold the talk. Would like to know, do I need to talk in english or can I do the talk in german? (just like to know it when I prepare everything on saturday)

**Comment by janz93** [comment]
English would be preferred as it is our default language.

If you feel more comfortable in German we will think about a way how it can be somehow transparent for non German speakers

**Comment by JoschkaSchulz** [comment]
ah no it's fine :) I asked just because of the preparation of the talk

**Comment by salzig** [comment]
Thanks for the talk @JoschkaSchulz
