### ISSUE TITLE
August 2022 Meetup

### ISSUE THREAD

**Issue by janz93** [rughh/planning#144]
10.08.2022 19:00 @ {location}

- [x] Location
- [x] [Create Event](http://hamburg.onruby.de/admin/)
- [x] Add Issue ID to Event
- [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
- [x] Promotion on Twitter
- [x] [Adjust Slides](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)
- [x] [Adjust Door Sign](https://docs.google.com/presentation/d/1IQfnE3TbG3EU5zRnNKdG3kzxdYjT1ryWNWs4WWgpE04/edit?usp=sharing)
- [x] [Gather slide-decks and other material](http://hamburg.onruby.de/admin/materials/new)

**Comment by JoschkaSchulz** [comment]
TTY toolkit Talk
https://docs.google.com/presentation/d/1iNQ5293mF64HB_vOKXBhevFGRs1VwPetx0LT88yzpsU/edit?usp=sharing

[tty toolkit (1).pdf](https://github.com/rughh/planning/files/9306932/tty.toolkit.1.pdf)
