### ISSUE TITLE
September 2022 Meetup

### ISSUE THREAD

**Issue by janz93** [rughh/planning#146]
2022-09-14 19:00:00 @ MissionMe

- [x] Location
- [x] [Create Event](http://hamburg.onruby.de/admin/)
- [x] Add Issue ID to Event
- [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
- [x] Promotion on Twitter
- [x] [Adjust Slides](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)
- [x] [Adjust Door Sign](https://docs.google.com/presentation/d/1IQfnE3TbG3EU5zRnNKdG3kzxdYjT1ryWNWs4WWgpE04/edit?usp=sharing)
- [x] [Gather slide-decks and other material](http://hamburg.onruby.de/admin/materials/new)

**Comment by janz93** [comment]
@huldalam we are looking for a location for the meetup.
Could you see your company hosting this or some of our next meetups?

Thanks in advance Jan :)

**Comment by huldalam** [comment]
Hi @janz93 ,
mit wievielen Leuten rechnet ihr? Das Büro ist hier nicht ganz so groß und hat nicht wirklich Präsentationsmöglichkeiten :thinking: 

Grützie,
Anne

**Comment by janz93** [comment]
@huldalam Wir Planen so mit ca. 15 Personen pro Meetup.
Allerdings klingt das jetzt nicht danach, dass ihr die besten Möglichkeiten zum Hosten habt.

Da wir auch schon eine Location für den September gefunden haben, ist das ganze auch nicht mehr so zeitkritisch.

Vielleicht bietet es sich ja mal an, dass man in Ruhe das Ganze besprechen kann.

**Comment by huldalam** [comment]
Hi. Ich glaube, für 15 Leute wäre schon Platz, aber halt ohne großen Präsentationsmodus. Von daher ist es ganz gut, wenn ihr andere Locations vorzieht ;-)
