### ISSUE TITLE
Oktober 2022 Meetup

### ISSUE THREAD

**Issue by janz93** [rughh/planning#147]
12.10.2022 19:00 @ {location}

- [ ] Location
- [ ] [Create Event](http://hamburg.onruby.de/admin/)
- [ ] Add Issue ID to Event
- [ ] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
- [ ] Promotion on Twitter
- [ ] [Adjust Slides](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)
- [ ] [Adjust Door Sign](https://docs.google.com/presentation/d/1IQfnE3TbG3EU5zRnNKdG3kzxdYjT1ryWNWs4WWgpE04/edit?usp=sharing)
- [ ] [Gather slide-decks and other material](http://hamburg.onruby.de/admin/materials/new)

**Comment by stex** [comment]
@janz93 Just to be sure: There is no October meetup, correct? At least I didn't see it on the website.

**Comment by janz93** [comment]
@Stex Yes that is correct.
We will be at the heruko in Helsinki
