### ISSUE TITLE
November 2022 Meetup

### ISSUE THREAD

**Issue by janz93** [rughh/planning#148]
09.11.2022 19:00 @ [njiuko](https://hamburg.onruby.de/locations/njiuko-72)

- [x] Location
- [x] [Create Event](http://hamburg.onruby.de/admin/)
- [x] Add Issue ID to Event
- [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
- [x] Promotion on Twitter
- [x] [Adjust Slides](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)
- [x] [Adjust Door Sign](https://docs.google.com/presentation/d/1IQfnE3TbG3EU5zRnNKdG3kzxdYjT1ryWNWs4WWgpE04/edit?usp=sharing)
- [x] [Gather slide-decks and other material](http://hamburg.onruby.de/admin/materials/new)

**Comment by stex** [comment]
Hey @janz93!
Just to confirm: I'll hold my cypress task next week?

**Comment by janz93** [comment]
Correct 👍

**Comment by janz93** [comment]
@stex Could you add here a link to the repo and maybe your slides?

**Comment by stex** [comment]
Sorry, only tweeted the link, but forgot to add it here

https://stex.codes/2022/11/09/cypress-on-rails-2-electric-boogaloo.html
