### ISSUE TITLE
December 2022 Meetup

### ISSUE THREAD

**Issue by janz93** [rughh/planning#149]
14.12.2202 19:00 @ TBD

- [x] Location
- [x] [Create Event](http://hamburg.onruby.de/admin/)
- [x] Add Issue ID to Event
- [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
- [x] Promotion on Twitter
- [x] [Adjust Slides](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)
- [x] [Adjust Door Sign](https://docs.google.com/presentation/d/1IQfnE3TbG3EU5zRnNKdG3kzxdYjT1ryWNWs4WWgpE04/edit?usp=sharing)
- [x] [Gather slide-decks and other material](http://hamburg.onruby.de/admin/materials/new)

**Comment by iltempo** [comment]
Yoga Easy GmbH & Co. KG
Dorotheenstr. 48
22301 Hamburg
