### ISSUE TITLE
Meeting August 2015

### ISSUE THREAD

**Issue by halfbyte** [rughh/planning#15]
Termin: 12. 08. 19:00

* [x] Location
* [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
* [x] Promo auf Twitter
* [x] [Push-Notification für iOS app senden](http://hamburg.onruby.de/admin/dashboard)
* [x] [Slides anpassen](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)

**Comment by halfbyte** [comment]
Je nach Wetter vielleicht noch mit Grillen verbinden? Orga übernehme ich.

**Comment by phoet** [comment]
:+1:

**Comment by volkert** [comment]
Ich hatte beim letzten Meetup mal mit Kerstin gesprochen und wenn es für alle beteiligten in Ordnung wäre, würden wir bei XING die Location und Verpflegung in Form von Getränken stellen.

Einen Talk hätte ich auch beizusteuern "Marrying AngularJS with Rails", wo ich Erfahrungen über eine Produktentwicklung bei XING mit genannter Technologie teilen könnte.

Über Feedback freu ich mich!

**Comment by phoet** [comment]
@volkert das ist super! vielleicht kannst du dein thema kurz hier eintragen und beschreiben worum es geht, in welcher sprache du ihn halten willst/kannst und wie lange er ungefähr dauert (mit oder ohne QA): http://hamburg.onruby.de/topics/new

**Comment by volkert** [comment]
Done!

**Comment by titanoboa** [comment]
:+1: 
ich werde allerdings schon wieder in der Weltgeschichte unterwegs sein, bin an dem Abend also leider nicht da

**Comment by halfbyte** [comment]
@volkert Ich hab die Veranstaltung angelegt - Sollte das jetzt bei Euch doch nicht passen bitte ich um möglichst baldige Rückmeldung.

**Comment by halfbyte** [comment]
@Salzig: Steht Dein Angebot für August? Wenn ja, würde ich das mal mit reinnehmen.

**Comment by halfbyte** [comment]
@weidenfreak: Wie siehts aus? Magst Du Deinen Talk auf http://hamburg.onruby.de/topics/new? eintragen, dann kann ich den da mit reinwerfen?

**Comment by halfbyte** [comment]
Je nachdem wie mein Lightning-Talk gleich beim Eurucamp ankommt, würde ich den auch noch mit reinwerfen, kann man auch gut weglassen wenn es zu spät wird.

**Comment by weidenfreak** [comment]
Ich habe meinen Talk eingetragen.

**Comment by Salzig** [comment]
@halfbyte grundsätzlich ja. Kann ich dir Morgen endgültig bescheid sagen?

**Comment by halfbyte** [comment]
@Salzig Klar. Noch haben wir ja Zeit und wir haben ja bereits Talks.

**Comment by Salzig** [comment]
@halfbyte Slides habe ich wieder gefunden, demo allerdings nicht. Wie ist es euch lieber? Diesen Monat drei Vorträge oder schon mal einen für nächsten?

**Comment by phoet** [comment]
+1 für nächstes mal

**Comment by nesQuick** [comment]
:+1: was @phoet sagt

**Comment by titanoboa** [comment]
ja, nächstes Mal klingt gut. Ich melde mich auch einfach mal freiwillig für die Septemberorga, hab ich ja ne ganze Weile nicht gemacht wegen Urlaub und so.
