### ISSUE TITLE
Meetup in January

### ISSUE THREAD

**Issue by bpieck** [rughh/planning#150]
Hi Jan,

I talked to my boss and saw, you still look for a location in January. So I could propose to have that meetup in Ottensen at brandnooz Media GmbH.

## Who is the person we can contact in case of questions?
me

## When do you want to host us?
2023-01-11 19:00

## Is the location address still update to date?
brandnooz Media GmbH
Holstentwiete 15
22763 Hamburg

## What do you want to offer?
[x] alcohol free beverages
[x] beer (optional)
[x] snacks (optional) 

About a topic: My collegue Kashyap proposed to have a talk about "integrating alchemy cms into an existing project" if this could be interesting for you. Or I could talk and show a little, how we misused turbo and put parts of a page into independend services via lazy loading turbo frames (I still don't know, if that was a good idea though :P)

**Comment by janz93** [comment]
@bpieck Hey Bente sorry for the late response. 
That sounds wonderful.

I added you as our location for January 🎊

**Comment by janz93** [comment]
@bpieck sure it would be great if you both could add the topic's on the web site.
This way we can schedule them either both on in January or at a later time

**Comment by janz93** [comment]
@bpieck It would be great if you could tell me which topic I should add the meetup 😄

**Comment by bpieck** [comment]
Hi Jan,

Happy new year

Kashyap is preparing a talk about: “Integrating alchemy cms into an existing rails application”.

I cannot promise to be well prepared for this turbo thing, don't add that to the topics right now. But if anyone is interested in the hacks we did for that - still in an experimental stage (and maybe even abandoned in nearby future before ever deployed ;) ) - I will just show something more adhoc.
