### ISSUE TITLE
Location Offer October (2023)

### ISSUE THREAD

**Issue by hejhugo** [rughh/planning#155]
Hi Jan,

as discussed, we would like to host the Usergroup in October at OMR (ramp106 GmbH) in the Schanze.

## Who is the person we can contact in case of questions?
me

## When do you want to host us?
2023-10-11 19:00

## Is the location address still update to date?
On our [website](https://hamburg.onruby.de/locations) we offer directions to the location. Please check if your address is still correct: 
- [ ] Yes
- [x] No (please comment the correct address below)
OMR - ramp106 GmbH
Lagerstr. 36
20357 Hamburg

## What do you want to offer?
- [x] alcohol free beverages
- [x] beer (optional)
- [ ] snacks **tbd.**
- [ ] dinner **tbd.** (pizza, pretzels, etc.) 

Topics are tbd.

**Comment by janz93** [comment]
@hejhugo Thanks for the Location Issue.

This simplifies communication.

I will add our location pool with the address and look forward to the October

**Comment by janz93** [comment]
@hejhugo just a quick checkin 👋
Is everything clear for the meetup or do you have any questions which I could help you with? 🙂
Also do you know if you want to present something this meetup or at a later point in time?

**Comment by janz93** [comment]
@hejhugo just a quick checkin 👋
Is everything clear for the meetup or do you have any questions which I could help you with? 🙂
Also do you know if you want to present something this meetup or at a later point in time?
