### ISSUE TITLE
Location Offer November 2023

### ISSUE THREAD

**Issue by WTF-Selena** [rughh/planning#160]
Thank you for wanting to host the Ruby Usergroup Hamburg!

Everything that there is to know about hosting you will in find in our [README](https://github.com/rughh/planning#ausrichten--hosting) and on [our website](http://hamburg.onruby.de/locations/none?locale=en).

If you are unsure when we are still looking for a location have a look at our [schedule overview](https://github.com/rughh/planning/issues/129)

## Who is the person we can contact in case of questions?
me

## When do you want to host us?
2023-11-08 19:00

## Is the location address still update to date?
On our [website](https://hamburg.onruby.de/locations) we offer directions to the location. Please check if your address is still correct: 
[ ] Yes
[x] No (please comment the correct address below)

Whiskey Tango Foxtrot GmbH
Gasstrasse 4
22761 Hamburg
Deutschland

## What do you want to offer?
[x] alcohol free beverages
[x] beer (optional)
[x] snacks (optional) 
[ ] dinner (pizza, pretzels, etc.) (optional)

Thank you for supporting us!

**Comment by janz93** [comment]
@WTF-Selena hello and sorry for the late reply.
Thank you for the offer to host us 🎉 

We already have for the November a hosting location 😬 
Due to my mistake, I forgot to update the overview 🙈 

Would a different time this year or at the beginning of next year work for you?

**Comment by WTF-Selena** [comment]
@janz93 Thanks for letting me know :)
How about the date in December, the 13th, is it still free?

**Comment by janz93** [comment]
@WTF-Selena Yes this is still free!

**Comment by WTF-Selena** [comment]
@janz93 We'll take it!

**Comment by janz93** [comment]
Perfect I created a new issue #162  for this.
