### ISSUE TITLE
September 2023 Meetup

### ISSUE THREAD

**Issue by janz93** [rughh/planning#161]
13.09.2023 @ yogaeasy

- [x] Location
- [x] [Create Event](http://hamburg.onruby.de/admin/)
- [x] Add Issue ID to Event
- [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
- [x] Promotion on Twitter
- [x] [Adjust Slides](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)
- [x] [Adjust Door Sign](https://docs.google.com/presentation/d/1IQfnE3TbG3EU5zRnNKdG3kzxdYjT1ryWNWs4WWgpE04/edit?usp=sharing)
- [ ] [Gather slide-decks and other material](http://hamburg.onruby.de/admin/materials/new)

**Comment by janz93** [comment]
@code-206 I'm looking forward to the talk #159 
Could you quickly confirm that this time still works for you :)

**Comment by iltempo** [comment]
YogaEasy is happy to host the September meetup edition in collaboration with Mind Matters.

YogaEasy GmbH
Hoheluftchaussee 95a
20253 Hamburg

cc @JenniferSpry
