### ISSUE TITLE
Location Offer December 2023

### ISSUE THREAD

**Issue by janz93** [rughh/planning#162]
Thank you for wanting to host the Ruby Usergroup Hamburg!

Everything that there is to know about hosting you will in find in our [README](https://github.com/rughh/planning#ausrichten--hosting) and on [our website](http://hamburg.onruby.de/locations/none?locale=en).

If you are unsure when we are still looking for a location have a look at our [schedule overview](https://github.com/rughh/planning/issues/129)

## Who is the person we can contact in case of questions?
@WTF-Selena

## When do you want to host us?
13.12.2023 19:00

## Is the location address still update to date?
On our [website](https://hamburg.onruby.de/locations) we offer directions to the location. Please check if your address is still correct: 
[ ] Yes
[x] No (please comment the correct address below)

Whiskey Tango Foxtrot GmbH
Gasstrasse 4
22761 Hamburg
Deutschland

## What do you want to offer?
[x] alcohol free beverages
[x] beer (optional)
[x] snacks (optional) 
[ ] dinner (pizza, pretzels, etc.) (optional)

Thank you for supporting us!

**Comment by WTF-Selena** [comment]
@janz93 Hi Jan, I haven't heard from you in a while :) Is there something that we can start doing?

**Comment by janz93** [comment]
@WTF-Selena Hi Selena, I can only think of two things:
* We started a small tradition where we have for the Christmas meetup Glühwein and waffels. If you want to continue this tradition that would be great 😅 
* You could ask if anyone would like to give a talk and if so I would be happy if they could add them to our website.

Anything else is already answered in the issue :)

**Comment by WTF-Selena** [comment]
@janz93 We can offer Glühwein and Waffles for that day :) We will have a waffle-station, with batter, toppings and a waffle iron and everybody can make their own :)
