### ISSUE TITLE
[Tiny talk proposal] (How) can we support junior developers?

### ISSUE THREAD

**Issue by code-206** [rughh/planning#163]
Unfortunaltly a talk at the Euruko 2023 about junior developers in our community was not ranked.
But I met Steven R. Baker, the creator of RSpec and he inspired me on that topic.

I've prepared a small talk and some slides to share my thoughts. The main focus is the follow-up discussion on:

- Is there a need for supporting junior developers
- Potential ways to offer support
- ...

**Comment by JoschkaSchulz** [comment]
I talked with @janz93 about 'what can we do to get more juniors in ruby' and the disappearing events for starting skill levels. 

Would absolutely love to find ways to support junior devs.

**Comment by janz93** [comment]
@code-206 Yes I would love to hear your ideas! @JoschkaSchulz thanks for the shoutout. Let's see what can grow out of this motivation.

@code-206 is this something you want to share next week or at a later point in time?

**Comment by code-206** [comment]
I am starting today to create some slides with 2 ideas ;) for Wednesday.
