### ISSUE TITLE
[Talk Proposal] fly.io experiences

### ISSUE THREAD

**Issue by janz93** [rughh/planning#169]
Hey @skorfmann I missed you email and just saw that you are interested in talking about `fly.io`
Is this still the case?

**Comment by skorfmann** [comment]
@janz93 Yes, happy to do that talk. Something along the lines of "From Zero to Ruby FaaS" - probably something in the range of 20 - 30 minutes. Perhaps I'll come up with a better name once the talk is ready :) 

Are you aiming for April?

**Comment by janz93** [comment]
@skorfmann that would be my idea. Yet if this is too soon, May would also work. What do you think is better for you?

**Comment by skorfmann** [comment]
> @skorfmann that would be my idea. Yet if this is too soon, May would also work. What do you think is better for you?

All good, April would work 👍

**Comment by janz93** [comment]
Perfect 🎉 
To make it easy to promote and more visible I would like to ask you to add the [final talk to our website](https://hamburg.onruby.eu/topics/new).

**Comment by janz93** [comment]
@skorfmann do you have any slides you want to share or should I just close this issue?
