### ISSUE TITLE
Meeting Oktober 2015

### ISSUE THREAD

**Issue by titanoboa** [rughh/planning#17]
Termin: 14. 10. 19:00

* [x] Location
* [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
* [x] Promo auf Twitter
* [x] [Push-Notification für iOS app senden](http://hamburg.onruby.de/admin/dashboard)
* [x] [Slides anpassen](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)

**Comment by halfbyte** [comment]
Jens von [wlw_dev](https://twitter.com/wlw_dev) hat Angeboten, die UG zu hosten. 

Dann brauchen wir jetzt nur noch Talks.

**Comment by titanoboa** [comment]
es gab auch noch diese angebot von sinnerschrader per mail. hat denen schon jemand geantwortet? vielleicht könnten die dann im dezember? november ist ja glaub ich mindmatters, oder war das noch nicht fix?

**Comment by halfbyte** [comment]
@titanoboa Ich jedenfalls nicht. Ich hab die Email zu spät gesehen.

**Comment by jensblond** [comment]
@johanness von @werliefertwas hat ein Vorschlag für ein Thema: API Caching
Ausserdem frage ich bei mir im Team noch mal, ob jemand eine Idee hat.

**Comment by MrMarvin** [comment]
Ach, hier diskutiert ihr... Das Angebot bei Sinnerschrader steht, es hat uns noch niemand geantwortet und der Kühlschrank ist voll.;-)

**Comment by phoet** [comment]
@MrMarvin danke für euer angebot! bin im moment ein bissl beschäftigt, deshalb habe ich nicht gleich zurück geschrieben...

theoretisch sind dieser und nächster monat schon "vergeben", wäre für euch denn im dezember auch denkbar?

**Comment by halfbyte** [comment]
@jensblond Mögt Ihr die Sachen mal auf [onruby.de](http://hamburg.onruby.de/topics/new) eintragen, dann kann ich da gleich noch ein Event draus machen.

**Comment by halfbyte** [comment]
(Notiz an @titanoboa und @phoet: Ich bin ab Montag Mittag raus aus dem Thema weil Urlaub und so. Bis dahin versuche ich die Fäden noch in der Hand zu halten)

**Comment by jensblond** [comment]
Ist eingetragen!
