### ISSUE TITLE
April 2024 Meetup

### ISSUE THREAD

**Issue by janz93** [rughh/planning#170]
10.04.2024 19:00 @ yogaeasy

- [x] Location
- [x] [Create Event](http://hamburg.onruby.de/admin/)
- [x] Add Issue ID to Event
- [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
- [x] Promotion on Twitter
- [x] [Adjust Slides](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)
- [ ] [Adjust Door Sign](https://docs.google.com/presentation/d/1IQfnE3TbG3EU5zRnNKdG3kzxdYjT1ryWNWs4WWgpE04/edit?usp=sharing)
- [ ] [Gather slide-decks and other material](http://hamburg.onruby.de/admin/materials/new)

**Comment by janz93** [comment]
#169 @skorfmann passt dieser Termin noch oder sollen wir den Talk schieben?

**Comment by skorfmann** [comment]
passt von meiner Seite aus 👍

**Comment by janz93** [comment]
Perfekt 🎉 
Magst du den Tlak noch auf der Webseite eintragen? Dann kann ich den besser promoten

**Comment by skorfmann** [comment]
https://hamburg.onruby.de/topics/a-tiny-ruby-faas-1055
