### ISSUE TITLE
November meetup

### ISSUE THREAD

**Issue by phoet** [rughh/planning#18]
Termin: 11.11. 19:00

* [x] Location
* [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
* [x] Promo auf Twitter
* [x] [Push-Notification für iOS app senden](http://hamburg.onruby.de/admin/dashboard)
* [x] [Slides anpassen](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)

**Comment by phoet** [comment]
mindmatters hat sich angeboten das event zu hosten

**Comment by nesQuick** [comment]
Ich würde meinen HTTP/2 talk anbieten

**Comment by titanoboa** [comment]
@nesQuick super, dann trag den doch bei Gelegenheit auf http://hamburg.onruby.de/ ein

**Comment by nesQuick** [comment]
erledigt :)

**Comment by titanoboa** [comment]
:+1:

**Comment by titanoboa** [comment]
Das mit mindmatters ist fix und kann auf onruby eingetragen werden, oder nicht?
Ich übernehm dann einfach mal das November-Issue freiwillig...

**Comment by phoet** [comment]
da werde ich auch höchst wahrscheinlich wegen :baby_bottle: :baby: fehlen

**Comment by titanoboa** [comment]
so, zweiter talk wird das arbeiten-in-australien thema

**Comment by halfbyte** [comment]
Da Sebastian ausfällt: Ich würde meinen schon lang angekündigten Lightning-Talk in die Waagschale werden. Spricht was dagegen?

**Comment by phoet** [comment]
Tuestues

Jan Krutisch <notifications@github.com> schrieb am Mi., 11. Nov. 2015,
17:02:
