### ISSUE TITLE
December meetup

### ISSUE THREAD

**Issue by titanoboa** [rughh/planning#19]
Termin: 9.12. 19:00

* [x] Location
* [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
* [x] Promo auf Twitter
* [x] [Push-Notification für iOS app senden](http://hamburg.onruby.de/admin/dashboard)
* [ ] [Slides anpassen]
(https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)
* [x] Waffeleisen (2 Stück) besorgen
* [ ] Glühwein organisieren
* [ ] Topf oder Warmhaltebehälter für Glühwein organisieren

**Comment by titanoboa** [comment]
Sinnerschrader hat angeboten, demnächst mal die usergroup zu hosten. Ob das zum Dezembertermin klappt, müssen wir noch mit @MrMarvin absprechen (keine Eile)

**Comment by phoet** [comment]
wir haben auch [einen talk](http://hamburg.onruby.de/topics/sonic-pi-elektronische-musik-fette-beats-aus-ruby-code) von @hzulla

**Comment by halfbyte** [comment]
Anfrage an @MrMarvin ist per Email raus. Event lege ich sofort nach Antwort an.

**Comment by MrMarvin** [comment]
Vor mir aus sehr gerne. Ich kläre das im Laufe des Tages mit unserem office team. Denke aber das passt

**Comment by halfbyte** [comment]
@MrMarvin Ich hab das jetzt schon mal eingetragen. Sollte das wider erwarten nicht passen, sag bitte möglichst schnell bescheid. Wir sollten dann Anfang der Woche schnell die logistischen Aufgaben rund um Waffeln und Glühwein lösen :)

**Comment by hzulla** [comment]
Freue mich drauf.

Gibt es einen Beamer? Wenn ja, welcher Anschluss?

Gibt es eine Stereoanlage? Wenn ja, welcher Anschluss? (Wenn nein bringe ich eigene Lautsprecher mit.)

**Comment by phoet** [comment]
@hzulla ich denke mal das es bei sinnerschrader sowohl beamer als auch sound gibt.

in der regel haben wir immer adapter für mac und sound per klinke oder airplay. vielleicht kann @MrMarvin noch mal bescheid sagen wenn dem nicht so ist.

**Comment by hzulla** [comment]
Ich habe keinen Mac. Airplay habe ich nicht. Ich brauche HDMI für Beamer und Sound oder VGA für Beamer und Klinke für Sound.

**Comment by MrMarvin** [comment]
> Ich brauche HDMI für Beamer und Sound oder VGA für Beamer und Klinke für Sound.

Hammwa, kein Problem.

**Comment by hzulla** [comment]
Aber was. Wenn HDMI geht kann ich das leichtere Laptop einpacken.

**Comment by hzulla** [comment]
Ach was. Ich packe das große Laptop ein und gut ist. :-)

**Comment by MrMarvin** [comment]
Ah, sorry @hzulla, hab nicht kapiert das das für dich noch ableitet was du einpackst. Also vorhanden ist VGA zum Projektor und externe Aktivlautsprecher über Klinke. Bis nachher!

**Comment by halfbyte** [comment]
@MrMarvin Wie sieht's aus mit 'nem Waffeleisen? Glühweintopf? Habt Ihr da was da? Müssen wir noch was organisieren? Kann ich Euch die Beschaffung des Glühweins aufs Auge drücken? Ich bin leider etwas angeschlagen, deswegen nicht so wahnsinnig mobil, wäre toll, wenn Ihr da mit helfen könntet.

Was Waffeln/Waffelteig angeht: Ich hab heute morgen spontan einen Mixer und eine Rührschüssel eingepackt, zur Not können wir das also spontan fixen, sofern das Waffeleisen-Problem gefixt ist.

**Comment by MrMarvin** [comment]
> Glühweintopf?

Ja, haben wir was. Gerade gestern erprobt.

> Kann ich Euch die Beschaffung des Glühweins aufs Auge drücken?

Okay, ich kann nachher noch mal beim REWE vorbei. Bin da leider überhaupt nicht firm welche Marke und wie viel man da kaufen sollte?!

> Waffeleisen?

Habs noch nicht gesehen, aber soll ja im Haus eins geben. Frag gleich noch mal unten nach und verwahre es dann sicher.

**Comment by halfbyte** [comment]
@MrMarvin Was die Mengen angeht: Vielleicht kann der @phoet da helfen, der hat das die letzten Male verwaltet, glaube ich. Geheimtipp: Glögg bei IKEA kaufen. Wenn der @phoet hier reinschauen würde, hätte ich auch nichts gegen Übersendung eines Waffelteig-Rezepts, falls vorhanden. Ich würde dann über Mittag dafür einkaufen und die Zutaten mitbringen.

Vielen Dank für die Hilfe!

**Comment by phoet** [comment]
waffelrezept (letztes wochenende getestet): http://mobile.chefkoch.de/rezepte/m1283881233743104/Quarkwaffeln.html

eine portion reicht für knapp 4 leute, also so 4 bis 5 portionen

viele leute mögen aus mysteriösen gründen keine glühwein, ich würde also für 8 leute glühwein kaufen. ich denke mal, dass die reste bei euch sowieso weg gehen werden, deshalb ein wenig überprovisioniert 5 liter kaufen.

**Comment by halfbyte** [comment]
Waffelrezeptzutaten (x4, das ging am besten auf) sind gekauft, bringe ich nachher mit. Ich hab keine Waage am Mann, das ist mir noch aufgefallen, @MrMarvin Kannst Du aus der Poststelle eine Briefwage "leihen"? Ansonsten machen wir das Pi mal Auge.
