### ISSUE TITLE
promo und swag

### ISSUE THREAD

**Issue by phoet** [rughh/planning#2]
anschreiben:

* [x] docker
* [x] oreilly
* [x] jetbrains
* [x] heroku
* [x] github

**Comment by phoet** [comment]
`SwagOverflowError`

**Comment by nesQuick** [comment]
Die Telerik dinger evtl über twitter so oder verteilen?

**Comment by phoet** [comment]
das mit dem twitter hat nur so mittel funktioniert, ich würde sagen beim nächsten mal wieder was verteilen.

**Comment by phoet** [comment]
@nesQuick ich hab dir mal zugangsdaten für twitter und so per gmail geschickt

**Comment by nesQuick** [comment]
@phoet alles klar, cool. Ich hätte die keys jetzt einfach mit dem account vertwittert :D
