### ISSUE TITLE
January 2016 meetup

### ISSUE THREAD

**Issue by titanoboa** [rughh/planning#20]
Termin: 13.01.2016 19:00

* [x] Location
* [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
* [x] Promo auf Twitter
* [x] [Push-Notification für iOS app senden](http://hamburg.onruby.de/admin/dashboard)
* [x] [Slides anpassen](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)

**Comment by toadle** [comment]
Hey zusammen - wir würde das wieder bei Hanse Ventures organisieren. Keine Ahnung, ob ich das hier noch eintragen soll/muss :-)?

**Comment by titanoboa** [comment]
Vielen Dank @toadle  wir kommen gern zu Euch!

**Comment by halfbyte** [comment]
Alternativ hätte @andywenk Lust, das bei sum.cumo stattfinden zu lassen, aber das ginge auch im Februar, sagt er. First come first serve oder "neueinsteiger" first? Und, @titanoboa,  entnehme ich Deinem Kommentar dass Du den Vorsitz des Organisationskomitees für Januar übernimmst? :)

**Comment by andywenk** [comment]
Hi all - ich verfolge den thread hier. Sprecht mich gerne an. @halfbyte schon mal herzlichen Dank!

**Comment by titanoboa** [comment]
Ich war von first come first serve ausgegangen bzw. hatte angesichts des Emailwechsels mit hv angenommen, dass das schon fix eingetütet ist, und das schonmal bei onruby vermerkt. Das kann man aber natürlich noch ändern.

Ist ja eher ein Luxusproblem, wenn wir gerade auf verschiedenen Kanälen mehrere Raumangebote haben :-)

Wenn nötig, kann ich den Januar übernehmen - eigentlich fand ich aber lediglich, dass irgendjemand (tm) ja schonmal antworten kann, auch wenn wir noch nicht ausgehandelt haben, wer von uns 'dran' ist

bin aber bis anderthalb Tage vorher ausser Landes (lies: mit Hotel- und Flughafen WiFi gestraft) und würde insofern im Januar lieber dem Reisekomitee vorsitzen (es sei denn für Euch ist Januar auch schwierig, dann kann ich den schon übernehmen)

**Comment by andywenk** [comment]
@titanoboa ich kläre das morgen und poste dann - Danke

**Comment by titanoboa** [comment]
@andywenk jetzt bin ich verwirrt - du klärst, ob auch Februar geht? Oder was meintest Du?

**Comment by andywenk** [comment]
@titanoboa nee ... Du schreibst: "Wenn nötig, kann ich den Januar übernehmen" - deshalb gehe ich davon aus, dass es Dir lieber wäre, wenn jemand anderer den Januar übernimmt. Und ich will klären, ob wir das tun können. Oder hab ich das falsch interpretiert?

**Comment by titanoboa** [comment]
@andywenk ach so! da haben wir uns missverstanden. Bei 'den Januar übernehmen' ging es gar nicht um die Raumfrage, sondern das von @halfbyte erwähnte Organisationskomitee ;-)

**Comment by andywenk** [comment]
@titanoboa ok - sorry. Gut halten wir dann fest, dass sum.cumo im Februar der Host ist? Sorry for confusion ...

**Comment by titanoboa** [comment]
@andywenk wenn Februar für Euch passt, wäre das super und unser Luxusproblem gelöst

**Comment by andywenk** [comment]
@titanoboa so wird's gemacht - cool :dancer:

**Comment by andywenk** [comment]
@titanoboa @halfbyte we are in! sum.cumo stellt die Räumlichkeiten, Drinks, Beamer und Knabberi für Februar ;-)

**Comment by titanoboa** [comment]
Räume haben wir ja dann für Januar und Februar, da müssten @halfbyte @phoet und ich dann noch Streichholz ziehen, wer wann dem Organisationskomitee vorsitzt

**Comment by andywenk** [comment]
ab wann machen wir public, dass wir das im Februar bei uns machen? Wie würden das gerne weitergeben um möglichst viele Gäste zu haben ;-) Ich halte mich da an Eure "Erfahrungen, Wünsche, Regeln"

**Comment by phoet** [comment]
@andywenk lass uns das doch [hier](https://github.com/rughh/planning/issues/21) diskutieren

**Comment by titanoboa** [comment]
@phoet @halfbyte wir sollten mal klären, wer von uns sich um talks kümmert, oder? ich bin wie gesagt nur so halb verfügbar, aber falls ihr noch weniger da seid, kann ich es auch übernehmen

**Comment by titanoboa** [comment]
Werde voraussichtlich Mittwoch nicht da sein können

**Comment by halfbyte** [comment]
Relativ Planungsfailig wieder unterwegs dieses mal. Ich habe da gerade noch einen einzelnen Lead für einen Vortrag. Würde mir sonst eine Gruppenaction ausdenken für heute Abend, habe dazu auch schon ein paar Ideen. @toadle Ihr habt, so als Gastgeber nicht zufällig noch einen Talk in der Hinterhand?

Ich bekomme da irgendwas hin, aber das wird heiss gestrickt!

**Comment by toadle** [comment]
@halfbyte Leider nicht so wirklich. Ich könnte sonst spontan anbieten mal was zu "API-first CMS" zu erzählen. Haben gerade ein Projekt in dem wir das zum ersten mal einsetzen und funktioniert eigentlich echt ganz gut. 
Gibt aber keine Folien. Wir am Code gezeigt :-)!

**Comment by halfbyte** [comment]
@toadle Die andere Idee die ich hatte, war mal ein bisschen was über Rails 5 zu machen, aber eher so als Gruppenaktivität. Ich bereite das mal vor, dann haben wir ein bisschen was.

(Aus interesse: Was verwendet Ihr da? Contentful?)

**Comment by toadle** [comment]
@halfbyte Ja, Contentful. 
Soll ich mich drauf einstellen, da jetzt was zu zu erzählen?

**Comment by halfbyte** [comment]
Ja, gerne, mach mal. Danke!

**Comment by halfbyte** [comment]
Phew.

**Comment by phoet** [comment]
@halfbyte danke fuers graceful handling :+1:
