### ISSUE TITLE
Februar 2016 Meetup

### ISSUE THREAD

**Issue by titanoboa** [rughh/planning#21]
Termin: 10.02.2016 19:00

* [x] Location
* [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
* [x] Promo auf Twitter
* [x] [Push-Notification für iOS app senden](http://hamburg.onruby.de/admin/dashboard)
* [x] [Slides anpassen](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)

**Comment by titanoboa** [comment]
we have a talk proposed by @siniypin http://hamburg.onruby.de/topics/practical-dci-xing and he would like to speak on our February meetup

**Comment by titanoboa** [comment]
wie in #20 mit @andywenk besprochen, könnten wir uns bei sum.cumo treffen

**Comment by andywenk** [comment]
@titanoboa ACK ... sum.cumo geht klar - Danke ;-)

**Comment by phoet** [comment]
@andywenk in der regel kündigen wir die meetups dann an, wenn die rahmenbedingungen einigermaßen klar sind, wir also eine location haben und auch talks in der pipeline sind. mehr als 1 bis 2 wochen vorher halte ich nicht für sinnvoll, da die leute so lange eh nicht planen bzw es wieder vergessen haben bis dahin.

**Comment by andywenk** [comment]
@phoet verstehe. Ok - spricht aber nix dagegen, dass man "darüber spricht" order? ;-)

**Comment by phoet** [comment]
ihr könnt das gerne so kommunizieren wie ihr lustig seid. ich werde nachher schon mal einen termin anlegen, dann habt ihr auch was, dass ihr verlinken könnt.

**Comment by andywenk** [comment]
@phoet großartig - Danke ;-)

**Comment by phoet** [comment]
so, hier ist der link http://hamburg.onruby.de/events/ruby-usergroup-hamburg-februar-2016

**Comment by andywenk** [comment]
Mega! Vielen Dank ;-)

**Comment by titanoboa** [comment]
und @skorfmann hat seinen Australientalk angeboten

**Comment by andywenk** [comment]
super - vielen Dank! Bis morgen ;-)

**Comment by patrickdet** [comment]
Ich bin dabei einen Vortrag über Elm (elm-lang.org) zusammen zu stellen. Eigentlich wollte ich den auf dem HH.js meetup halten, aber wenn hier auch Interesse besteht kann ich den auch zweimal halten. Meine einzige Sorge ist, dass die rughh und hh.js Schnittmenge zu groß ist.

/cc @salzig

**Comment by phoet** [comment]
@patrickdet das thema finde ich super, ich glaube februar ist schon relativ voll. magst du dein thema mal hier eintragen: http://hamburg.onruby.de/topics/new

käme für dich auch ein anderer termin in frage?

**Comment by halfbyte** [comment]
@titanoboa @phoet Nur kurzer Hinweis: Ist ja kaum noch was zu organisieren aber ich bin für den Februar definitiv raus, bin gerade eben so zur UG wieder in Hamburg, das macht also keinen Sinn.

**Comment by andywenk** [comment]
an alle: herzlichen Dank für gestern - das war sehr cool ;-). 

Frage: habt Ihr schonmal was über Refinements gehabt?

**Comment by phoet** [comment]
@andywenk hilfe waere super, ich kann mich im moment nicht auf die orga hier commiten. ich glaube @klaustrainer war auch im gesraech bei der usergroup orga zu helfen?

zum thema refinements hatten wir glaube ich noch nix.

**Comment by titanoboa** [comment]
@phoet @halfbyte den Februar kann ich übernehmen

**Comment by andywenk** [comment]
@titanoboa cool. Sag bescheid, wenn ich was tun soll. Der Raum steht ja fest und ich werde einen talk einreichen. 

Andere Fragen: 

* wie kann man auf der Hamburg On Ruby Seite ein Job-Posting plazieren?
* auf der Hamburg on Ruby Seite gibt es die Sponsoren GitHub, Engine Yard und JetBrains. Gibt es die Möglichkeit dort mit aufzutauchen und wenn ja unter welchen Bedingungen?

**Comment by titanoboa** [comment]
Ok cool, dann ist der gegenwärtige Plan, den DCI-Talk im März zu machen und im Februar einen talk von @andywenk und den Australientalk von @skorfmann

@andywenk kannst Du deinen Talk auf http://hamburg.onruby.de/#topics eintragen? Ein, zwei Sätze genügen vollkommen

Damit ist dann für Februar nicht mehr viel zu tun, über generelle Hilfe bei der Orga können wir uns dann am besten live unterhalten, wir könnten Unterstützung gebrauchen

**Comment by andywenk** [comment]
@titanoboa sehr gerne - trage ich jetzt ein. Ev. kannst Du mir meine anderen Fragen noch beantworten ;-). Für generelle Hilfe bin ich am Start!

**Comment by andywenk** [comment]
http://hamburg.onruby.de/topics/refinements-we-no-need-monkey-s

**Comment by phoet** [comment]
@andywenk ich habe eure job-seite verlinkt.

zum thema sponsoring könnte ich mir vorstellen, dass ihr beispielsweise die laufenden kosten für den betrieb von onruby übernehmen könntet. das sind derzeit 9$/monat bei heroku und knapp 60 EUR/jahr für domains bei domainfactory. stellt sich natürlich immer die frage wie man das konkret verrechnet...

**Comment by andywenk** [comment]
@phoet großartig herzlichen Dank!!!

Sponsoring: das klingt gut - ich werde das mal bei uns besprechen ... Danke!!!
