### ISSUE TITLE
Community Roadshow

### ISSUE THREAD

**Issue by phoet** [rughh/planning#22]
mail von @GregorBiswanger 

> Hallo,
>  
> mein Name ist Gregor und ich bin 2016 wieder mit einer Community Roadshow unterwegs.
> https://software.intel.com/de-de/blogs/2015/11/30/community-roadshow-top-5-javascript-tools-und-best-practices-mit-microsoft-aber
>  
> Nun meine Frage an euch: Habt ihr Interesse, dass ich zur Ruby User Group Hamburg vorbeikomme?
> Ich habe Microsoft angefragt und sie würden Pizza und Bier sponsern J
>  
> Für die Roadshow habe ich einen Teaser, den ihr dann auch gerne für die Ankündigung verwenden dürft:
> https://www.youtube.com/watch?v=_jr_dEDvncI
>  
> Hier ist nochmal eine genauere Beschreibung von meinem Vortrag:
>  
> Community Roadshow: Top 5 JavaScript Tools und Best Practices – mit Microsoft, aber ohne Internet Explorer
>  
> Heutzutage sind eine hohe Anzahl an professionellen und leistungsfähigen JavaScript-Frameworks, -Tools und –Klassenbibliotheken erhältlich. Das zeigt uns, dass die JavaScript Entwicklung immer mehr an Bedeutung gewinnt. Bei diesem Vortrag, stellt Gregor Biswanger seine Top 5 Hilfsmittel vor. Dazu zählt zum Beispiel TypeScript für mehr Kontrolle bei der Entwicklung im Team und der Planung der Architektur, RxJS für eine performante asynchrone Programmierung, Visual Studio Code als Alternative zum Node Inspector, die ein effektiveres Debuggen von NodeJS-Anwendungen ermöglicht und vieles mehr.
>  
> Ganz viele Grüße aus Ingolstadt,
> Gregor

**Comment by phoet** [comment]
> 
> 
> -- 
> Ruby Usergroup Hamburg
> 
> Forwarded message:
> 
> From: Ruby Usergroup Hamburg <onruby@googlemail.com>
> To: Gregor Biswanger <gregor.biswanger@web-enliven.de>
> Date: Monday, 21. December 2015 20:29:00
> Subject: Re: WG: Community Roadshow: Top 5 JavaScript Tools und Best Practices
> 
> super!
> 
> --
> Ruby Usergroup Hamburg
> 
> 
> On Monday, 21. December 2015 at 18:26, Gregor Biswanger wrote:
> 
> Okay, der 13.04.2016 hört sich gut an.
> Dann trag ich das mal so in meinen Kalender ein.
> 
> Ich freu mich schon auf euch.. :)
> 
> -----Ursprüngliche Nachricht-----
> Von: Ruby Usergroup Hamburg [mailto:onruby@googlemail.com]
> Gesendet: Montag, 21. Dezember 2015 17:40
> An: Gregor Biswanger <gregor.biswanger@web-enliven.de (mailto:gregor.biswanger@web-enliven.de)>
> Betreff: Re: WG: Community Roadshow: Top 5 JavaScript Tools und Best Practices
> 
> dann lieber april. das wäre dann der 13.04.
> 
> --
> Ruby Usergroup Hamburg
> 
> 
> On Monday, 21. December 2015 at 12:32, Gregor Biswanger wrote:
> 
> Hi Peter,
> 
> ups, das Stimmt. Am 9. März wäre ich bereits bei einem Termin.
> Könnte man eine ausnahme mit dem 16. März machen? Andernfalls kann ich dann erst im April.
> 
> Beste Grüße,
> Gregor
> 
> 
> -----Ursprüngliche Nachricht-----
> Von: Ruby Usergroup Hamburg [mailto:onruby@googlemail.com]
> Gesendet: Samstag, 19. Dezember 2015 13:53
> An: Gregor Biswanger <gregor.biswanger@web-enliven.de (mailto:gregor.biswanger@web-enliven.de)
> (mailto:gregor.biswanger@web-enliven.de)>
> Cc: hamburg@onruby.de (mailto:hamburg@onruby.de)
> Betreff: Re: WG: Community Roadshow: Top 5 JavaScript Tools und Best
> Practices
> 
> hi gregor,
> 
> das ist aber leider der 3. mittwoch. ist der 9. märz auch möglich?
> 
> schöne grüße
> 
> --
> Ruby Usergroup Hamburg
> 
> 
> On Thursday, 17. December 2015 at 12:20, Gregor Biswanger wrote:
> 
> Hi Peter,
> 
> das freut mich! Dann würde ich mal den 16. März 2016 im Kalender blocken?!
> Danke für dein issue ;)
> 
> Ganz viele Grüße,
> Gregor
> 
> 
> -----Ursprüngliche Nachricht-----
> Von: Ruby Usergroup Hamburg [mailto:onruby@googlemail.com]
> Gesendet: Mittwoch, 16. Dezember 2015 19:24
> An: Gregor Biswanger <gregor.biswanger@web-enliven.de (mailto:gregor.biswanger@web-enliven.de)
> (mailto:gregor.biswanger@web-enliven.de)
> (mailto:gregor.biswanger@web-enliven.de)>
> Cc: hamburg@onruby.de (mailto:hamburg@onruby.de)
> Betreff: Re: WG: Community Roadshow: Top 5 JavaScript Tools und Best
> Practices
> 
> hi gregor,
> 
> ich sage mal so pauschal ja.
> 
> unsere usergroup findet jeden 2. mittwoch im monat statt. januar und februar sind schon verplant.
> 
> da wir unsere planung bei github machen, habe ich dafür mal ein
> issue
> erzeugt: https://github.com/rughh/planning/issues/22
> 
> schöne grüße,
> peter
> 
> --
> Ruby Usergroup Hamburg
> 
> 
> On Wednesday, 16. December 2015 at 17:03, Gregor Biswanger wrote:
> 
> Hallo,
> 
> mein Name ist Gregor und ich bin 2016 wieder mit einer Community Roadshow unterwegs.
> https://software.intel.com/de-de/blogs/2015/11/30/community-roadsh
> ow -t op-5-javascript-tools-und-best-practices-mit-microsoft-aber
> 
> Nun meine Frage an euch: Habt ihr Interesse, dass ich zur Ruby User Group Hamburg vorbeikomme?
> Ich habe Microsoft angefragt und sie würden Pizza und Bier
> sponsern J
> 
> Für die Roadshow habe ich einen Teaser, den ihr dann auch gerne für die Ankündigung verwenden dürft:
> https://www.youtube.com/watch?v=_jr_dEDvncI
> 
> Hier ist nochmal eine genauere Beschreibung von meinem Vortrag:
> 
> Community Roadshow: Top 5 JavaScript Tools und Best Practices –
> mit Microsoft, aber ohne Internet Explorer
> 
> Heutzutage sind eine hohe Anzahl an professionellen und leistungsfähigen JavaScript-Frameworks, -Tools und –Klassenbibliotheken erhältlich. Das zeigt uns, dass die JavaScript Entwicklung immer mehr an Bedeutung gewinnt. Bei diesem Vortrag, stellt Gregor Biswanger seine Top 5 Hilfsmittel vor. Dazu zählt zum Beispiel TypeScript für mehr Kontrolle bei der Entwicklung im Team und der Planung der Architektur, RxJS für eine performante asynchrone Programmierung, Visual Studio Code als Alternative zum Node Inspector, die ein effektiveres Debuggen von NodeJS-Anwendungen ermöglicht und vieles mehr.
> 
> Ganz viele Grüße aus Ingolstadt,
> Gregor
> 
> 
> 
> 
> 
> 
> Gregor Biswanger
> Freier Autor, Dozent, Trainer und Berater Microsoft MVP für
> Windows Platform Development, Intel Black Belt & Intel Software
> Innovator
> 
> about.me/gregor.biswanger (http://about.me/gregor.biswanger)
> www.dotnet-blog.net (http://www.dotnet-blog.net/)
> 
> T +49 174 - 91 91 513
> E gregor.biswanger@web-enliven.de (mailto:gregor.biswanger@web-enliven.de)

**Comment by phoet** [comment]
> Hallo Peter,
> ich hab ein wichtiges Kundenprojekt am 13.04. erhalten.
> Konnte leider keinen alternativen Termin finden.
> Wäre es möglich das wir das Treffen auf den 14.04. verschieben?
> Ganz viele Grüße,
> Gregor

**Comment by phoet** [comment]
> Im Mai dann?

**Comment by GregorBiswanger** [comment]
Ja, ich könnte am 11.05.
Machen wir es fix? :)

**Comment by titanoboa** [comment]
Ja, lass uns den 11.5. festmachen

**Comment by titanoboa** [comment]
@GregorBiswanger magst Du ein oder zwei Sätze Ankündigung unter http://hamburg.onruby.de/#topics eintragen?

**Comment by GregorBiswanger** [comment]
Erledigt! :)

**Comment by titanoboa** [comment]
http://hamburg.onruby.de/events/ruby-usergroup-hamburg-mai-2016
#28

**Comment by GregorBiswanger** [comment]
Hi, hab gesehen das du für den 13.5. den Termin veröffentlicht hast.. Ich hatte jetzt wie besprochen den 11.5. eingeplant... am 13.5. müsste ich bereits in Köln sein und könnte nur, wenn es gar nicht anders geht..

**Comment by phoet** [comment]
ich gehe mal davon aus, dass es sich um ein versehen handelt

**Comment by titanoboa** [comment]
Ja, das war ein Tippfehler, wir treffen uns wie immer mittwochs, sprich wie abgemacht am 11.5.
