### ISSUE TITLE
DevCamp

### ISSUE THREAD

**Issue by phoet** [rughh/planning#23]
anfrage von "Firyn, Jaqueline" <firyn@young-targets.de>

> Liebe Ruby User Group Hamburg,
> 
> ich habe Euch gerade auf http://hamburg.onruby.de/ entdeckt. Wir veranstalten Ende Januar das erste DevCamp in Hamburg​ (http://www.campus-devcamp.de/)​ und würden sehr gerne auch das Thema "Ruby" etwas fokussieren. Ich kann mir​ gut​ vorstellen, dass einige der Teilnehmer eine Session dazu ​spannend finden würden.
> 
> Das DevCamp ist eine Un-Konferenz für Coder & Developer, d.h. die Teilnehmer gestalten ihre Konferenz durch Beiträge (zu Technologien, Programmiersprachen, Methoden, neuen Entwicklungen) selbst, wobei spannende Diskussionen und selbst organisierte Arbeitsgruppen spontan entstehen können. Habt ihr Lust dabei zu sein und evtl. ​eine Session zu halten? Das Format könnt ihr frei wählen: ​45min - z.​B.​ als Vortrag, Gesprächsrunde oder Mini-Workshop. Falls nicht, freuen wir uns natürlich trotzdem, wenn ihr teil nehmt. 
> 
> Wir würden uns auch sehr freuen, wenn ihr die Infos weiter gebt. Vielleicht hat ja der ein oder andere aus eurer Gruppe Lust dabei zu sein. Einen Flyer findet ihr anbei.
> 
> Die Teilnahme ist kostenfrei, da wir die Kosten ​durch Förderbeiträge von Otto, Sabio​, InnoGames, AboutYou, top itservices und​ FH Wedel decken konnten.
> 
> Bei Fragen ruft mich gerne einfach an.
> 
> Viele Grüße

**Comment by phoet** [comment]
> Hallo Peter,
> 
> ein frohes neues Jahr wünsche ich dir! :) 
> 
> Bald steht das DevCamp am 30./31.01. im Werkheim statt. Habt ihr noch Lust dabei zu sein?
> 
> Wir nehmen euch auch gerne als Partner mit auf unserer Website. Ich freue mich über eine Rückmeldung.
> 
> Lieben Gruß
> 
> Jaqueline

**Comment by phoet** [comment]
hat da jemand ne meinung zu?

/cc @rughh/owners

**Comment by titanoboa** [comment]
Dagegen

On January 20, 2016 6:08:08 PM GMT+01:00, "Peter Schröder" <notifications@github.com> wrote:
>hat da jemand ne meinung zu?
>
>/cc @rughh/owners 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/rughh/planning/issues/23#issuecomment-173276248

-- 
Sent from my mobile phone

**Comment by nesQuick** [comment]
Ich persönlich habe kein Interesse. Ist doch auch "nur" headhunting. Und hier im Thread ist es ja auch schon weiter gegeben :)
