### ISSUE TITLE
März 2016 Meetup

### ISSUE THREAD

**Issue by phoet** [rughh/planning#24]
Termin: 09.03.2016 19:00

* [x] Location
* [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
* [x] Promo auf Twitter
* [x] [Push-Notification für iOS app senden](http://hamburg.onruby.de/admin/dashboard)
* [x] [Slides anpassen](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)

**Comment by titanoboa** [comment]
we have a talk proposed by @siniypin http://hamburg.onruby.de/topics/practical-dci-xing and he would like to speak on our March meetup

**Comment by exterm** [comment]
Hey, I would like to propose our nice office in the Schanze as a location. We will have pizza, beer, a projector and chairs. (Avocado Store)

**Comment by phoet** [comment]
@exterm thanks for the heads up, we will come back to you when the date is aproaching!

**Comment by phoet** [comment]
@exterm i updated the march meetup to be at avocado store, is that alright? @siniypin i added your talk to that event, are you fine with that?

**Comment by phoet** [comment]
@skorfmann IIRC you could not give your talk the last time, do you want to do it in march?

**Comment by exterm** [comment]
:+1:

**Comment by siniypin** [comment]
@titanoboa, @phoet  Affirmative, I'll deliver a talk as I advertised

**Comment by siniypin** [comment]
@exterm Hey Philip, do you have sound system in your office? I'd like to play back a couple of files during the speech.

**Comment by exterm** [comment]
@siniypin not really. I can bring a small Speaker with a 3.5 mm Stereo Plug however that will have more power than the laptop speakers. ( https://www.cambridgeaudio.com/products/wireless-speakers/go-radio ) Will that be enough?

Otherwise I can try to organize something bigger.

**Comment by siniypin** [comment]
@exterm I think that speaker will do, thanks!
