### ISSUE TITLE
April 2016 Meetup

### ISSUE THREAD

**Issue by phoet** [rughh/planning#25]
Termin: 13.04.2016 19:00

* [x] Location
* [x] [Event anlegen](http://hamburg.onruby.de/admin/)
* [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
* [x] Promo auf Twitter
* [x] [Push-Notification für iOS app senden](http://hamburg.onruby.de/admin/dashboard)
* [x] [Slides anpassen](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)

**Comment by phoet** [comment]
für diesen termin planen wir die [roadshow](https://github.com/rughh/planning/issues/22) mit ein

**Comment by bnerd** [comment]
Zwecks Location: Wir könnten das April Meetup gerne bei uns im Office (Brandslisten GmbH) hosten. Verena hatte das bereits angeboten. Wir sind vor einiger Zeit von der Großen Elbstraße in die Banhöfe Altona umgezogen. Ein wenig Sorge bereitet mir nur der Platz, da unser Konferenz Raum in etwa Platz für 10-15 Personen bietet. Allerdings ist bspw. unser Flur recht lang. Müssten wir etwas mehr in die Tiefe als in die Breite bestuhlen. Das würden wir schon hinbekommen! Mit wie vielen Personen rechnet ihr im Schnitt?

**Comment by phoet** [comment]
@bnerd im schnitt melden sich 20 personen an, wir können aber auch die anzahl limitieren falls das wirklich sehr eng werden sollte.

**Comment by bnerd** [comment]
@phoet - 20 Personen sind kein Problem. Um sicher zu gehen, würde ich auf 30 - 35 Personen limitieren. Bier trinken geht auch mit mehreren; aber für die Vorträge wird es sonst etwas zu kuschelig.

**Comment by phoet** [comment]
@bnerd alles klar, dann machen wir das so und halten das brandslisten office schon mal fest

**Comment by phoet** [comment]
[roadshow](https://github.com/rughh/planning/issues/22) is of for now

**Comment by phoet** [comment]
@skorfmann @handylearn @attackemartin any takers for talks?

**Comment by phoet** [comment]
@bnerd anything that you or your coworkers want to add in terms of talks?

**Comment by andywenk** [comment]
hijacking ... @phoet - wir würden geren das Mai Meetup bei uns wieder machen. Ist es zu früh schon ein Planungs-Issue aufzumachen

**Comment by handylearn** [comment]
Zu meinem Vortrag: Ich bin noch nicht ganz sicher, ob ich alles schaffe was ich mir zum Thema vorgenommen habe. Ich wollte zeigen, wie man mit Hilfe einer Webapp von Excel auf Rails zuzugreifen kann. Ich melde mich nach Ostern dazu nochmal.

**Comment by phoet** [comment]
@tobstarr would you like to give your kubernetes talk in april?

**Comment by tobstarr** [comment]
@phoet works for me

**Comment by phoet** [comment]
there might be another talk from brandslisten

> Moin, ich arbeite bei brandslisten und würde gerne am kommenden Mittwoch einen kurzen Vortrag über Crystal halten. Wäre das ok?
>
 >Gruß
> Lasse

**Comment by phoet** [comment]
plus there might be somebody talking about [refugees on rails](http://refugeesonrails.org/de/)
