### ISSUE TITLE
hacken.in Hamburg

### ISSUE THREAD

**Issue by titanoboa** [rughh/planning#26]
Hacken.in ist ein Eventkalender für usergroups und andere lokale community events rund um Technikkram: 

https://hacken.in

Es ist also inhaltlich und geografisch fokussierter als meetup.com. Nicht-kommerziell, kostenlos etc.

Vielleicht hat Eure usergroup auch Interesse, dort zu erscheinen?

Wie bei der letzten ruby usergroup mit einigen besprochen, habe ich Kontakt zu den hacken.in Leuten aufgenommen. Das hier ist der Versuch, auch Hamburger Events dorthinzubringen, so dass wir auch für Hamburg einen zentralen Kalender haben und uns nicht durch meetup, onruby, xing und zig andere Seiten klicken müssen, um zu wissen was wann los ist.

Jede Gruppe kann für sich entscheiden, wie sie das nutzen möchte. Generell kann hacken.in auch die Orte der einzelnen Treffen anzeigen, RSVP handhaben etc. Es ist jedoch genausogut möglich, dies auf den bisher genutzen Wegen zu tun (also meetup.com, onruby etc wie gehabt zu verwenden) und bei hacken.in lediglich den Termin und einen link auf die eigene Webseite abzukippen. 

Beispiel: die ruby usergroup könnte z.B. bei hacken.in einen wiederkehrenden Termin für den zweiten Mittwoch des Monats eintragen, in dem nur steht 'Ort und Themen findet ihr auf hamburg.onruby.eu'. Der Aufwand ist minimal - einmal eintragen und ggf. noch ab und an Sonderlocken wie Extra-Termine nachpflegen. Trotzdem halte ich das (sofern mehrere Gruppen mitmachen) für nützlich, da wir eine zentrale Terminübersicht bekommen.

Das ganze ist natürlich nicht auf usergroups im engeren Sinne beschränkt. Auch ein nicht-kommerzieller Hackathon, Cryptoparty oder dergleichen können hier ihren Platz finden - es sollte halt thematisch nicht zu sehr ausufern, die Yogagruppe gehört eher nicht hierher.

Die hacken.in Leute freuen sich, wenn wir mitmachen. Als ersten Schritt würde ich erstmal sammeln, wer so Interesse hätte und das kommunizieren. Wenn Ihr gleich Nägel mit Köpfen machen möchtet, könnt Ihr auch einfach einen account auf hacken.in anlegen und mir den account mitteilen (und welche Gruppe ihr eintragen möchtet), dann kümmere ich mich drum, dass die diese accounts für das Eintragen von Terminen freigeschaltet werden. Wenn ein paar Termine eingetragen sind, kann dann der Hamburg Kalender auf öffentlich sichtbar gestellt werden.

Ich pinge jetzt in diesem issue mal die Leute an, die mir so in den Sinn gekommen sind. Wenn Ihr Kontakt zu weiteren usergroups / interessierten Menschen habt, holt sie gern in diese Diskussion. Wenn der Kalender dann an den Start geht, können wir natürlich auch die Gruppen einladen, in denen wir niemanden direkt kennen.

Wer hat Interesse, was haltet Ihr davon?

* @halfbyte @phoet (ruby?)
* @nesQuick (php?)
* @JanAhrens (api?)
* @stefanmunz (cocoaheads?)
* @KlausTrainer (couchdb?)

**Comment by phoet** [comment]
wenn ich mich recht entsinne, dann gibt es für onruby schon eine integration durchs rss feed von @bitboxer https://github.com/phoet/on_ruby/pull/125

**Comment by titanoboa** [comment]
@phoet cool :+1: hatte ich noch gar nicht gesehen

wenn ich das richtig sehe erscheinen aber dennoch die Hamburger Termine derzeit nirgends, weil es ja generell keine 'Hamburg' Sektion auf hacken.in gibt

**Comment by nesQuick** [comment]
php -> @icewolfs

**Comment by moonglum** [comment]
Wenn ihr irgendwelche Hilfe braucht, einfach anpingen :smile:

**Comment by frank-sons** [comment]
statt @icewolfs geht auch dieser account :-) Für die PHP Usergroup gerne mich ansprechen, ansonsten ein Hinweis: für digitiale Initiativen (dies beinhaltet Usergroups), gibt es in Hamburg bereits ein Netzwerk: http://www.digital-mesh.de/de/ bzw. https://www.xing.com/communities/groups/digital-mesh-hamburg-8a81-1004614

Ein Kalender ist da bereits auch in Arbeit und es findet ein regelmäßiger Stammtisch und Austausch statt. Interessierte Organisatoren sind da jederzeit willkommen und ich stelle gerne den Kontakt her.

**Comment by KlausTrainer** [comment]
Moin. Ja, ich würde die Termine für das CouchDB Meetup in Hamburg gerne da eintragen. Ich bin mit meinem GitHub-Account (@KlausTrainer) angemeldet, welcher gerne für das Termin-Eintragen freigeschaltet werden darf ;)

**Comment by JanAhrens** [comment]
Super Initiative! Ich möchte die nächsten [WebAPI Hamburg](http://www.meetup.com/de-DE/webapi-hamburg/) Treffen ebenfalls auf hacken.in ankündigen. Ich hab ebenfalls mit meinem GitHub Account angemeldet (die Nägel-mit-Köpfen-Variante).

Kann mich jemand (vielleicht @titanoboa) bitte freischalten?

**Comment by titanoboa** [comment]
https://hacken.in/hamburg existiert nun, wird dann später auf der Startseite verlinkt, wenn wir ein paar Termine beisammen haben

**Comment by KlausTrainer** [comment]
Moin @moonglum! Ich würde gerne Termine für das CouchDB Meetup in Hamburg eintragen. Ich bin mit meinem GitHub-Account (@KlausTrainer) angemeldet ;)

**Comment by titanoboa** [comment]
du bist schon freigeschaltet @KlausTrainer, genau wie @JanAhrens geht mal auf https://hacken.in/admin/events

**Comment by KlausTrainer** [comment]
Ah, cool! Danke :)

**Comment by moonglum** [comment]
Also bei Hacken.in gibt es drei verschiedene Rollen im Backend:

1. Admin: Dürfen alles :wink: 
2. Regionsadmins: Dürfen in einer Region (zB. Hamburg) alle Events verwalten, neue anlegen usw.
3. Kuratoren: Dürfen ein (oder mehrere) Events (zB. Ruby UG Hamburg) verwalten

Ich habe nun drei Regionsadmins für Hamburg zugewiesen :smile: Wenn ihr Kuratoren möchtet, sagt mir Bescheid. Aktuell könnt ihr Regionsadmins die nicht anlegen, aber werden wir einbauen (https://github.com/hacken-in/website/issues/611) :smile:

**Comment by KlausTrainer** [comment]
Erstmal danke, @moonglum :)

Das einzige was beim CouchDB Meetup noch fehlt ist ein Logo. Ich würde gerne das selbe verwenden wie für unseren [Twitter Account](https://twitter.com/HamburgCouchDB) (also das [hier](https://pbs.twimg.com/profile_images/655793986888683522/XAykxY5F.png)). Ich kann zwar vorhandene Bilder auswählen, habe aber keine Möglichkeit gefunden ein neues Bild hochzuladen.

**Comment by moonglum** [comment]
@KlausTrainer In der Top Bar gibt es für dich nicht die Option Bilder/Pictures? Dann ist das noch ein Bug :wink:

**Comment by nesQuick** [comment]
Ich würde hh.ex dort auch eintragen :)

2016-02-05 23:49 GMT+01:00 Lucas Dohmen <notifications@github.com>:

**Comment by titanoboa** [comment]
@moonglum ich fände es gut wenn der @nesQuick auch Regioadmin und nicht nur Kurator wird, der ist doch eh hier in Hamburg in mehreren Gruppen unterwegs (keine Angst, ich will jetzt nicht noch zehn weitere RegioAdmins einrichten)

**Comment by moonglum** [comment]
Klar, von mir aus gerne :smile: @nesQuick hast du einen Hacken.in Account? Wenn ja, welchen Namen hast du dort?

**Comment by nesQuick** [comment]
Jetzt ja. Hab meinen GitHub Account verlinkt. Also Account: nesQuick

**Comment by KlausTrainer** [comment]
@moonglum Habe gerade nochmal wegen der Bilder-Option geschaut, aber die fehlt bei mir noch.

**Comment by moonglum** [comment]
-> https://github.com/hacken-in/website/issues/612

**Comment by moonglum** [comment]
Hey :smile: Wie ist der Status bei hacken.in/hamburg? Wir haben gerade unseren Umzug auf einen neuen Hoster hinter uns gebracht :smile: Fehlt euch noch irgendwas von der Implementierungsseite? Braucht ihr hacken-in/website#611 und hacken-in/website#612 zum Launch?

**Comment by KlausTrainer** [comment]
Moin! Von meiner Seite sehe ich keine Blocker für nen Launch :)

https://github.com/hacken-in/website/issues/612 habe ich gerade für das CouchDB-Meetup getestet, und hat prima funktioniert :)

Vielen Dank!

**Comment by nesQuick** [comment]
HH.ex fehlt. Würde das gern auch dort vertreten sehen. Aber das ist natürlich kein Launch Blocker.

**Comment by moonglum** [comment]
@KlausTrainer Super, freut mich sehr :smile: 
@nesQuick: Ich kann dir gerne die HH.ex erstellen und dich zum Kurator machen :smile: Hast du schon einen Account bei Hacken.in?
@titanoboa: Was denkst du? Soll ich euch freischalten? :)

**Comment by titanoboa** [comment]
Von der Implementierungsseite her sehe ich keine Blocker. Es wäre sicher praktisch, wenn wir selber Kuratoren anlegen könnten, aber ein Blocker ist es nicht.

Der Kalender ist halt noch recht dünn was Termine angeht, aber vielleicht wird es auch einfacher Leute zu motivieren, ihr meetup einzutragen, wenn es dann wirklich live ist. Von daher würde ich sagen: schalte uns ruhig frei.

**Comment by moonglum** [comment]
Freut mich sehr!

Ok, dann mache ich das mal bereit :smile: Wenn es live ist sage ich euch Bescheid :smile: Das mit den Kuratoren versuche ich irgendwann zwischen zu schieben!

**Comment by nesQuick** [comment]
@moonglum wir drehen uns im kreis: https://github.com/rughh/planning/issues/26#issuecomment-180738410 -> https://github.com/rughh/planning/issues/26#issuecomment-180739053 :D

**Comment by moonglum** [comment]
@nesQuick Entschuldige :blush: Habe dich nun wie oben besprochen zum Regionsadmin Hamburg gemacht, dann kannst du HH.ex selber anlegen :smile:

**Comment by nesQuick** [comment]
@moonglum no worries! :) Ich trag dann mal hh.ex ein die tage :tada:

**Comment by nesQuick** [comment]
@moonglum jetzt auch mit hh.ex :+1:

**Comment by moonglum** [comment]
Yay :tada:

**Comment by handylearn** [comment]
@titanoboa meinte ja, die Yogagruppe gehört da nicht her. Vielleicht ist es etwas voreilig, unter den Software-Prozess-Gurus von [ACM ](http://learning.acm.org/) wird gerade YOGA [diskutiert](http://event.on24.com/wcc/r/1155985/486853632F1F828E87AD631548733301).

> YOGA* is a software development process based on ancient principles and derived from many years of experience with software production and introspective research into and measurement of software production. I thank the guru Fapsan Rat for his many hours of discussion and joint meditation with me concerning these principles.
> 
> YOGA stands for _You Only Go Ahead_ and its theme is to be forward looking. It consists of 10 basic commandments such as:
> 
>  * Ignore the past and only look ahead. Don’t worry about repeating past mistakes.
>      
>  * Don’t try to be rational. There is substantial evidence that there’s no such thing as a rational software production process. Think of yourselves as artists, free to create.
>      
>  * Each team member should meditate on his/her code for an hour every day. The purpose of the meditation is to become more enlightened about the code and coding. The goal should be to find a place in the code that the team member can modify today.
>      
>  * Strengthen your core. Your core developers are the ones who make 80% of the changes. Give them coding exercises to do and hold an occasional refactoring contest to see who can refactor fastest.
> 

Besonders überzeugend finde ich die Bemerkung "There is substantial evidence that there’s no such thing as a rational software production process."

**Comment by moonglum** [comment]
So, Hamburg ist jetzt live :smile: 

https://twitter.com/hacken_in/status/715920394021126144

**Comment by titanoboa** [comment]
:tada:
