### ISSUE TITLE
Possible Talk 

### ISSUE THREAD

**Issue by sebs** [rughh/planning#27]
Refactoring node.js microservices with the "12 factor app" methods

It's been a recurring case in the last 2 years: Customers, who did develop a prototype in node.js, found out their ideas worked and people really used these. With the usage, the problems came. How do we scale it? How do we do releases? Where does it run? Who does config? 

Its the nature of prototype projects on the one hand, to be not perfect in all areas, but to work for a narrowly defined case. On the other hand, being a good citizen in the node.js world is not expensive and does not take long. For something you call a microservice: building, deploying and running it are main concerns as well as the codebase. If all that is messy, the codebase it self is maybe even not your primary concern. 

These are IRL projects, IRL examples of 2 IRL projects.

**Comment by phoet** [comment]
would our april meeting #25 be interesting for you?

**Comment by sebs** [comment]
yes

**Comment by titanoboa** [comment]
Great! Could you add the talk description to http://hamburg.onruby.de/#topics ?
