### ISSUE TITLE
Mai 2016 Meetup

### ISSUE THREAD

**Issue by phoet** [rughh/planning#28]
Termin: 11.05.2016 19:00

* [x] Location
* [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
* [x] Promo auf Twitter
* [x] [Push-Notification für iOS app senden](http://hamburg.onruby.de/admin/dashboard)
* [x] [Slides anpassen](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)

**Comment by phoet** [comment]
@andywank i think this is fine, AFAIK we don't have anybody hosting the may meetup yet.

cross linking https://github.com/rughh/planning/issues/25#issuecomment-199813769

**Comment by phoet** [comment]
i won't be there in may and june due to maternaty leave, so i'm not going to organize this one

**Comment by andywenk** [comment]
So Location is sum.cumo GmbH Borsteler Bogen 27b 22453 Hamburg 

Thanks @phoet ;-)

**Comment by titanoboa** [comment]
@phoet wie waere es wenn du den April machst, und ich übernehme den Mai?

**Comment by phoet** [comment]
geht klar

**Comment by titanoboa** [comment]
als talk ist die community roadshow #22 eingeplant

**Comment by titanoboa** [comment]
@GregorBiswanger meistens haben wir talks, die so ca. eine halbe Stunde sind - passt das ungefähr für Deinen talk, oder was hast Du so grob angepeilt?

Ausserdem hab ich irgendwo in Deinen mails was gelesen von Pizza Sponsoring durch microsoft oder so - falls das noch steht, schlage ich vor Du sprichst das am besten kurz mit @andywenk direkt ab, der ist unser Gastgeber an dem Abend und weiss sicher besser als ich, wo man da was bestellen kann etc.

**Comment by titanoboa** [comment]
neben der roadshow machen wir auch den docker talk

**Comment by andywenk** [comment]
* Getränke sind bestellt
* wie ist das mit Pizza - will da jemand was organisieren? Platz ist genug 
* Nach der allgemeinen Einführung möchte ich als Host kurz zwei Slides zeigen - dauert drei Minuten

Freuen uns auf Euch ;-)

**Comment by titanoboa** [comment]
@GregorBiswanger @ginkel wenn Ihr uns links auf Eure Folien gebt, stelle ich die gern auf unsere Webseite

**Comment by ginkel** [comment]
@titanoboa Gerne: https://www.tgbyte.de/talks/docker-rughh/
