### ISSUE TITLE
Juni Meetup 2016

### ISSUE THREAD

**Issue by phoet** [rughh/planning#29]
Termin: 8.06.2016 19:00

* [x] Location
* [x] [Event anlegen](http://hamburg.onruby.de/admin/)
* [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
* [x] Promo auf Twitter
* [x] [Push-Notification für iOS app senden](http://hamburg.onruby.de/admin/dashboard)
* [x] [Slides anpassen](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)

**Comment by phoet** [comment]
@jensblond offered to host it at WLW

**Comment by titanoboa** [comment]
Wir sind bei WLW und haben den Headhunter from Hell talk - gibt also noch Platz für einen weiteren Talk

**Comment by titanoboa** [comment]
wir haben noch eine kurze Vorstellung des Projektes refugees on rails

**Comment by titanoboa** [comment]
ich setz mir mal freiwillig den hut auf für diesen monat

**Comment by titanoboa** [comment]
Termin: 13.07.2016 19:00

* [ ] Location
* [ ] [Event anlegen](http://hamburg.onruby.de/admin/)
* [ ] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
* [ ] Promo auf Twitter
* [ ] [Push-Notification für iOS app senden](http://hamburg.onruby.de/admin/dashboard)
* [ ] [Slides anpassen](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)
