### ISSUE TITLE
2015 meetup Januar

### ISSUE THREAD

**Issue by phoet** [rughh/planning#3]
wenn ich mich richtig erinnere, dann wollte @halfbyte das januar treffen organisieren?

damit wir es nicht vergessen, hier der link zur ideensammlung die @titanoboa netter weise ins wiki gestellt hat: https://github.com/rughh/planning/wiki/Ideensammlung

**Comment by halfbyte** [comment]
Raumfrage hab ich noch mal mit @nesQuick abgeklärt. 

Bleibt die Frage, ob wir zu Sprachen was hinbekommen jetzt (Ist sicher so dick, dass man das auch auf zwei Treffen machen kann) Ich frage noch mal ein bisschen rum. 

@skade würde auch gerne auf Februar schieben. (via twittäh)

**Comment by halfbyte** [comment]
@tammofreese macht Swift am Mittwoch. Talk Count: 1 :)

**Comment by halfbyte** [comment]
Treffen auf onruby angelegt.

**Comment by phoet** [comment]
gestern auf dem döner.js treffen wurde mir noch der @usefulthink ans herz gelegt. wenn ich mich nit irre dan war das was mit hardware?

**Comment by phoet** [comment]
@halfbyte ich würde gerne für die events ein google slide oder so machen, damit wir da schon mal speaker namen, talk titel, ankündigungen etc eintragen können. wie findeste dis?

**Comment by usefulthink** [comment]
@phoet korrekt, hier als vorgeschmack die slides von dem #hhjs-talk: https://speakerdeck.com/usefulthink/node-rpi-ws281x. Dürfte eine eher kurzweilige Geschichte werden.

**Comment by halfbyte** [comment]
@phoet Gerne: Machen :)

@usefulthink Und das krichste hin am nächsten Mittwoch? Ich überlege, ob ich da dann im Anschluss mein Arduino + IKEA Dioder-Kram zeige, da ist dann wenigstens ein bisschen ruby dabei :)

Klingt auf jeden Fall sehr gut.

**Comment by usefulthink** [comment]
@halfbyte ja, kein problem. Der Code ist JS-mäßig fertig, würde dann am WE noch schnell eine ruby-extension dafür bauen (ich komm dann natürlich auch nicht ganz ohne ruby-code und nach dem was ich gesehen hab sind native-extensions auch bei ruby nicht wirklich hexenwerk) und die slides überarbeiten.

**Comment by phoet** [comment]
@usefulthink wir kommen sonst auch gut mit js klar, aber native-extension ist immer zeigenswert. macht man (ich) nicht alle tage

**Comment by phoet** [comment]
ich hab mit den [slides schon mal angefangen](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)

**Comment by halfbyte** [comment]
@usefulthink Magst Du das ganze mal hier eintragen: http://hamburg.onruby.de/topics/new?

Dann kann ich das in das Treffen übernehmen.

**Comment by phoet** [comment]
@usefulthink können wir eigentlich für heute abend mit dir rechnen? kannst du dich einmal [auf onruby.de per github anmelden](http://hamburg.onruby.de/auth/login/github), damit wir deinen talk mit eintragen können?

ich hab diese beschreibung mal von der hh.js geklaut

> Martin Schuhfuss: rpi-ws281x
>
> This is one of my current fun-projects – involving a raspberry-pi, hardware-hacking, nodejs-addons and other fun-stuff to play with. Will cover lots of interesting topics from electronics to building live-coding environments. In about 20minutes. Phew.

**Comment by usefulthink** [comment]
@phoet könnt ihr. Hab mir die nacht um die Ohren geschlagen und die slides nochmal restauriert und überarbeitet und hab das ganze zeug dabei. Bin da eingelogt, was muss ich da machen?

**Comment by phoet** [comment]
@usefulthink hab ich für dich eingetragen, brauchste jetzt nichts mehr machen. vielen dank für die investierte zeit!

![screen shot 2015-01-14 at 11 05 19](https://cloud.githubusercontent.com/assets/48745/5737082/57610920-9bdd-11e4-8a59-a778921d62ea.png)

**Comment by usefulthink** [comment]
perfekt, danke!
