### ISSUE TITLE
Talk Proposal: Docker for Ruby Developers

### ISSUE THREAD

**Issue by ginkel** [rughh/planning#32]
During yesterday's meetup I had the impression that some attendants would have been quite happy about some general Docker intro before the Kubernetes talk. ;-) I could imaging preparing a talk about "Docker for Ruby Developers" (and maybe also briefly touch the topic of how to use Docker in production without a full-blown Kubernetes stack).

Do you think that would be a good fit for RUGHH?

**Comment by phoet** [comment]
@ginkel we already [had such a talk](http://hamburg.onruby.de/topics/getting-started-with-docker). nevertheless i think it is a good idea since the docker topic is getting so much attention. would you be interested in doing this?

**Comment by ginkel** [comment]
If you think there is sufficient demand, I'd love to. (sorry for the delayed reply :-/)

**Comment by phoet** [comment]
yes please!

**Comment by ginkel** [comment]
Allright, I created a talk proposal at http://hamburg.onruby.de/topics/docker-nicht-nur-fur-ruby-entwickler. ;-)

**Comment by phoet** [comment]
😽 thx

**Comment by titanoboa** [comment]
When are you available to give this talk? Next meetups are May 11th and June 8th

**Comment by ginkel** [comment]
@titanoboa I won't be around in June, but next week should work.

**Comment by titanoboa** [comment]
Great! http://hamburg.onruby.de/events/ruby-usergroup-hamburg-mai-2016

When preparing your talk, please keep in mind that we also have another talk that evening, so the talks should not b too long. Usually something like 30 minutes is a good length, but of course this is not a hard limit
