### ISSUE TITLE
Vortrag aus Gründer Sicht

### ISSUE THREAD

**Issue by phoet** [rughh/planning#34]
> On Saturday, 28. May 2016 at 07:35, Pierre Kerchner (sofanet) wrote:
> 
> Hi
> 
> wäre evtl. auch ein Vortrag aus Gründer Sicht (der selbst kein Ruby kann) interessant ?
> 
> - Erfahrungen mit Entwicklern
> - Erfahrungen mit den anderen Disziplinen (Design, Werbung, ...)
> - Erfahrungen mit Wachstum und Nicht-Wachstum
> - Marketing von Anwendung / Apps
> - Vision / Geschichte einer Anwendung
> 
> pierre

"Pierre Kerchner (sofanet)" <pkerchner@sofanet.de>

@titanoboa willst du ihn mal anschreiben bezüglich der nächsten usergroup?

**Comment by titanoboa** [comment]
wir haben schon zwei beiträge im juni, ich denke das reicht eigentlich
