### ISSUE TITLE
Talk: pattern libraries

### ISSUE THREAD

**Issue by titanoboa** [rughh/planning#36]
talk offer from @weidenfreak about pattern libraries

description: tba
date: tba
language: tba

**Comment by phoet** [comment]
@weidenfreak hast du lust den beim nächsten mal zu halten?

**Comment by weidenfreak** [comment]
Lust ja, leider bin ich Mittwochs normalerweise nicht in HH...

**Comment by titanoboa** [comment]
@weidenfreak wie sieht es denn so mit dem 12.10. aus? Oder bist Du immer noch auswärts?

**Comment by weidenfreak** [comment]
Leider bin ich in der Woche wieder nicht in HH.

Am 29.09.2016 5:50 nachm. schrieb "titanoboa" <notifications@github.com>:

**Comment by phoet** [comment]
@weidenfreak hast du noch lust auf den vortrag?

**Comment by weidenfreak** [comment]
Weiß nicht ob das noch klappt, bin seit dem nicht mehr in Hamburg gewesen an einem Usergroup Mittwoch :/

**Comment by phoet** [comment]
@weidenfreak ok danke, dann mache ich das erst mal zu. sag bescheid wenn du doch irgendwann noch zeit und lust hast!

**Comment by weidenfreak** [comment]
Jo, ok!
