### ISSUE TITLE
Juli Meetup

### ISSUE THREAD

**Issue by titanoboa** [rughh/planning#37]
Termin: 13.07.2016 19:00

* [x] Location
* [x] [Event anlegen](http://hamburg.onruby.de/admin/)
* [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
* [x] Promo auf Twitter
* [x] [Push-Notification für iOS app senden](http://hamburg.onruby.de/admin/dashboard)
* [x] [Slides anpassen](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)

**Comment by titanoboa** [comment]
Als Vortrag haben wir bisher #35

**Comment by KlausTrainer** [comment]
Ich kann einen Lightning Talk (max. 5 Minuten) anbieten: _End-to-End Arguments in System Design_

**Comment by KlausTrainer** [comment]
…und falls noch eine Location benötigt wird, kann ich das Meetup gerne bei Ubilabs hosten ;)

**Comment by titanoboa** [comment]
@KlausTrainer super, wir kommen gern zu Euch :-) 

auch den lightning talk nehmen wir gern

**Comment by KlausTrainer** [comment]
@titanoboa Alles klar. Dann lass uns das so machen :)

**Comment by titanoboa** [comment]
* lightning talks von @halfbyte  und @toadle eingeplant, Themen tba
* @ginkel @LAndreas überlegen noch (ggf. nochmal nachfragen)

**Comment by LAndreas** [comment]
@titanoboa ich könnte einen Lightning Talk (5 bis 10 Minuten) über _system call interception_ machen. Wahrscheinlich keine Folien, nur Code (Go & Ruby).

**Comment by titanoboa** [comment]
@LAndreas cool, trag ich ein. Gern auf deutsch.

**Comment by andywenk** [comment]
Ich werd es nicht schaffen einen talk vorzubereiten. Sry. ...

**Comment by jensblond** [comment]
Bin dieses Mal raus. Der Zoll will an dem Tag unsere Brauerei begutachten 🤔

**Comment by titanoboa** [comment]
@toadle cool, habs gleich auf onruby vermerkt

**Comment by titanoboa** [comment]
@andywenk @jensblond wir machen das womöglich noch öfter, ihr seid dann einfach beim nächsten mal dran ;-)

**Comment by ginkel** [comment]
@titanoboa Ich schaff's morgen leider auch nit mit einem Talk, mit etwas mehr Vorlauf aber gerne. ;-)

**Comment by halfbyte** [comment]
@titanoboa Ich hätte dann auch einen Titel für Dich: "How do you keep your dependencies up to date?"

**Comment by andywenk** [comment]
@titanoboa sehr gerne ;-)
