### ISSUE TITLE
August Meetup - Hosting of RUGHH at XING

### ISSUE THREAD

**Issue by uygars** [rughh/planning#38]
Hi, 

we can offer to host the next meetup on 10th of August in our office at XING AG.

Cheers,

Uygar

**Comment by phoet** [comment]
@uygars thx that's great! do you know if any of you peers is also willing to give a talk there?

**Comment by uygars** [comment]
yes, my colleague @jgroeneveld will give an exciting talk...

**Comment by jgroeneveld** [comment]
this one: http://hamburg.onruby.de/topics/errors-as-return-values :) working on the details

**Comment by phoet** [comment]
@jgroeneveld could you add some details to the description, that would be awesome

**Comment by phoet** [comment]
Termin: 10.08.2016 19:00

* [x] Location
* [x] [Event anlegen](http://hamburg.onruby.de/admin/)
* [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
* [x] Promo auf Twitter
* [x] [Push-Notification für iOS app senden](http://hamburg.onruby.de/admin/dashboard)
* [x] [Slides anpassen](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)

**Comment by jgroeneveld** [comment]
@phoet i did so. It will be a short talk
