### ISSUE TITLE
September Meetup

### ISSUE THREAD

**Issue by phoet** [rughh/planning#39]
Termin: 14.09.2016 19:00

* [x] Location
* [x] [Event anlegen](http://hamburg.onruby.de/admin/)
* [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
* [x] Promo auf Twitter
* [ ] [Push-Notification für iOS app senden](http://hamburg.onruby.de/admin/dashboard)
* [ ] [Slides anpassen](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)

**Comment by MrMarvin** [comment]
Location: Gerne mal wieder bei uns @sinnerschrader.

**Comment by phoet** [comment]
@MrMarvin oh sorry, jimdo ist im prinzip schon für den september gebucht. wäre für euch auch der oktober denkbar?

**Comment by MrMarvin** [comment]
@phoet denkbar klar, muessten wir dann im September noch mal terminlich wegen Urlauben und Co gucken.

**Comment by phoet** [comment]
wenn du oktober meinst, dann ja :) wir kommen dann noch mal auf dich zu?

**Comment by MrMarvin** [comment]
> wenn du oktober meinst, dann ja :) wir kommen dann noch mal auf dich zu?

Ja, genau. __Im__ September gucken wir, ob und wie wir __fuer__ den Oktober koennen. :)

**Comment by phoet** [comment]
@gmitruby  would you like to present your talk in september? http://hamburg.onruby.de/topics/building-complex-queries-with-the-active-record-query-interface-hh

**Comment by gmitruby** [comment]
Moin Peter,
    (ich antworte mal von meiner Hauptadresse)
    wenn der Termin wie erwartet am 14.09.
        stattfindet: sehr gerne!
      
    Muss ich neben den Slides irgendetwas Besonderes
        wissen / vorbereiten? Notebook nehme ich mit, es hat
        Mini-DisplayPort.
    Viele Grüße,
    
      
    /Gerrit
      
    
    
    
    On 25.08.2016 13:50, Peter Schröder
      wrote:
    
    
      @gmitruby would you like to present
        your talk in september? http://hamburg.onruby.de/topics/building-complex-queries-with-the-active-record-query-interface-hh
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/rughh/planning","title":"rughh/planning","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/rughh/planning"}},"updates":{"snippets":[{"icon":"PERSON","message":"@phoet in #39: @gmitruby  would you like to present your talk in september? http://hamburg.onruby.de/topics/building-complex-queries-with-the-active-record-query-interface-hh"}],"action":{"name":"View Issue","url":"https://github.com/rughh/planning/issues/39#issuecomment-242359318"}}}
    
    
    -- 
      
        
        Gerrit Bruno Blöss
        Managing Director / Geschäftsführer
        gbb@study.eu
        
        
        
        Study.EU - Brickubus UG (haftungsbeschränkt)
        Curt-Bär-Weg 25
        21035 Hamburg
        Germany / Deutschland
        
        Handelsregister: Amtsgericht Hamburg, HRB 128467
        Steuernummer: 44/708/00637
        USt-IdNr.: DE 291545766

**Comment by phoet** [comment]
der termin ist fix. für macs sollten wir adapter da haben. dann bis dahin!

**Comment by phoet** [comment]
@gmitruby ich plane dich jetzt fest mit ein

**Comment by phoet** [comment]
@robin-drexler soll ich dich auch mit einplanen für nächsten mittwoch? könntest du dann hier kurz titel und abstract reintun? http://hamburg.onruby.de/topics/new

**Comment by robin-drexler** [comment]
Reicht Freitag fürs abstract?

**Comment by phoet** [comment]
@robin-drexler sichi
