### ISSUE TITLE
Meeting Feb 2015

### ISSUE THREAD

**Issue by halfbyte** [rughh/planning#4]
Da von Januar einiges übrig geblieben ist, hier schon mal eine neue Issue

Als Vorschläge für Talks im Rahmen der "Sprachen" sind für Februar im Gespräch:

* Rust (@skade, via @halfbyte)
* Elixir (@BjRo, via @titanoboa)
* Lua (@hmans, via @titanoboa)

Wir haben dann noch mal Go im Köcher, dafür habe ich @tobstarr schon angefragt, der könnte im März. Eventuell einen der Talks vom Feb in den März schieben?

* [x] Location
* [x] Talks / Format
* [x] Promo auf Twitter / Facebook ...
* [x] Push-Notification für iOS app senden
* [x] [Slides anpassen](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)

**Comment by skade** [comment]
In welchem Format ist das jetzt und gibts ne kleine Aufgabe?

**Comment by rubiii** [comment]
vielleicht kann der @nicolai86 was über go erzählen, falls wir das im februar machen wollen und der @tobstarr da keine zeit hat.

**Comment by halfbyte** [comment]
@rubiii: Frag doch mal :)

Vier Vorträge sind vielleicht ein bisschen viel, dachte ich.

**Comment by rubiii** [comment]
aso :) ja, da haste vielleicht recht. ne, drei find ich gut.

**Comment by tobstarr** [comment]
also im Februar sollte ich schon können, falls sich das missverständlich angehört hatte.

**Comment by halfbyte** [comment]
@tobstarr Ah, ein off-by-one-error, Du sagtest auf Twitter "Übernächstes Treffen", daraus schloss ich März.

**Comment by tobstarr** [comment]
naja, nächstes wäre für mich Mittwoch, übernächstes (wo ich wieder kann) dann das im Februar

**Comment by titanoboa** [comment]
Gab es schon irgendwelche Absprachen in Sachen Raum? Wenn nicht, kann da ggf. jemand der Zugriff hat via hamburgsync twittern, ob wer Interesse hat uns einzuladen? Vielleicht meldet sich ja jemand freiwillig, um eine location bereitzustellen

**Comment by nesQuick** [comment]
Wenn sich niemand findet: Ihr seid immer bei uns willkommen! :)

2015-01-15 16:19 GMT+01:00 titanoboa <notifications@github.com>:

**Comment by titanoboa** [comment]
Vielen Dank @nesQuick, wir kommen immer gern zu Euch! Der Abwechslung halber würd ich aber erstmal schauen, ob sich vielleicht für Februar was anderes findet.

**Comment by nesQuick** [comment]
Deshalb sagte ich immer gern als fallback ;)

**Comment by phoet** [comment]
@tbk303 Haskell?

**Comment by tbk303** [comment]
Februar könnte knapp werden, aber März geht bestimmt.

**Comment by phoet** [comment]
hab da mal noch so TODOs eingefügt. vielleicht können wir das über die zeit als template für neue event-issues übertragen

**Comment by schurock** [comment]
Die Februarausgabe kann sehr gern wieder bei mindmatters stattfinden.

**Comment by titanoboa** [comment]
Vielen Dank, @schurock 
Wir kommen gern zu Euch!

**Comment by skade** [comment]
Hätte jemand ein Bett am 11. und einen Arbeitsplatz für den 12. für mich? Von Hamburg nach Berlin ist nachts immer so anstrengend... :)

**Comment by nesQuick** [comment]
@skade den Arbeitsplatz am 12. kann ich dir gern bei uns (Jimdo) anbieten :)

**Comment by phoet** [comment]
bett nich, aber schlafcouch wenn's recht ist. auch gleich um die ecke von mindmatters

**Comment by phoet** [comment]
@titanoboa falls du das nächste mal selber twittern willst, ich habe mal ein paar zugangsdaten in dieses private repo geworfen: https://github.com/rughh/logins

**Comment by skade** [comment]
@phoet waagerecht und ein wenig länger als 1.85m reicht mir völlig. Nehm ich! Bring ich nen Schlafsack mit oder nicht?

@nesquick: das passt gut, da kommt man ja abends gut zum Zug.

Danke euch Beiden!

**Comment by titanoboa** [comment]
@skade Du erzählst uns was über Rust? Wäre cool, wenn du auf http://hamburg.onruby.de/#topics einen Eintrag erstellen könntest - muss kein langer Text sein, ein zwei Sätze sind vollkommen genug

**Comment by titanoboa** [comment]
> @titanoboa falls du das nächste mal selber twittern willst,...
Prima, Danke @phoet

**Comment by titanoboa** [comment]
@tobstarr Steht das Angebot noch? Würdest du uns am 11.2. was über Go erzählen?

**Comment by tobstarr** [comment]
steht noch

**Comment by titanoboa** [comment]
@tobstarr cool :-) dann plane ich dich ein. Kannst Du auf http://hamburg.onruby.de/#topics einen Eintrag erstellen? Muss nicht lang sein, ein zwei Sätze reichen vollkommen.

**Comment by titanoboa** [comment]
Hab gerade auch mündlich die Zusage für den Elixir-Talk bekommen. Es gibt dann also Rust, Go und Elixir im Februar, im März dann Lua.

**Comment by phoet** [comment]
\o/

**Comment by titanoboa** [comment]
@tobstarr hab Dich jetzt mal ohne Beschreibungstext in die Ankündigung auf onruby aufgenommen. Falls Du doch noch eine Beschreibung da haben möchtest, können wir das ja noch nachtragen

**Comment by skade** [comment]
Hi @titanoboa, @phoet und @tobstarr,

ich muss euch leider für heute absagen. Ich hab Hals- und Ohrenschmerzen und Schnupfen, das verträgt sich nicht so gut mit nem Vortrag :).

Nächsten Monat dann?

Gruß,
Florian

**Comment by phoet** [comment]
Mooooh :( gute Besserung!
Am 11.02.2015 08:28 schrieb "Florian Gilcher" <notifications@github.com>:

**Comment by nesQuick** [comment]
:syringe::hospital::ambulance: Gute Besserung

**Comment by phoet** [comment]
ich hab das mal auf diesem twitter announced und den florian aus dem termin rausgenommen.

**Comment by phoet** [comment]
Da wir unsere timeboxen heute sehr überzogen haben und das in der
Vergangenheit häufiger passiert ist würde ich gerne was dagegen machen beim
nächsten Event. Meinungen?
Am 11.02.2015 22:35 schrieb "titanoboa" <notifications@github.com>:

**Comment by titanoboa** [comment]
Hab mal ein eigenes issue angelegt, um das zu besprechen: #8

**Comment by rubiii** [comment]
@skade sehr schade. gute besserung!
