### ISSUE TITLE
October Meetup

### ISSUE THREAD

**Issue by phoet** [rughh/planning#40]
Termin: 12.10.2016 19:00

* [x] Location
* [x] [Event anlegen](http://hamburg.onruby.de/admin/)
* [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
* [x] Promo auf Twitter
* [x] [Push-Notification für iOS app senden](http://hamburg.onruby.de/admin/dashboard)
* [x] [Slides anpassen](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)

**Comment by phoet** [comment]
for location see https://github.com/rughh/planning/issues/39#issuecomment-240447355

**Comment by titanoboa** [comment]
@MrMarvin bleibt es dabei, dass ihr im Oktober die usergroup beherbergt?

**Comment by bkarstaedt** [comment]
@titanoboa Jup, wir würden die usergroup gerne bei uns/SinnerSchrader am 12.10. ausrichten. Ich werde mich dann mit Marvin zusammen um Snacks, Getränke usw. kümmern

**Comment by bkarstaedt** [comment]
@titanoboa Snacks und Getränke sind geordert, wäre super wenn ihr das Event auf der RUBHH Seite anlegen würdet :)

**Comment by andreaswachowski** [comment]
@salzig sagte, es werden noch Talks gesucht. Ich hätte evtl. noch einen CSS-Talk, den ich im Sommer firmenintern gehalten hatte (CSS Lessons Learnt, siehe https://github.com/andreaswachowski/css-lessons-learnt/blob/master/css_lessons_learnt.md). Wäre das was? Und wie lange dürfte der Talk dauern?

**Comment by bkarstaedt** [comment]
Ich könnte was über unser internes "operations" Gem erzählen (das wir bald mal open sourcen möchten). Das Gem bietet eine DSL über der Health Checks diverser Schnittstellen (z.B. externe API, Datenbanken) konfiguriert werden können und schließlich über eine Route vereint abgefragt werden kann (als JSON, XML und eine visuelle HTMl Variante). Hierzu gibt es auch ein Dashboard, das den Zustand aller Knoten visualisiert.

Das wäre dann recht spontan und ich würde es am live Beispiel demonstrieren (Slides werde ich wegen Zeitmangel kaum mehr hinbekommen).

**Comment by titanoboa** [comment]
@andreaswachowski sehr gern 

Die Daumenregel für die Länge ist grob 'möglichst nicht länger als eine halbe Stunde'

besonders toll wäre es, wenn du noch einen Eintrag unter http://hamburg.onruby.de/#topics erstellst - ein bis zwei Sätze sind genug

**Comment by titanoboa** [comment]
@bkarstaedt super. slides brauchst du nicht, live demo ist prima

besonders toll wäre es, wenn du noch einen Eintrag unter http://hamburg.onruby.de/#topics erstellst - ein bis zwei Sätze sind genug

**Comment by bkarstaedt** [comment]
@titanoboa Habe einen Eintrag angelegt: http://hamburg.onruby.de/topics/sinnerschrader-gem-to-operate-15-rails-applications :)

**Comment by titanoboa** [comment]
ausserdem haben wir noch #44

**Comment by titanoboa** [comment]
@bkarstaedt @andreaswachowski vielen dank Euch, ist jetzt Teil der Veranstaltungsankündigung http://hamburg.onruby.de/events/ruby-usergroup-hamburg-oktober-2016

**Comment by titanoboa** [comment]
@bkarstaedt @andreaswachowski wie ist es bei euch mit der Sprache, tragt Ihr auf deutsch vor oder könntet ihr euch vorstellen, das auf english zu machen?
Hab gerade vernommen, es sind voraussichtlich ein paar Leute da nicht gut deutsch verstehen

**Comment by andreaswachowski** [comment]
@titanoboa Ich kann den Vortrag sehr gerne auf Englisch halten.

**Comment by bkarstaedt** [comment]
@titanoboa Englisch ist ok
