### ISSUE TITLE
Talk: offline first

### ISSUE THREAD

**Issue by titanoboa** [rughh/planning#41]
Vortragsangebot zum Thema 'offline first', ca. 30 Minuten, 
- Thema: 'offline first'
- Dauer: 20-30 Minuten
- Q&A: ja
- Sprache: Englisch oder Deutsch
- Termin: muss noch abgesprochen werden, evntl. September #39 oder Oktober #40

**Comment by phoet** [comment]
wirst du den halten?

**Comment by titanoboa** [comment]
ich? besser nicht, ich hab da keine Ahnung von
hab halt den github username von Stefanie nicht, deshalb kein mention hier
ich kann nochmal nachfragen, aber ich gehe davon aus dass es eher Oktober wird

**Comment by titanoboa** [comment]
wegen Termin sagt @SteffiPeTaffy voraussichtlich diese Woche Bescheid

**Comment by phoet** [comment]
ping @SteffiPeTaffy

**Comment by titanoboa** [comment]
@SteffiPeTaffy wäre der 12.10. was für Deinen talk?

**Comment by phoet** [comment]
ping @SteffiPeTaffy
