### ISSUE TITLE
GitHub Community Event

### ISSUE THREAD

**Issue by phoet** [rughh/planning#42]
@mat offered that we could join the community event that will be hosted at XING due to some GitHub folks visiting them

> Wäre es möglich, am Mittwoch, 26. Oktober die Ruby UG stattfinden lassen, gerne bei uns bei XING?

**Comment by titanoboa** [comment]
Fine by me, but is it instead of or in addition to the regular Oktober meetup?

**Comment by mat** [comment]
Peter and I thought it'd make more sense as non-regular event, which I like.

**Comment by phoet** [comment]
additionally i'd say. i do not want to skip the normal schedule.

@mat's idea was

"Ruby meets iOS and GitHub”
* [ ] 1 Talk from CocoaHeads
* [ ] 1 Talk from Rubyists
* [x] 1 Talk from GitHubs

**Comment by titanoboa** [comment]
I totally agree that skipping the normal schedule is something we should usually avoid. So let's do it as an additional special event.

**Comment by mat** [comment]
👍 for additional, non-regular event.

CocoaHeads have already recruited a volunteer for a talk, it's gonna be something along the lines of _My new life working with Ruby (Confessions of an iOS Developer)_

I'll talk to GitHub about the talk they're going to give.
Is there anything you want to know from them, hear a talk from them about? (Can't promise they'll follow my wishes, though ;))

**Comment by phoet** [comment]
@mat could not yet find somebody and unfortunately we did not really promote the event on our usergroup last night...

concerning the organization at XING, are you going to handle that or do you need any help with this?

**Comment by titanoboa** [comment]
ich werde an dem abend voraussichtlich nicht da sein

**Comment by mat** [comment]
No worries guys, thanks for your help 👍
The result so far: https://www.meetup.com/xingdevs/events/234617847/

**Comment by phoet** [comment]
great, see you then
