### ISSUE TITLE
Talk: react and rails

### ISSUE THREAD

**Issue by titanoboa** [rughh/planning#43]
@fdietz might be able to give a talk about integrating react with rails

**Comment by phoet** [comment]
@fdietz do you want to do that next week or on another meetup

**Comment by fdietz** [comment]
Moin! Sorry, for my late answer. I've discussed this with Kerstin already in person. I cannot give you a date currently, due to other personal live stuff. But, will start working on the presentation and ping you again when I'm ready. So, this will be a future talk :-)

**Comment by titanoboa** [comment]
I've talked to the speaker, the talk is not going to be at our October meetup

**Comment by phoet** [comment]
@fdietz still interested?

**Comment by fdietz** [comment]
Sorry, for not getting in touch with you again! Finished my project at went straight for my vacation. Since the arrival of https://github.com/rails/webpacker (i saw there's going to be a talk about it too), my topic is basically obsolete, IMHO!

**Comment by phoet** [comment]
@fdietz ok, thank's and enjoy your vacation. if there is anything else you would like to present, please feel free to ping me at any time. i'm going to close this for now.
