### ISSUE TITLE
Talk: offline first example app

### ISSUE THREAD

**Issue by titanoboa** [rughh/planning#45]
@KlausTrainer is working on an offline first app and could give some insights

could be a nice follow-up to #41

**Comment by phoet** [comment]
@klausTrainer still interested?

**Comment by KlausTrainer** [comment]
@phoet oh, sorry, just saw that now as you closed the issue. I still think I wanna do a talk about this topic some time. But currently I'm quite busy with all kinds of other stuff. I'll open a new issue once my plan for doing that talk becomes more concrete.

**Comment by phoet** [comment]
@KlausTrainer sounds like a plan!
