### ISSUE TITLE
November Meetup

### ISSUE THREAD

**Issue by titanoboa** [rughh/planning#47]
Termin: 9.11.2016 19:00
- [x] Location
- [x] [Event anlegen](http://hamburg.onruby.de/admin/)
- [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
- [x] Promo auf Twitter
- [x] [Push-Notification für iOS app senden](http://hamburg.onruby.de/admin/dashboard)
- [x] [Slides anpassen](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)

**Comment by titanoboa** [comment]
to be clarified:

@andywenk might be willing to host us, including a CouchDB 2.0 talk
@PragTob might be willing to drop by with a talk

**Comment by PragTob** [comment]
I can do November or December I think :)

What's the preferred talk length?

Currently I can do:

* How did AlphaGo beat the strongest human player? (40 mins min sadly)
* Elixir & Phoenix - fast, concurrent and explicit
* *insert catchy title about code readability* - used to be called "Code is read many more times than written"

I'm also working on a benchmarking in Elixir talk atm which is probably a bit off and would like to prepare some form of motivation (as in human motivation and team motivation) and potentially communication talk if that's of any interest :)

Tobi

**Comment by KlausTrainer** [comment]
Hi @PragTob!

Interesting talk ideas! I'd actually love to hear all of them 😄 

The benchmarking in Elixir talk sounds indeed slightly too special for the Ruby meetup, although the people there are usually quite open to all kinds of topics (also if those don't directly relate to Ruby). I'd just like to let you know that there's also a [nice Elixir meetup in Hamburg](https://www.meetup.com/Elixir-Hamburg/). So if you'd like to do a talk there, feel free to make your proposal here: https://github.com/hh-ex/planning/issues

Looking forward to seeing you!

**Comment by PragTob** [comment]
@KlausTrainer thanks for the info, I'll give the benchmarking talk at Elixirlive in early december. Only way to make it happen is for me to go to Hamburg twice (I'm from Berlin) or if both meetups were close together to bug my Hamburg friends for that long :D

**Comment by titanoboa** [comment]
@PragTob talk length usually is 'not much longer than 30 minutes' but we can talk about that. we simply want to avoid that all of a sudden we have three speakers talking for an hour each

we already had an elixir talk, but that was quite some time ago and iirc it did not cover phoenix, so elixir & phoenix is an option. I agree that the benchmarking elixir might be too special.
readability is an excellent topic anyways, and we have not had this in a while iirc
alphago is also cool

about the schedule: I'm not sure if we have time to prepare it, but the December meetup is usually a waffle and Glühwein thing, so it's up to you if you prefer your audience to be sober ;-)

**Comment by andywenk** [comment]
@PragTob @titanoboa @KlausTrainer I personally would be extremely happy to here a talk about Elixr & Phoenix ;-)

**Comment by andywenk** [comment]
Wir können am 09.11. gerne bei uns (sum.cumo) die RUGHH machen.

**Comment by titanoboa** [comment]
@andywenk super, wir kommen gern mal wieder zu euch

**Comment by andywenk** [comment]
@titanoboa wollt Ihr die Website aktualisieren, dass das bei uns stattfindet? Dann würd' ich das auch mal bei Twitter bekannt geben und so

**Comment by PragTob** [comment]
Hey there,

while I prefer a medium sober audience I'll probably have to skip to December - 14th of December? One of the dogs of my parents/my dog has a major operation and needs direct supervision for 2 weeks after that and this falls right into the week where I said I'd watch her...

So, hard to do a Hamburg trip that time. If you can't find something else I could arrive that day and leave early the next day but would actually prefer to stick around a bit :)

Cheers + sorry for late notice,
Tobi

**Comment by phoet** [comment]
@andywenk i created the event: http://hamburg.onruby.de/events/ruby-usergroup-hamburg-november-2016 

what about the couchdb talk? is this going to happen? could you add it to the topics if so?

**Comment by andywenk** [comment]
@phoet thanks !!! Yes I will give the CouchDB talk and add it to the topics

**Comment by titanoboa** [comment]
we're also going to have a lightning talk (about 10 min) #50

**Comment by phoet** [comment]
Just FYI, won't be there due to spontaneous trip to Spain 😎

**Comment by andywenk** [comment]
warum is'n allet uff Englisch hia eigentlüsch? 👯‍♂️ 

Wäre cool, wenn die anderen talks auch noch in die Topics kämen ... Freu mich auf Euch alle ;-)

**Comment by halfbyte** [comment]
@titanoboa I'll be there and I can also put in a lightning talk into the mix. I'll be adding it to the platform after finishing typing this comment.

**Comment by halfbyte** [comment]
@titanoboa Also, do you have @uygars confirmed for the lightning talk? I see the topic in the app but it's not added to the event, so just wanted to make sure I don't "fix" something by mistake.

**Comment by titanoboa** [comment]
@halfbyte +1 for another lightning talk and afaik @uygars is going to give her talk tomorrow as planned

**Comment by andywenk** [comment]
heya ... please do all these lightning talks. I will do my CouchDB talk but ran into a timing problem jobwise. So I guess it will be only aprox 30 minutes  ... sorry ...

**Comment by titanoboa** [comment]
30 minutes are perfectly fine
I'm not a big fan of those long talks anyways (at least for after work
meetups)

**Comment by andywenk** [comment]
@titanoboa +1 ;-)
