### ISSUE TITLE
Refugees on Rails

### ISSUE THREAD

**Issue by rubiii** [rughh/planning#48]
Hey,

just wanted to let you know that the #rorhamburg program has started and that I suggested that coaches take their students to the next or any upcoming usergroup. So I hope there may be some newcomers at the next meeting(s) and maybe there’s also something we could do to make them feel more welcome.

I will not be at the next meeting on Wednesday, but I’m definitely planning to attend future meetings with my student.

Cheers,
Daniel

**Comment by rubiii** [comment]
Not saying that “we” have to do something now, but I just think it’s good if everyone knows about this program and the fact that there might (hopefully) be some new people.

**Comment by titanoboa** [comment]
great! we'll do our best to make them feel welcome
unfortunately, this is a very short notice, so we cannot ensure that all talks are going to be in english
I'll clarify with the speakers if they can present in english, but in the end it is up to them if they feel comfortable with that

**Comment by phoet** [comment]
would it make sense to (re)tweet a bit about it?

**Comment by titanoboa** [comment]
I've reached two of the speakers and they agreed to present in english, so at least two of the three presentations are going to be in english

**Comment by titanoboa** [comment]
as far as I understand, there is no particular action to be taken on our side, so I close this ticket
