### ISSUE TITLE
December meetup

### ISSUE THREAD

**Issue by titanoboa** [rughh/planning#49]
Termin: 14.12.2016 19:00
- [x] Location
- [x] [Event anlegen](http://hamburg.onruby.de/admin/)
- [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
- [x] Promo auf Twitter
- [x] [Push-Notification für iOS app senden](http://hamburg.onruby.de/admin/dashboard)
- [x] [Slides anpassen](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)
- [x] Waffeleisen
- [x] Glühwein-Warmmachgelegenheit
- [x] Glühwein

**Comment by PragTob** [comment]
Hey as I fell through for November (#47) I'd like to make it to this one and nail it down (it's already in my calendar).

For November we settled on the Elixir & Phoenix talk, however I met quite some Hamburgers (is that the correct English way?), hi @andywenk, at Rubyconf Portugal where I gave the talk. So, I was thinking that maybe it'd be good to do another talk. Still totally up to doing the other talk, just thinking out loud.

So, with that in mind here is another list (repost/edit from before):

* How did AlphaGo beat the strongest human player? (40 mins min sadly)
* Elixir & Phoenix - fast, concurrent and explicit: Basic elixir/phoenix intro focussing what's great about the language and framework aside from speed
* _insert catchy title about code readability_ - used to be called "Code is read many more times than written": Dive into writing readable code mostly on the method level, e.g. practices and rules to apply along with rationalization and some practices to help keep them and improve the code base
* I could also undust the good old [shoes](http://shoesrb.com/) and talk about UI programming in Ruby (and maybe OSS)
* I can also talk about meta programming in Ruby with practical application of (potentially live) coding a simple library for aspect oriented programming ([full library - after_do](https://github.com/PragTob/after_do))
* a soft skills introduction talk covering motivation theory (f.ex. Mastery, Purpose, Autonomy), group dynamics and leadership behavior (f.ex. Forming, Storming, Norming, Performing) - recent experiences made me really want to push these as a talk again next year :)

So, yeah let me know if this works out :)
Tobi

**Comment by titanoboa** [comment]
@rughh/owners Ich fürchte, ich werde keine Zeit haben, mich um das Dezember Meetup zu kümmern (nur falls jemand gehofft hat, ich würde, oder so)

**Comment by halfbyte** [comment]
@rughh/owners Ich nehme das mal tentativ an mich. @phoet bist Du da schon wieder in der Stadt und könntest mich Waffelmäßig unterstützen?

Ich bin echt komplett raus, gab es noch Kandidaten für einen Ort?

**Comment by halfbyte** [comment]
@PragTob Tough choice, they are all good. I'd love to hear the Elixir/Phoenix talk. I believe we had an Elixir talk a while back, but I can't remember if it covered Phoenix as well.

Would personally love to hear the AlphaGo talk as well, (40 Mins not being a problem, really).

**Comment by phoet** [comment]
Helfe gerne beim Backen!

Jan Krutisch <notifications@github.com> schrieb am Di., 22. Nov. 2016,
15:19:

**Comment by andywenk** [comment]
where will the meeting happen? iirc December is sinner schrader right?

@PragTob hi :D Elixir FTW !

**Comment by titanoboa** [comment]
Glaub nicht das es schon Kandidaten für den Ort gab, kann mich zumindest nicht erinnern. sinnerschrader waren wir im Oktober

**Comment by PragTob** [comment]
Ihr koennt ja nochmal schauen was ihr wollt waere gut wenn ich bis zum ~6.12 wissen wuerde was ihr gerne hoern wollt :) Elixir & AlphaGo sind mehr oder weniger fertig, bei Elixir wuerde ich schauen dass ich noch hier und da evtl. was aendere :)

**Comment by halfbyte** [comment]
Habe gerade bei mindmatters angefragt.

**Comment by halfbyte** [comment]
@PragTob wir hatten im Februar 2015 das letzte Mal einen Elixir talk, insofern glaube ich, wir nehmen mal den Elixir/Phoenix talk. Wir laden Dich dann einfach im nächsten Jahr mehrfach ein damit Du die alle mal bei uns hälst :)

**Comment by PragTob** [comment]
@halfbyte ok, Zeitvorgabe? Ich werd schauen dass ich nen bischen was raus nehme und nen anderen interessanten Part rein nehme, damit die dies schon gesehne haben auch noch etwas neues lernen. Und ich kauf mir dann mal tickets :)

**Comment by halfbyte** [comment]
@PragTob Fast egal. 30-40 Minuten sind überhaupt kein Problem, wenn es einen Tick länger dauert ist auch okay, aber Du weisst ja selbst: Besser wird so ein Talk eher nicht, wenn er länger wird :)

**Comment by halfbyte** [comment]
Okay. mindmatters hat abgesagt, schade. Andere Vorschläge?

**Comment by nesQuick** [comment]
Grad zum Waffeln kann ich die Kaminstimmung bei SABIO sehr empfehlen 🔜  ping @dszam

**Comment by dszam** [comment]
@nesquick ich checke mal, ob jemand hier ist. Ich kann am 14.12. leider nicht. Die Lounge sollte aber frei sein.

**Comment by dszam** [comment]
@rughh die SABIO Lounge steht bereit und ich habe auch jemanden gefunden (@MrEmdja), der sich um euch kuemmert. Falls es romantisch werden soll, machen wir auch den Kamin an.

**Comment by halfbyte** [comment]
Das klingt toll, dank an @nesQuick für's helfen! 

@dszam @MrEmdja Wir servieren normalerweise Waffeln und Glühwein im Dezember. Waffelzubehör bekommen wir hin, allerdings wäre die Frage, ob ihr eine Möglichkeit habt Glühwein warm zu machen und ggf. auch bereit zu stellen oder ob wir das noch organisieren müssen.

**Comment by phoet** [comment]
danke @dszam !

**Comment by dszam** [comment]
@halfbyte jep. Wir haben zwei Herdplatten in der Lounge. Sollte also kein Problem sein.

**Comment by halfbyte** [comment]
Ja, eh, auch von mir noch mal Danke, @dszam :)

Noch mal zu dem Glühwein: Sind Töpfe auch vorhanden?

**Comment by dszam** [comment]
@halfbyte muss ich morgen checken. Bin heute nicht im Büro

**Comment by halfbyte** [comment]
@phoet Kannst Du Waffeleisen stellen? Wie machen wir das jetzt mit dem Glühwein? Würde den SABIO sponsoren? @dszam @mrEmdja ? Wenn nicht, @phoet, was wäre denn da eine gute Quelle? IKEA? :)

**Comment by dszam** [comment]
Jep. SABIO sponsort den Glühwein. Ich besorge den morgen. Wie viel braucht ihr?

**Comment by halfbyte** [comment]
Cool! Beim letzten Mal hatten wir glaube ich 5 Liter angesetzt. Ihr habt, nehme ich an, auch alternative Getränke an Bord für Leute, die keinen Glühwein trinken?

Issue von 2015 ist #19, zum nachlesen.

**Comment by halfbyte** [comment]
Hier das Waffelrezept, das ging ja letztes Mal ganz gut auf und war lecker. Zutaten kaufe ich ein, Werkzeug etc. packe ich auch ein.

http://mobile.chefkoch.de/rezepte/m1283881233743104/Quarkwaffeln.html

**Comment by halfbyte** [comment]
@PragTob Magst Du entweder 1. Deine Talk bei [hamburg.onruby.de](http://hamburg.onruby.de/topics/new?) eintragen oder 2. hier einfach einen Abstract und Titel reinwerfen? Dann kann ich das Event auf der Seite vollständig machen.

**Comment by phoet** [comment]
Waffeleisen bring ich mit!

Jan Krutisch <notifications@github.com> schrieb am Mo., 12. Dez. 2016,
17:16:

**Comment by halfbyte** [comment]
@phoet Reicht eins?

**Comment by PragTob** [comment]
@halfbyte eintragen sehr gerne, mach ich gleich. Ich kenn das mit diesen speakern die das ewig nicht machen :D

**Comment by phoet** [comment]
@halfbyte gute frage, hab aber nur eins

**Comment by PragTob** [comment]
ah was mir da einfaellt (eingetragen) was is denn die bevorzugte Vortragssprache? Ich hab ewig keinen Vortrag mehr auf Deutsch gegeben :D

**Comment by phoet** [comment]
@PragTob englisch ist super

**Comment by halfbyte** [comment]
> @halfbyte gute frage, hab aber nur eins

Hm. Überlegte eh, mir sowas mal zuzulegen, wäre vielleicht eine Gelegenheit. Ich schau mal.

**Comment by dszam** [comment]
Glühwein: :white_check_mark:
Töpfe: :white_check_mark:

**Comment by andywenk** [comment]
Ich werde morgen leider nicht dabei sein können :( - Kinder Weihnachtsfeierei und danach noch Lemmy Schule ... ich wünsche ein herrliches kleines Abschieds usergroup Treffen.

**Comment by halfbyte** [comment]
Dank an alle, hat Spaß gemacht, sehr, sehr coole Location, @dszam! Kommen wir bestimmt mal wieder drauf zurück. Lust mal einen Vortrag über Eure Erfahrungen mit Chef zu halten? :)
