### ISSUE TITLE
Collective Sticker Order

### ISSUE THREAD

**Issue by nesQuick** [rughh/planning#5]
As we discussed on the last meetup we will start a collective @stickermule order so we can save some shipping cost.

We will order a certain amount of these stickers: http://www.stickermule.com/marketplace/2284-hamburg-ruby-usergroup

![](http://d21ii91i3y6o6h.cloudfront.net/gallery_images/from_proof/2284/large/1414104130/hamburg-ruby-usergroup.png)

Let's see how much of a interest we have in our group. The interest determines the prices, here is what you could expect:

```java
1   Sticker  $3.06  ($3.06 p. pc.)
10  Stickers $18.50 ($1.85 p. pc.)
100 Stickers $80.40 ($0.80 p. pc.)
```

Shipping is roughly **$49** please just comment here how many you'd like. I will take care of any further organisation. I'd aim for **> 100 stickers** so we get a better price!

cheers!

**Comment by sgeorgi** [comment]
I'd take 20

**Comment by JanAhrens** [comment]
Great stuff! I'm also taking 20 stickers.

**Comment by phoet** [comment]
@nesQuick FYI 

> Sollte der Warenwert 22,- Euro übersteigen, so ist Mehrwertsteuer auf den Warenwert zu entrichten. Sofern der Warenwert aber noch unterhalb von 150 Euro ist, fallen keine Zölle an und die Ware ist Zollfrei. Zitat: "(...) Höchstgrenze für die zollfreie Einfuhr von Kleinsendungen auf 150 Euro je Sendung (...)"

this is incl. shipping, so we can max at ~108€ for stickers.

since shipping is free to canada for orders >50$ i'd ask @kurtfunai if he can order it and send a package to germany. that might be much cheaper. :kissing_cat:

**Comment by nesQuick** [comment]
@phoet that would be awesome! :sparkling_heart:

**Comment by kurtfunai** [comment]
For sure guys, just let me know how many you need! :smiley: :maple_leaf:

**Comment by phoet** [comment]
@kurtfunai an order for 300 stickers is on the way to you https://www.stickermule.com/orders/R174360725?token=8e77d8f56a0d4818

**Comment by kurtfunai** [comment]
@phoet woohoo!

**Comment by phoet** [comment]
@kurtfunai don't forget to grab some for yourself!

**Comment by phoet** [comment]
stickers are on their way: http://wwwapps.ups.com/WebTracking/track?track=yes&trackNums=1ZA576236794779997

**Comment by kurtfunai** [comment]
@phoet seems they had issue with address.
http://wwwapps.ups.com/WebTracking/track?track=yes&trackNums=1ZA576236794779997

If you need another address, use my work address: `185 Rideau Street, Second Floor, Ottawa, ON, K1N 5X8 `

**Comment by phoet** [comment]
fuck me, UPS is such a shitshow!

@kurtfunai can you try to login and change the address yourself? i can't get anything to work on that fucking page.

**Comment by kurtfunai** [comment]
@phoet I'll get in contact with UPS tomorrow and try to correct the address. Their support is closed today.

**Comment by phoet** [comment]
@kurtfunai <3

**Comment by phoet** [comment]
:maple_leaf: :package: :de:

**Comment by phoet** [comment]
stickers are going to be distributed on the next meetup or at my jimdo desk!

**Comment by nesQuick** [comment]
:tada:

**Comment by phoet** [comment]
i'm taking orders here :smile_cat:  http://phoet.jimdo.com/

@sgeorgi @JanAhrens please let me know how i can get the stickers to you

**Comment by sgeorgi** [comment]
Ordered 20, just tell me where and how to pay you :)
