### ISSUE TITLE
Sketching for Software

### ISSUE THREAD

**Issue by filtercake** [rughh/planning#51]
Moin.

In the new year I would like to talk a bit about Sketching in Software Development: why it is important, why *everybody* should do it and how easy it is to learn.

I already did a mini session at the UX Camp Hamburg in August, which consisted of [some short slides](https://slidr.io/filtercake/sketching-for-software-mini-edition#30) and some basic exercises everybody can do with any set of pen and paper.

Also I would like to offer the full workshop to Ruby UG members on a date following the Usergroup – for free :)  see https://ti.to/filtercake-workshops/sketching-for-software-16-11-19/ as example.

Cheers,
Fabian

**Comment by phoet** [comment]
that would be great! <3

**Comment by filtercake** [comment]
cool :)

I could offer either January or March then...

**Comment by phoet** [comment]
@filtercake should we put this in for march?

**Comment by filtercake** [comment]
@phoet 👍

What date is the march ug?

**Comment by phoet** [comment]
8th of march

**Comment by phoet** [comment]
@filtercake could you write down something small here: http://hamburg.onruby.de/topics/new

would also be great to know if you need any material and how much time we block for it.

**Comment by filtercake** [comment]
Sorry for the delay :/

If every attendee could get a standard, neutral-yellowish postit block and a pen or fineliner, that would be perfect. Any other small notepad will do too. Lmk if should take care of that, sure can do. 

At the ux camp i did ~10 minutes slides, then ~40 minutes exercise. That was fun, would do again like this. 

I'll add the description later...

**Comment by phoet** [comment]
it would be cool if you could bring all the stuff and then we refund you according to the receipt? would that work for you?

time slot sounds good to me, it leaves time for one more talk.

**Comment by filtercake** [comment]
> it would be cool if you could bring all the stuff and then we refund you according to the receipt? would that work for you?

👍

How many attendees were there the past couple times?

**Comment by phoet** [comment]
19 on average http://hamburg.onruby.de/locations/none

**Comment by filtercake** [comment]
> could you write down something small here: http://hamburg.onruby.de/topics/new

👍 

---

> 75% of our sensoric neurons are reserved for visuals. So why do we keep writing complicated text into Jira tickets? Why do we endure endless meetings with lots of talking and little listening? Didn’t they say “show, don’t tell”?!

> Sketching creates ownership, alignment and commitment across roles and teams with very little time investment. It convertes abstract ideas into specific form, which in turn resolves misunderstandings *before* they are crafted into shiny Photoshop mockups or production code.

> Don’t worry: sketching is not drawing and this is not art school. You can do it! :)

**Comment by filtercake** [comment]
a package with pens and postits should arrive on tuesday at mindmatters, /cc @halfbyte :)

**Comment by janz93** [comment]
@filtercake great to hear.

**Comment by filtercake** [comment]
@janz93 thx for organising <3

**Comment by phoet** [comment]
@filtercake thx again, can you share your slides?

**Comment by filtercake** [comment]
here they are: https://slidr.io/filtercake/sketching-for-software-ruby-ug-hamburg-march-2017

**Comment by janz93** [comment]
Thanks :)
