### ISSUE TITLE
Andere Tageszeit für Usergroup-Treffen?

### ISSUE THREAD

**Issue by halfbyte** [rughh/planning#52]
Ich hatte gerade eine Idee, und ich wüsste gerne, was Ihr davon haltet. Sie ist nicht super-revolutionär, haben andere auch schon versucht, teilweise mit Erfolg.

Die Theorie ist, dass ein Usergroup-Termin am Abend (also quasi nach Ende der Tagesschicht) durchaus ein paar Menschen abschreckt, bzw. davon abhält, bei uns aufzukreuzen:

- Mamas und Papas, die einfach nach der Arbeit besseres zu tun haben.
- Menschen, denen 8 Stunden am Tag Technikbeschäftigung einfach auch genug sind.

Ich habe lange (für mich selbst, aber vermutlich auch extern) so argumentiert, dass einem das wert sein muss. Allerdings habe ich seit dem immer mehr Leute kennengelernt, bei denen es ganz sicher nicht am Engagement scheitert.

Was also tun? Easy. Verlegen wir die Usergroup in die "normale" Arbeitszeit oder zumindest näher dran, whatever that means.

- Morgens. (ala Creative Mornings. Die finden z.T. sogar schon um 7:30 statt)
- Später Nachmittag, also sowas wie 16:00-18:00 Uhr
- Usergroup-Lunch?

Damit sowas funktionieren kann, braucht es meines Erachtens folgendene Dinge:

- Etwas straffer und doch etwas weiter im Voraus geplante Treffen
- Buy-In in den Firmen. Die Nachricht ist: Das gehört zum Job genauso wie auf Konferenzen und Schulungen gehen.
- Dinge, mit denen man das für die Firmen, deren Buy-In wir brauchen, attraktiver machen kann.

Der zweite Punkt ist deutlich schwieriger. Ich würde versuchen, das möglichst offensiv anzugehen und einfach zu gucken, ob man bei ein paar größeren Firmen (XING, Thoughtworks, wer fällt uns noch ein?) buy-in vom mittleren Management bekommt, in dem man die direkt anspricht.

Auch wenn das mit viel Aufwand verbunden ist, ich würde so etwas gerne mal ausprobieren und wenn es nur ist um meine Hypothese zu falsifizieren. 

Meine Fragen in die Runde:

- Was haltet Ihr grundsätzlich davon?
- Haltet Ihr das für machbar?
- Sollte ich mich einfach wieder hinlegen?

**Comment by phoet** [comment]
Ich spiele schon seit längerem mit dem Gedanken an eine ähnliche Sache. Ich würde gerne ein "elternfreundliches" Event organisieren. Am besten irgendwas wo man auch kleine Scheisser mit hin nehmen kann. Das würde die accessibility für Elternteile deutlich erhöhen.

**Comment by bkarstaedt** [comment]
Ich finde die Idee super! Ich könnte mir auch 17-19Uhr vorstellen.

**Comment by dennisreimann** [comment]
Klingt für mich erstmal schwierig, ich lasse mich da aber auch gerne eines besseren belehren. 
Persönlich fände ich so ein Treffen mitten im Tag (siehe UG-Lunch) äußerst schwierig, da hätte ich irgendwie nicht den Kopf dafür frei. Generell mag ich solche Treffen gerne als Ausklang des Arbeitstages – kann dabei aber gut nachvollziehen, dass 19-X Uhr dafür auch recht spät ist.

Am praktikabelsten finde ich daher den Ansatz, dass in den Nachmittag zu verlegen und es als Ausklang in den Feierabend zu sehen – so bleibt man recht nah an dem ursprünglichen Vorgehen und kann mir auch vorstellen, dass Arbeitgeber bei so etwas leichter mitziehen.

**Comment by janz93** [comment]
Ich denke mal das trifft wahrscheinlich nur auf mich, aber da ich die Schulbank drücke, wäre es für mich unter Berücksichtigung des Fahrtweges nicht möglich solche meetings zu besuchen.

**Comment by janz93** [comment]
Ist tauschen der Meetup zeit noch ein Thema oder kann das Issue geschlossen werden?
