### ISSUE TITLE
January 2017 Meetup

### ISSUE THREAD

**Issue by halfbyte** [rughh/planning#53]
Termin: 11.01.2017 19:00
- [x] Location
- [x] [Event anlegen](http://hamburg.onruby.de/admin/)
- [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
- [x] Promo auf Twitter
- [x] [Push-Notification für iOS app senden](http://hamburg.onruby.de/admin/dashboard)
- [x] [Slides anpassen](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)

**Comment by halfbyte** [comment]
Kandidaten für die Location?

**Comment by bkarstaedt** [comment]
Wir von SinnerSchrader würden das Event gerne mal wieder austragen :)

**Comment by phoet** [comment]
@bkarstaedt super, wäre der januar für euch schon möglich?

**Comment by bkarstaedt** [comment]
@phoet Ja, 11.1. kommende Woche passt!

**Comment by phoet** [comment]
@bkarstaedt sehr schön, dann locken wir das doch schon mal ein :) 

wenn ihr etwas zu präsentieren habt, dann sagt bescheid, wir suchen wie immer noch nach vorträgen.

**Comment by phoet** [comment]
hier wäre schon mal der link zum event http://hamburg.onruby.de/events/ruby-usergroup-hamburg-januar-2017

**Comment by phoet** [comment]
Gerrit könnte ein Thema beisteuern http://hamburg.onruby.de/topics/scraping-websites-re-engineering-a-privacy-friendly-social-media-widget

**Comment by halfbyte** [comment]
Eventuell kann auch @dennisreimann seinen schon für Dezember angedachten Elm-Talk halten, sagte er. Er wollte sich hier melden, wenn er absehen kann ob er in Hamburg ist.

**Comment by dennisreimann** [comment]
Ok, ich komme rum – der Talk dauert etwa 45 Minuten, passt das oder soll ich was kürzen?

**Comment by phoet** [comment]
@dennisreimann sehr geil! soweit ich das sehen kann haben wir platz für 45 minuten.

**Comment by dennisreimann** [comment]
@phoet Kannst du "Elm – Funktionale Frontend-Entwicklung" als Titel mit auf der Website eintragen? Dann twitter ich das gleich mal raus …

**Comment by phoet** [comment]
@dennisreimann klaro, vielleicht kannst du noch ein abstract [hier](http://hamburg.onruby.de/topics/elm-funktionale-frontend-entwicklung/edit) rein schreiben.

**Comment by dennisreimann** [comment]
Ist gemacht, danke für den Hinweis!
