### ISSUE TITLE
Meet up's Austausch/ Zusammenarbeit.

### ISSUE THREAD

**Issue by janz93** [rughh/planning#54]
Hallo ich bin Jan und war beim letzten Meetup dabei.
Ich habe Kontakte zu dem [NYC.rb Meetup](https://www.meetup.com/de-DE/NYC-rb) in New York.
Dort habe ich mit Organisator, bezüglich der Möglichkeiten des Austausches gesprochen.
Er war von dem Gedanken angetan und hat unter anderem auf die kurzfristig live geschaltete Podcast Webseite verwiesen. Des Weiteren wollen wir weitere Möglichkeiten in naher Zukunft das Thema weiter besprechen. (Das Resultat daraus werde ich als Kommentar dem Issue beifügen.)
Ich wollte wissen, ob jemand weitere Vorschläge zu diesem Thema hat?

Hello I'm who was at the last meetup.
I have contact to the  [NYC.rb Meetup](https://www.meetup.com/NYC-rb) in New York.
I was talking to one of the orginisor about the possiblity about exchange of informations.
He liked that idea and meantioned there soon live going podcast website. 
We will have a meeting soon about how in details such a colloboration could look like. (I'll post the results as a comment)
I would like to know if anyone has some ideas regarding that idea?

**Comment by janz93** [comment]
Ebenfalls wäre das meetup in Budapest an einer Zusammenarbeit interessiert.
Hier kam der Vorschlag von live Präsentation. Dies würde natürlich gewisse technische Bedingungen mit sich bringen. (Kamera, Mirkophone, Internetverbindung etc.)

Also the meetup in Budapest is interrested in an Corporation.
One of the organizers suggested to idea of remote presentations. That would mean to have some techinal requirements such as a Carama, Mircophone, internet connection. any one has some other ideas?

**Comment by phoet** [comment]
thank you @janz93 for getting in touch. as i said on the last meetup, in general, we are very much interested in having more exchange between usergroups. (thx @pragtob for coming over from berlin last meetup BTW) 

since we only have very limited time-resources for planning and preparation, we can only consider doing anything when somebody volunteers in setting everything up.

**Comment by janz93** [comment]
I would love to that.

**Comment by PragTob** [comment]
@janz93 wanna come to Berlin and do the recording as well? :P We used to have people doing this, but not for a long time... I think somebody told me they wanted to do it but didn't see them again

**Comment by janz93** [comment]
just to be clear.
I don't have any technical Equipment. 
I just wanted to get in this idea of colloboration going.
On the details in terms of technical things I haven't got a Solution yet.

**Comment by phoet** [comment]
@mlammers maybe xing could be of help here
