### ISSUE TITLE
EuRoKu

### ISSUE THREAD

**Issue by janz93** [rughh/planning#55]
Ich werde dieses Jahr zu [EuRoKu](http://www.euruko2017.org/) nach Budapest fahren.
Mich würde interessieren, ob noch andere Personen dort hinfahren wollen.

**Comment by phoet** [comment]
https://twitter.com/hamburgsync/status/820649024973901825

**Comment by emrox** [comment]
Denke ich werde dabei sein.

**Comment by torasakura** [comment]
wenn es vom datum passt, bin ich auch dabei

**Comment by janz93** [comment]
Die EuRoKu wird 29-30 September 2017 sein.
Sie wird in Budapest stattfinden

**Comment by phoet** [comment]
@janz93 anything else to do here?

**Comment by janz93** [comment]
Good question. I would like to keep this open for a little longer since currently there are no tickets to buy yet. I believe when the ticket selling started it will be more clear to see who is interested in going there and who isn't. As for those who are interested, this issue could be a good starting point for some serious planning.

**Comment by lindtdev** [comment]
Was kosten die Tickets denn so aus Erfahrung? Ich würde grundsätzlich auch gern

**Comment by emrox** [comment]
@lindtdev letztes Jahr kostete das Ticket 65eu

**Comment by lindtdev** [comment]
@emrox Danke. Das ist ja echt extrem günstig

**Comment by lindtdev** [comment]
Also aktuell kosten Flugtickets bei Germanwings 150€ für 28.09-01.10. Ich schau mir das bis Ende des Monats noch an (vielleicht greift ja eine Rabattaktion), glaub aber nicht, dass sie noch billiger werden. Andere Transportmöglichkeiten gibt's ja nicht wirklich?

**Comment by emrox** [comment]
@lindtdev wenn dir lange Busfahrten nichts ausmachen kannst du mit Flixbux fahren. Aber gemessen an der Zeit, die du dann im Bus verbringst, sparst du nicht wirklich was gegenueber dem Flug. Evtl. findet man auch etwas ueber die Mitfahrzentrale?

**Comment by lindtdev** [comment]
Noch mal recherchiert: Es gibt grundsätzlich noch die Möglichkeit, den Nachtzug Hamburg-Wien zu nehmen. Der fährt dann so 12 Stunden von ca 20 Uhr bis 8 Uhr morgens. Kostet aktuell 39€ pro Strecke (weiß nicht, ob das auch für einen Schlafwagen gilt). Von Wien dauert es noch 3 Stunden mit dem Zug nach Budapest. Werde ich mir für die Rückfahrt als Option überlegen.

**Comment by lindtdev** [comment]
Wobei auch die 150€ schon OK vom Geld her sind. In Budapest selbst gibt man ja nicht so viel Geld aus, das passt schon.

**Comment by janz93** [comment]
A heads up! 
One of the organizers of the Euroku said the tickets are going to be on sale soon.

**Comment by janz93** [comment]
Euroku tickets are online

**Comment by lindtdev** [comment]
Das Ticket kostet mit Steuern übrigens 95€. Jan hat mich drauf hingewiesen dass man via Berlin deutlich günstiger nach Budapest kommt, weil dort Ryanair fliegt. Da die Eurowings Tickets in der Zwischenzeit teurer geworden sind, ist Berlin eine Überlegung wert!

**Comment by lotar650** [comment]
Und, wie steht es bei euch? Sitzt jemand mit mir im Eurowings-Flieger am Donnerstag dem 28.09? Zurück komme ich nun Sonntag Abend mit einem Flug aus Wien.

**Comment by lindtdev** [comment]
Und, wie steht es bei euch? Sitzt jemand mit mir im Eurowings-Flieger am Donnerstag dem 28.09? Zurück komme ich nun Sonntag Abend mit einem Flug aus Wien.

Sorry für den anderen Comment, habe vergessen mich aus einem anderen Account auszuloggen :laughing:

**Comment by janz93** [comment]
@lindtdev Ich bin am Donnerstag ebenfalls im Flieger von Berlin aus.
Können uns ja dort schon mal treffen?
