### ISSUE TITLE
Als dev in Kanada / nach Kanada

### ISSUE THREAD

**Issue by titanoboa** [rughh/planning#56]
Nachdem wir ja schon ein paar andere Auswander-Berichte hatten, könnte ich einen zum Thema nach Kanada gehen / in Kanada arbeiten / bei Shopify arbeiten beisteuern, Temperaturen unterhalb von -20 Grad inclusive ;-)

Ich werde zu jsunconf in Hamburg sein, die ist am 25. & 26. März.

Da ihr ja in #52 sowieso gerade über abweichende Termine diskutiert, wie wäre es mit einer Usergroup in zeitlicher Nähe zur jsunconf? Vielleicht nicht gerade Sonntag Abend wenn alle total erschöpft sind, aber grundsätzlich wäre ich terminlich halbwegs flexibel was Tageszeit und Wochentag angeht.

**Comment by phoet** [comment]
gut zu wissen!

**Comment by phoet** [comment]
@titanoboa haben wir irgendwie nicht auf die reihe bekommen. ich schliesse das mal vorläufig
