### ISSUE TITLE
February 2017 Meetup

### ISSUE THREAD

**Issue by phoet** [rughh/planning#57]
Termin: 08.02.2017 19:00
- [x] Location
- [x] [Event anlegen](http://hamburg.onruby.de/admin/)
- [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
- [x] Promo auf Twitter
- [x] [Push-Notification für iOS app senden](http://hamburg.onruby.de/admin/dashboard)
- [x] [Slides anpassen](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)
- [x] [Door Sign anpassen](https://docs.google.com/presentation/d/1IQfnE3TbG3EU5zRnNKdG3kzxdYjT1ryWNWs4WWgpE04/edit?usp=sharing)

**Comment by phoet** [comment]
thx @mlammers for setting us up on short notice at XING 

http://hamburg.onruby.de/events/ruby-usergroup-hamburg-februar-2017

**Comment by janz93** [comment]
@phoet as discussed before and to get the collaboration started. #54 
Would there be a way to record the event?
