### ISSUE TITLE
March Meetup 2017

### ISSUE THREAD

**Issue by phoet** [rughh/planning#59]
Termin: 08.03.2017 19:00
- [x] Location
- [x] [Event anlegen](http://hamburg.onruby.de/admin/)
- [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
- [x] Promo auf Twitter
- [x] [Push-Notification für iOS app senden](http://hamburg.onruby.de/admin/dashboard)
- [x] [Slides anpassen](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)
- [x] [Door Sign anpassen](https://docs.google.com/presentation/d/1IQfnE3TbG3EU5zRnNKdG3kzxdYjT1ryWNWs4WWgpE04/edit?usp=sharing)

**Comment by phoet** [comment]
i created a private contact list here: https://github.com/rughh/logins/issues/2

@filtercake offered to provide a workshop in march https://github.com/rughh/planning/issues/51

**Comment by phoet** [comment]
@halfbyte wanted to talk to mindmatters about a location, if that is possible, you could involve @janz93 there

**Comment by janz93** [comment]
@halfbyte what is that status on mindmatters as location for our next meetup?
Is there anything I can do to help?

**Comment by halfbyte** [comment]
@janz93 Will ask them this week. Hold your horses.

**Comment by janz93** [comment]
@halfbyte Okay thanks for helping me :)
Let me know what I need to do next or I you need any information from me.

**Comment by halfbyte** [comment]
@janz93 mindmatters has agreed on hosting. if you could give me an Email address (just send me an email to jan@krutisch.de), I'll put you in contact with Claudia from mm.

**Comment by janz93** [comment]
@phoet I don't have an iphone device so someone has to sent to push notification.

**Comment by phoet** [comment]
@janz93 there is a link in the (linked) admin interface

<img width="638" alt="screen shot 2017-03-01 at 21 07 42" src="https://cloud.githubusercontent.com/assets/48745/23478937/2c1fe86c-fec3-11e6-9b1a-1d5e7edaba47.png">

so once the event is created an properly hooked up, you click on that link.

**Comment by janz93** [comment]
Ah okay :)

**Comment by janz93** [comment]
How many talks will we have in March.
So Far I counted 2.
#51 and #60 
Will the time be enough for that?

**Comment by phoet** [comment]
i think it's a good mix, i would not look for more though. i would start with the workshop and then try to keep the timebox so it won't be too long.

**Comment by janz93** [comment]
Okay then i will create the event like that.

**Comment by janz93** [comment]
@phoet Could you overview the event to make sure it's okay

**Comment by phoet** [comment]
if you click on those links, you can pick one of the talks that are [proposed in the undone-section of the website](http://hamburg.onruby.de/#undone)

<img width="660" alt="screen shot 2017-03-01 at 21 32 52" src="https://cloud.githubusercontent.com/assets/48745/23480003/acfa8e30-fec6-11e6-8495-dae7dbaf05d2.png">

**Comment by janz93** [comment]
Okay I have added them

**Comment by janz93** [comment]
@phoet The door sign I'm just bringing printed out to the meetup I am assuming

**Comment by phoet** [comment]
@janz93 that's just convenience for the host. i think you don't need to bring that to mm

**Comment by janz93** [comment]
Okay so then I would just add the wifi password to the presentation on wednessday and everything should be done

**Comment by phoet** [comment]
@janz93 sounds perfekt

**Comment by JoschkaSchulz** [comment]
Is there a default door sign? Then maybe I can print it tomorrow here in the office and put it early on the doors.

**Comment by phoet** [comment]
@JoschkaSchulz you can use the one linked in the description https://docs.google.com/presentation/d/1IQfnE3TbG3EU5zRnNKdG3kzxdYjT1ryWNWs4WWgpE04/edit#slide=id.p

**Comment by erotte** [comment]
Hey @janz93,  ich habe gehört du kommst aus Bremen? Ich auch, fahre heute Abend mit dem Pkw nach HH.
Leider habe ich keine andere Kontaktmöglichkeit gefunden, ich hoffe, das hier kommt bei Dir an.

**Comment by janz93** [comment]
Moin ja stimmt.
Ich habe dir eine Email geschickt.
