### ISSUE TITLE
Ruby-Golf-Event

### ISSUE THREAD

**Issue by phoet** [rughh/planning#6]
Die Gewinner der letzten Ruby-Golf-Veranstaltung @tbk303 und @tammofreese sind theoretisch in der Pflicht die Weitergabe des Wanderpokals durch Austragen einer Nachfolgeveranstaltung zu gewährleisten. Da sie es im letzten Jahr versäumt haben, möchte ich nun noch einmal höflichst an die Einhaltung dieser ehrenhaften Aufgabe erinnern.

Hochachtungsvoll,
Klaus Schröder

**Comment by nesQuick** [comment]
:trophy: :soon: :bust_in_silhouette:

**Comment by rubiii** [comment]
@tbk303 @tammofreese bei nichteinhaltung der fristen sehen die regeln übrigens vor, dass der pokal zur not auch ohne das amtierende gewinnerteam verspielt werden kann! nur so ;)

**Comment by janz93** [comment]
Wann wird denn das nächste Ruby-Golf-Tunier ausgetragen werden ?

**Comment by phoet** [comment]
@janz93 wenn es jemand schafft eins zu organisieren

**Comment by janz93** [comment]
Ich kann das gerne mal in die Hand nehmen.
Was sind denn auflagen dazu?

**Comment by janz93** [comment]
ping @phoet

**Comment by phoet** [comment]
https://www.sitepoint.com/ruby-golf/

Termin finden und Organisation und ab dafür.

**Comment by janz93** [comment]
perfect ich werde mich da mal Informieren und werde den Termin dann im issue bekannt geben.

**Comment by janz93** [comment]
Für wenn soll das Event alles sein?
Für die Orga nur oder jeder der Will?

**Comment by salzig** [comment]
@janz93 in der Vergangenheit war es für alle :)

**Comment by janz93** [comment]
@salzig okay dann werde ich mir mal etwas überlegen

**Comment by phoet** [comment]
also der @tbk303 hat sich nicht ganz abgeneigt gezeigt doch noch mal was mitzuhelfen.

und hier der reminder wofür es sich zu kämpfen lohnt!

![img_20170914_170608](https://user-images.githubusercontent.com/48745/30437622-5a289b5e-996f-11e7-80eb-1b32ef048f9b.jpg)

**Comment by janz93** [comment]
@phoet @tbk303 Die Idee wäre es vielleicht an einem Freitag Nachmittag und Abend zu machen.
Dazu was zu Essen und Getränke. Was haltet ihr davon?

**Comment by phoet** [comment]
ich schließe das vorerst. vielleicht hat zukünftig jemand lust es zu organisieren.
