### ISSUE TITLE
Talk: What I learned from Michael Jackson about diagrams in software development.

### ISSUE THREAD

**Issue by handylearn** [rughh/planning#60]
Ich habe einen Angebot für einen Talk.
http://hamburg.onruby.de/topics/what-i-learned-from-michael-jackson-about-diagrams-in-software-development
Ich habe den Talk schon mal firmenintern gehalten, da waren es 45 Minuten.

Würde thematisch zu den Sketch-Talk passen, und 8 März würde mir auch passen.

**Comment by phoet** [comment]
klingt gut! wir halten das Mal so fest

**Comment by phoet** [comment]
@handylearn kannst du uns deine präse online zur verfügung stellen?

**Comment by janz93** [comment]
@phoet Ist glaube ich durch Lizenzgründen nicht möglich.
Korrigiere mich wenn ich falsch liege @handylearn
