### ISSUE TITLE
Deleted Topic

### ISSUE THREAD

**Issue by janz93** [rughh/planning#62]
I have deleted this following event after misconfiguration of march event.
"Formatting image previews for social media sharing" from Gerrit @Study.EU

![image](https://cloud.githubusercontent.com/assets/5300559/23480369/fa1ae3b2-fec7-11e6-94ca-70d95211b75c.png)

**Comment by phoet** [comment]
well, instead of deleting it, you could have removed it from the event

<img width="1317" alt="screen shot 2017-03-01 at 21 54 23" src="https://cloud.githubusercontent.com/assets/48745/23480839/ae438cb2-fec9-11e6-9ad3-3004fdfe5649.png">

i think it won't hurt that it's gone

**Comment by janz93** [comment]
Oh my bad.
Sorry I just missed that.
I'll try to talk to the person at the meetup again and ask him to readd the topic.
Thanks for explaining it to me.
