### ISSUE TITLE
Sticker buying

### ISSUE THREAD

**Issue by janz93** [rughh/planning#63]
You can still buy the ruby sticker on the github readme page.
As discussed last meetup @phoet no money can be earned with the meetup.
[Sticker link](https://www.stickermule.com/marketplace/2284-hamburg-ruby-usergroup)
Of course now the money goes else where.
I'm wondering where does the money go and is that fine to advertise with the sticker from the meetup from the law perspective.

**Comment by phoet** [comment]
ask @nesQuick who was so nice to create them from our logo

<img width="695" alt="screen shot 2017-03-02 at 22 27 03" src="https://cloud.githubusercontent.com/assets/48745/23527743/6d865302-ff97-11e6-8b6e-35b6e346a15b.png">

**Comment by janz93** [comment]
@phoet okay will do.

**Comment by nesQuick** [comment]
> Of course now the money goes else where.

lol

![screen shot 2017-03-02 at 23 01 58](https://cloud.githubusercontent.com/assets/584259/23529042/511e4cd8-ff9c-11e6-8a9f-5e21054523bd.png)

**Comment by janz93** [comment]
@nesQuick okay I really like the design.
@phoet I was just wondering if there would be a way to have it presenter like adding it onto the website or meantioning it at the meetup.

**Comment by phoet** [comment]
the last time we did a group order asking over twitter

**Comment by janz93** [comment]
Okay yes something like that would be a nice thing where I would be up for.
Maybe in combination of an event it could be a great addition as well

**Comment by phoet** [comment]
@janz93 well, as the organizer of the next event, you are free to add this to your intro slides to whatever you feel is appropriate.

**Comment by phoet** [comment]
@nesQuick you faked the screenshot, didn't you? in reality you are earning a shit ton of money with it!

**Comment by nesQuick** [comment]
@phoet yeah. The truth is, that I can make a living out of selling stickers 🕶

**Comment by phoet** [comment]
@janz93 feel free to ask around tomorrow if you are still interested in buying a bunch of stickers

**Comment by salzig** [comment]
btw, who is owner of the logo? Would it be possible to use it for T-Shirts/Hoodies? SVG or other vector format available?

**Comment by phoet** [comment]
It's not explicit, but I think it's creative commons and you can do with it what you want like everything from us in this repo
