### ISSUE TITLE
Bilder vom März Meetup post

### ISSUE THREAD

**Issue by janz93** [rughh/planning#64]
Moin Stefanie von mindmatter waren so freundlich und habt Bilder vom Event gemacht.
Ich würde diese gern in einem Twitter post und ggf. auch auf der Webseite bei dem entsprechendem Event hochladen.
Textlich könnt ihr mir da gerne helfen, da ich nicht so wortgewannt in solchen Angelegenheiten bin.

**Comment by phoet** [comment]
hast du die bilder schon? ich würde sie sonst als Dropbox ordner oder
dergleichen zur Verfügung stellen.

Jan Zaydowicz <notifications@github.com> schrieb am Do., 9. März 2017,
21:52:

**Comment by janz93** [comment]
Ja sind unter diesem Link zu erreichen.
https://we.tl/qJg6Dr4Ehs
Muss allerdings mit dem Copyright notice von mindmatter versehen werden.

**Comment by janz93** [comment]
Wie schon gesagt bin ich nicht so ganz wortgewannt. Dennoch könnte ich mir den folgenden text für den Tweet an sich vorstellen.
Dazu würde ich die folgenden Bilder einsetzten sollen und auch vielleicht dafür eine kleine Bildunterschrift nehmen. (die folgenden Bilder sind nur thumbnails an den orginalen)

## Tweet text
Wer das Letzte Meetup verpasst hat.
Hier sind ein paar ein Blicke:

## Bilder
![Danke an mindmatters](https://cloud.githubusercontent.com/assets/5300559/23899475/950a896c-08b5-11e7-9fb8-c345064a5f7a.jpg)
Danke an mindmatters

![2_tn](https://cloud.githubusercontent.com/assets/5300559/23899469/94f4bb8c-08b5-11e7-80f1-47fc0cb28a40.jpg)
Hilfe zum Erstellen von verständlichen logik Diagrammen

![3_tn](https://cloud.githubusercontent.com/assets/5300559/23899470/94f69614-08b5-11e7-82d2-844eeb5a1703.jpg)
Der Weg zum einfachem Visualisieren von Meeting Informationen

![4_tn](https://cloud.githubusercontent.com/assets/5300559/23899471/94f93e1e-08b5-11e7-9407-6a5ef46df250.jpg)
Nicht nur zuhören sondern selbst aktiv werden

![5_tn](https://cloud.githubusercontent.com/assets/5300559/23899474/94fcce9e-08b5-11e7-8814-b0c1646d9629.jpg)
Jeder Anfang ist schwer

![6_tn](https://cloud.githubusercontent.com/assets/5300559/23899472/94faf678-08b5-11e7-8d0a-d7d4685f294f.jpg)
Resultate nach einer Stunde workshop

![7_tn](https://cloud.githubusercontent.com/assets/5300559/23899473/94fb3840-08b5-11e7-9a66-1dcab505c713.jpg)
Gemütlicher Austausch bei Bier und Chips

**Comment by phoet** [comment]
hm, nuja, man könnte eine wiki-seite anlegen und dann dort das copyright angeben? ¯\_(ツ)_/¯`

**Comment by janz93** [comment]
Ja also ich wollte die Fotos erstmal auf twitter veröffentlichen und dort kann man das ja entsprechend im Bild mit eintragen.
Was haltet ihr den von den Texten?

**Comment by janz93** [comment]
Ich würde versuchen am Wochenende den Tweet fertig zustellen.
Also falls bis Sonntag keine einwände kommen würde ich den Tweet so posten.

**Comment by janz93** [comment]
https://twitter.com/hamburgsync/status/844484558275915776
