### ISSUE TITLE
April Meetup 2017

### ISSUE THREAD

**Issue by janz93** [rughh/planning#66]
Termin: 12.04.2017 19:00

- [x] Location
- [x] [Event anlegen](http://hamburg.onruby.de/admin/)
- [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
- [x] Promo auf Twitter
- [x] [Push-Notification für iOS app senden](http://hamburg.onruby.de/admin/dashboard)
- [ ] [Slides anpassen](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)
- [ ] [Door Sign anpassen](https://docs.google.com/presentation/d/1IQfnE3TbG3EU5zRnNKdG3kzxdYjT1ryWNWs4WWgpE04/edit?usp=sharing)

**Comment by janz93** [comment]
Ich bin gerade im Abi-stress und könnte zwar das Meetup wieder zu moderieren, allerdings kann ich mich nicht um eine Location kümmern.

**Comment by phoet** [comment]
@janz93 kein problem, ich kann mich um das nächste event kümmern

**Comment by phoet** [comment]
XING has offered to host it.

**Comment by phoet** [comment]
@tobstarr thx for hosting at dynport. you moved to abc strasse, is that correct?

**Comment by tobstarr** [comment]
yes, address is correct.

**Comment by halfbyte** [comment]
@phoet Meinst Du, ich kann einen 5-Minuten-Was-genau-macht-Depfu talk reinschmuggeln? Ich hab auch Discount-Codes UND BUTTONS dabei :)

**Comment by janz93** [comment]
Ich werde es erst gegen viertel vor 8 ca schaffen. Somit kann ich heute auch nicht das meetup moderieren wie angeboten

**Comment by phoet** [comment]
@janz93 null problemo, mache ich
