### ISSUE TITLE
Job postings

### ISSUE THREAD

**Issue by janz93** [rughh/planning#67]
Ich habe von einem Recruiter ein Jobangebot bekommen.
Ich kann in diesem Zeitraum nicht und würde die Anfrage somit gerne auf die Meetup Seite bringen.
Im Moment sind ja konkrette Jobanfragen gepostet. Da diese Anfrage über einen Recruiter gehe würde, wollte ich mal wissen ob dies ein Problem wäre.

**Comment by phoet** [comment]
wenn du eine konkrete stelle in hamburg hast und es dafür eine verlinkbare stellenanzeige online gibt, dann kannst du die gerne einstellen.

bitte auf keinen fall recruitern eine plattform bieten. dann springen uns die user an den hals.

**Comment by janz93** [comment]
Okay verstanden 👍
