### ISSUE TITLE
Kann ich mithelfen?

### ISSUE THREAD

**Issue by lindtdev** [rughh/planning#69]
Moin liebes Orga Team, braucht ihr beim Ausrichten der Meetups Hilfe und was kann ich tun?

Liebe Grüße, Irina

**Comment by janz93** [comment]
@phoet Hier ist die angekündigte Hilfe.

**Comment by phoet** [comment]
@lindtdev super! vielen dank schon mal für dein angebot!

hättest du lust uns dabei zu helfen die juni usergroup zu organisieren? mai ist vielleicht schon zu nah dran.

**Comment by lindtdev** [comment]
Juni ist super!

**Comment by phoet** [comment]
gut, dann wäre es super wenn du zur nächsten usergroup kommst, dann können wir das einmal durchsprechen.

**Comment by phoet** [comment]
@lindtdev morgen dann alles weitere
