### ISSUE TITLE
Meeting Mar 2015

### ISSUE THREAD

**Issue by titanoboa** [rughh/planning#7]
* [x] Location
* [x] Talks / Format
* [x] Promo auf Twitter
* [x] Push-Notification für iOS app senden
* [x] [Slides anpassen](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)

Thoughtworks würde uns ggf. beherbergen (Absprache mit @lieblingswelt)
Ggf. kann @lieblingswelt auch einen Vortrag anbieten (sollte noch abgesprochen werden)

**Comment by titanoboa** [comment]
Ausserdem: @hmans zu Lua (quasi schon zugesagt)

**Comment by phoet** [comment]
dann ping ich den @skade hier gleich noch mal. termin wäre dann der 11. märz

falls thoughtworks net will würden wir sonst auch jimdoen

**Comment by titanoboa** [comment]
So weit ich weiss sind wir bei thoughtworks schon eingeplant, oder @lieblingswelt?

**Comment by lieblingswelt** [comment]
Jap, Ihr seid bei ThoughtWorks eingetragen!!

**Comment by rubiii** [comment]
@lieblingswelt kommst du dann auch?

**Comment by lieblingswelt** [comment]
@rubiii jap in jedem Fall, endlich mal wieder!

**Comment by rubiii** [comment]
@lieblingswelt :ok_hand: :smiley_cat:

**Comment by phoet** [comment]
@titanoboa machst du eigentlich für dieses meetup die orga? wir haben es glaube ich beim letzten mal verschusselt fürs nächste mal was festzulegen... zur not kann ich auch gerne wieder was machen.

**Comment by titanoboa** [comment]
Ich kann das machen

dabei hattest du doch in #8   diesen wundervollen Zufallsgenerator  ;-)

**Comment by phoet** [comment]
Kam leider kein Feedback zu vom @halfbyte
Am 21.02.2015 16:17 schrieb "titanoboa" <notifications@github.com>:

**Comment by titanoboa** [comment]
Ich mach das, kein Problem.
@lieblingswelt macht einen Vortrag zu 'pixelated - easy to use encrypted email with federated hosting' und was tw da so macht

@hmans geht das klar mit deinem Lua talk?

**Comment by halfbyte** [comment]
Boah, das war doch schon fast alles fertig organisiert, deswegen hab ich das erst mal liegen gelassen :)

**Comment by phoet** [comment]
Zorri jan

**Comment by halfbyte** [comment]
Kein Problem, ich reiss mich auch nicht drum. Ist ja eh nicht so viel zu tun.

**Comment by phoet** [comment]
Fatfingering my android...  Ich lass es lieber mit dem schreiben heute

**Comment by phoet** [comment]
@halfbyte ich frug nur weil ich nämlich gar net weiß wer @lieblingswelt ist :question: :exclamation: sei mir net bööös :heart: :green_heart: :blue_heart:

**Comment by titanoboa** [comment]
Ich habe eh nur so bereitwillig gesagt ich machs weil eh nicht mehr so viel zu tun ist 

On February 21, 2015 7:34:17 PM GMT+01:00, "Peter Schröder" <notifications@github.com> wrote:
>@halfbyte ich frug nur weil ich nämlich gar net weiß wer @lieblingswelt
>ist :question: :exclamation: sei mir net bööös :heart: :green_heart:
>:blue_heart: 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/rughh/planning/issues/7#issuecomment-75385343

-- 
Sent from my mobile phone

**Comment by titanoboa** [comment]
@hmans wird uns was zu Lua erzählen

Möchte denn @skade auch im März vorbeikommen? Oder lieber erst in einem späteren Monat? Wir würden ja schon gern noch was über Rust lernen...

**Comment by rubiii** [comment]
@phoet :weary:

**Comment by skade** [comment]
@titanoboa Ich hab jetzt heute mal meinen Terminplan gemacht. Diesen Monat klappt absolut nicht, wegen einem Kundentermin auf dem Tag. Für den April kann ich aber direkt zusagen.

**Comment by phoet** [comment]
@skade cool, dann buchen wir dich mal für den april fest ein!

**Comment by phoet** [comment]
der @aemkei hat uns gebeten ein wenig werbung für die JSUnconf.eu zu machen. hab schon mal den gutschein-code mit in die slides gepackt, damit wir das nicht vergessen

**Comment by titanoboa** [comment]
Wieso steht da eigentlich 'Facebook' unter den ToDos? Haben wir ne Facebookseite von der ich nix weiß?

**Comment by phoet** [comment]
Ich glaube da war ein Fragezeichen dran? Ich wollte niemanden ausschließen.
vielleicht gibt es Leute die das noch benutzen, aus Gründen...
Am 09.03.2015 10:59 schrieb "titanoboa" <notifications@github.com>:

**Comment by titanoboa** [comment]
Ah ok, dann hatte ich das falsch verstanden, umso besser
