### ISSUE TITLE
Hanami talk in June

### ISSUE THREAD

**Issue by cllns** [rughh/planning#70]
Hi everyone!

I'm an organizer for Boulder Ruby (in Colorado, US). I'm going to spend most of my June in Hamburg, and I'd love to give a talk about [Hanami](http://hanamirb.org) while I'm there. I'm a core team member for Hanami, and I gave a talk here in January about it (which I'd revise for this talk). That one was 30 minutes plus Q&A, so that's probably the best length. (I welcome questions during the talk, as well as at the end).

It looks like the date would be June 14?

I'd only be able to give the talk in English, but happy to take questions in German if others translate.  Mein Deutsch ist... nicht toll 😄

**Comment by phoet** [comment]
hi @cllns 

that sounds great, we will happily reserve a slot for you.

english only is no problem at all.

if you have any further questions feel free to ask them in this issue, i'll directly create on for the june meetup, so that you can follow along how the organisation is doing.

**Comment by lindtdev** [comment]
Hi @cllns 
as the June meetup draws near hamburg.onruby.de/events/ruby-usergroup-hamburg-june-2017 I wanted to ask if you are still planning to give your talk, we'd love to have you.

**Comment by cllns** [comment]
@lindtdev Yes! on my calendar, i'll be there 👍

**Comment by lindtdev** [comment]
@cllns Great! Looking forward to your talk

**Comment by lindtdev** [comment]
Hi Sean, could you login at our meetup page (hamburg.onruby.de) with either your Github or your Twitter? This creates "your" user in our system, so I can assign that user to your topic. Right now I had to use my user for that http://hamburg.onruby.de/events/ruby-usergroup-hamburg-june-2017

**Comment by cllns** [comment]
Thanks for the opportunity to speak last night! It was a great time.

I didn't see the request to register on the onruby.de site until now (and Jan asked me last night). Just did that 👍

**Comment by phoet** [comment]
@cllns thx for registering. i linked your account to the talk. is there a way so that you could share your slides with us? that would be great.
