### ISSUE TITLE
June meetup

### ISSUE THREAD

**Issue by phoet** [rughh/planning#71]
14.06.2017 19:00

- [x] Location
- [x] [Event anlegen](http://hamburg.onruby.de/admin/)
- [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
- [x] Promo auf Twitter
- [x] [Push-Notification für iOS app senden](http://hamburg.onruby.de/admin/dashboard)
- [x] [Slides anpassen](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)
- [ ] [Door Sign anpassen](https://docs.google.com/presentation/d/1IQfnE3TbG3EU5zRnNKdG3kzxdYjT1ryWNWs4WWgpE04/edit?usp=sharing)
- [ ] [Gather slide-decks and other material](http://hamburg.onruby.de/admin/materials/new)

**Comment by phoet** [comment]
we already have one talk #70

**Comment by phoet** [comment]
@lindtdev will be helping with the organization

**Comment by phoet** [comment]
TODOs for @lindtdev 

pre-event

* [ ] join the RUGHH organization
* [ ] login to our twitter acount etc https://github.com/rughh/logins
* [ ] get in contact with sum.cumo for hosting the event https://twitter.com/sumcumo/status/849625832347840512
* [ ] recruit (new,) additional speakers for the event
* [ ] keep this issue up to date

on-event

* [ ] act as a "community staff"
* [ ] communicate & organize with the host
* [ ] communicate & organize with speakers
* [ ] answer questions / resolve issues with attendees
* [ ] time manage the event (when to start, breaks, talk duration)
* [ ] present introduction (this can optionally be done by the host or another organizer)

to be continued

**Comment by lindtdev** [comment]
Habe mit Dustin von GuJ abgesprochen dass ich mir am Mittwoch ihre Räumlichkeiten ansehe. Dann würde ein Talk von seinem Mitarbeiter Manuel da auch gut passen. Dustin selbst hat noch ein anderes Thema in den Raum gestellt, "Zusammenarbeit mit Entwicklern". Finde ich grundsätzlich ganz spannend. Ich werde noch mal am Mittwoch nach Details dazu fragen.

**Comment by phoet** [comment]
@lindtdev guck bitte mal in deine emails, du hast eine einladung in die rughh github organization

**Comment by lindtdev** [comment]
Oh :woman_facepalming: erledigt

**Comment by phoet** [comment]
@lindtdev kannst du dich bitte einmal auf hamburg.onruby.de mit deinem github account anmelden? dann kann ich dich als organizer eintragen.

**Comment by lindtdev** [comment]
Done

**Comment by lindtdev** [comment]
Also, ich war heute da, sieht alles gut aus. Außer dass die Klingel nicht funktioniert und man durch einen Innenhof rein muss: da werde ich wahrscheinlich etwas früher ankommen und schauen, dass da ein Zettel mit Anweisungen neben der Klingel klebt. Dustin will mir bis Ende der Woche mitteilen, ob sie am 14. Juni den Raum frei haben. Ob und wie viele Talks sie machen wollen, will er dann nächste Woche sagen (sie hatten ja gleich zwei Themen vorgeschlagen).

**Comment by phoet** [comment]
@lindtdev super!

**Comment by lindtdev** [comment]
Dustin fragt, ob es möglich ist, das Meetup eine Woche später zu veranstalten, weil er in dieser Zeit beruflich reisen muss. Will aber auch versuchen, seine Termine zu verlegen, falls es nicht anders geht. Habe erst mal zurückgefragt, ob er am 7. Juni kann. Was sagt ihr? Wie ist es beim Meetup üblich in solchen Fällen?

**Comment by phoet** [comment]
@lindtdev in der regel versuchen wir dann eine andere location zu finden.

ausweichtermine überschneiden sich häufig mit anderen usergroups oder sonstigen terminen.

ich würde darüber nur nachdenken, wenn wir sonst auf gar keinen fall eine usergroup stattfinden lasen können.

falls das ohne dustin nicht geht, würde ich mit sum.cumo kontakt aufnehmen, die hatten auch angeboten eine usergroup zu hosten.

**Comment by lindtdev** [comment]
Dustin hat mir jetzt die Location "Greenhouse"/Pianofabrik am Schulterblatt für den 14. Juni zugesagt. Er wird nicht dabei sein können, aber seine Mitarbeiter übernehmen das dann. Wahrscheinlich wird dann Manuel seinen Talk zum Thema "JSON APIs" halten. 
Ich werde dann gleich sum.cumo kontaktieren, ob sie den Julitermin übernehmen möchten.

**Comment by phoet** [comment]
@lindtdev das wäre mega!

**Comment by janz93** [comment]
@lindtdev One the next meetup I also would like to say a few words regarding the Euroku and the collaboration between meetups

**Comment by phoet** [comment]
@lindtdev i habe dich als administrator auf onruby hinzugefügt. du kannst jetzt schon das nächste event anlegen, talks verlinken etc (siehe todos oben). http://hamburg.onruby.de/admin/dashboard 

in diesem issue finden sich noch diverse benutzungsbeispiele https://github.com/rughh/planning/issues/59

**Comment by phoet** [comment]
@lindtdev jetzt wäre der perfekte zeitpunkt alle talks beisammen zu haben, auf der website zu verlinken und schon mal werbung für nächste woche mittwoch zu machen. das ist üblicher weise der moment, den wir sonst immer verschlafen 😸

**Comment by fsmanuel** [comment]
@lindtdev I'll post my talk tonight at http://hamburg.onruby.de

**Comment by lindtdev** [comment]
@fsmanuel great!

**Comment by lindtdev** [comment]
Ich wollte die Topics selbst anlegen, bin aber am Erstellen des zugehörigen Users gescheitert. Muss jeder seinen User selbst erstellen?

**Comment by phoet** [comment]
ja, sonst wird es kompliziert mit der oauth Zuordnung. wahlweise deinen
user nehmen und später ändern. oder erstmal in der event Beschreibung
hinterlegen.

Irina Lindt <notifications@github.com> schrieb am Fr., 9. Juni 2017, 11:57:

**Comment by fsmanuel** [comment]
Hier mein Eintrag: http://hamburg.onruby.de/topics/providing-a-json-api-spec-compliant-api

**Comment by fsmanuel** [comment]
Slides: https://rawgit.com/fsmanuel/slides/master/json-api/index.html#/

**Comment by adamniedzielski** [comment]
My slides: https://speakerdeck.com/adamniedzielski/boring-ruby-code-1

**Comment by janz93** [comment]
@adamniedzielski Thanks
