### ISSUE TITLE
Providing a JSON API spec compliant API

### ISSUE THREAD

**Issue by janz93** [rughh/planning#72]
@fsmanuel

**Comment by janz93** [comment]
Talk about json APIs

**Comment by fsmanuel** [comment]
I'll add a title and a short description this week.

**Comment by janz93** [comment]
perfect 👍 
Also add the topic on our [website](http://hamburg.onruby.de/topics/new?) as well.

**Comment by lindtdev** [comment]
I'll update our meetup page once Manuel posts his topic title+description here.

**Comment by janz93** [comment]
That works too :)

**Comment by lindtdev** [comment]
Hi @fsmanuel short reminder about that title :)

**Comment by lindtdev** [comment]
Hi @fsmanuel what language is your talk in? Would it be your problem for you to give it in English? We'll probably have some English speakers at this meetup

**Comment by fsmanuel** [comment]
@lindtdev will be english.

@janz93 can you change the issue to 'Providing a JSON API spec compliant API' and maybe add the link http://hamburg.onruby.de/topics/providing-a-json-api-spec-compliant-api for reference?
