### ISSUE TITLE
Talk Thema "Zusammenarbeit mit Entwicklern"

### ISSUE THREAD

**Issue by lindtdev** [rughh/planning#74]
Es geht um die Perspektive von jemand aus einem anderen Bereich, der mit Entwicklern zusammenarbeitet. Den Talk würde vermutlich Dustin Bartels halten; ich frage ihn am Mittwoch noch mal nach Details.

**Comment by phoet** [comment]
@lindtdev ist das hier noch relevant? wenn ich das richtig verstanden habe, dann hätte dustin das im greenhaus erzählt, oder?

**Comment by lindtdev** [comment]
Ja, aber wir sind gerade im Gespräch dass er das bei shipcloud macht

**Comment by phoet** [comment]
supi

**Comment by lindtdev** [comment]
Dustin hat sich (trotz Nachfragen) nicht mehr bei mir gemeldet, ich schließe daher.
