### ISSUE TITLE
Location for September

### ISSUE THREAD

**Issue by phoet** [rughh/planning#76]
SumCumo offered to host in September. This Issue is just a reminder:

https://twitter.com/sumcumo/status/870546897425113088

**Comment by andywenk** [comment]
super gut - wir freuen uns drauf!

**Comment by janz93** [comment]
Korrekt

**Comment by lindtdev** [comment]
Ich bin an diesem Termin im Urlaub, werde aber im Voraus wie immer mithelfen,

**Comment by andywenk** [comment]
Hey all,

ich war drei Wochen im Urlaub und wollte nur nochmal kurz bestätigen, dass wir am Start sind wie geplant.

LG

Andy

**Comment by janz93** [comment]
Sehr gut 👍
