### ISSUE TITLE
coc

### ISSUE THREAD

**Issue by phoet** [rughh/planning#77]
Irina and Jan should back the CoC berlin

**Comment by phoet** [comment]
for reference https://github.com/rubyberlin/code-of-conduct/pull/18

**Comment by lindtdev** [comment]
Should we take Kerstin's name out of the supporters.json or leave it there?

**Comment by phoet** [comment]
we can keep her there

**Comment by lindtdev** [comment]
done https://github.com/rubyberlin/code-of-conduct/pull/130

**Comment by phoet** [comment]
👍  thx!
