### ISSUE TITLE
Timebox

### ISSUE THREAD

**Issue by titanoboa** [rughh/planning#8]
@phoet schrieb bzgl. Februar: 
> Da wir unsere timeboxen heute sehr überzogen haben und das in der Vergangenheit häufiger passiert ist würde ich gerne was dagegen machen beim nächsten Event. Meinungen?

**Comment by titanoboa** [comment]
:+1: 

Aber was sind denn unsere Timeboxen? 
Ich glaub die haben wir so oft überzogen dass mir nicht klar ist was eigentlich angedacht ist. Ich sage meist 'ca. ne halbe Stunde ist ganz gut' wenn mich jemand fragt, aber das ist nix weiter als individuelles Bauchgefühl. Viele Talks der jüngeren Vergangenheit waren definitv länger.

**Comment by phoet** [comment]
mir würde folgendes vorschweben:

wir vereinbaren mit den vortragenden eine entsprechende timebox. sagen wir mal 15, 30, 60 minuten und versuchen dann entsprechend während des vortrags darauf hinzuweisen wieviel zeit noch zur verfügung steht.

im prinzip finde ich es nicht schlecht wenn die vorträge länger werden wenn es für das publikum interessant ist. allerdings möchte ich den leuten, die vielleicht für das zweite thema gekommen sind nicht die möglichkeit verbauen dies auch noch zu hören, wenn sie evtl. früher gehen müssen.

wenn wir eine technische lösung dafür finden (z.b. streaming oder recording) dann wäre das für mich eher zu vernachlässigen.

**Comment by phoet** [comment]
ping @rughh/owners

**Comment by rubiii** [comment]
was @phoet sagt. vorher absprechen find ich gut.

**Comment by halfbyte** [comment]
Ich hätte gestern bei beiden auch schon früher eingehakt, hatte aber den Eindruck das alle recht gebannt waren, aber vielleicht sind die auch alle nur hanseatisch höflich. Im Zweifel kann man das ja aber auch fragen. Also das Publikum, in dem Moment wo die Timebox vorbei ist.

Wobei gestern so viele direkt nach dem 2. Talk gegangen sind, dass die Einschätzung von mir vielleicht schlicht falsch ist.

Was wir auch machen sollten: Konkret bestimmen, wer für die Einhaltung zuständig ist. Ich würde sagen, im Zweifel diejenige/derjenige die/der das Treffen organisiert hat. Zusätzlich könnte ich mir vorstellen, den Vortragenden einfach 'ne Ipad-Uhr oder sowas vor die füße zu stellen. Ich hab zwar auch selber immer 'ne Uhr mitlaufen als Speaker, aber so ein expliziter Hinweis aus der Orga hilft da glaube ich doch schon noch mal.

Zu den Zeiten: Ich mag ja 30 Minuten Talks, wenn es ein richtig komplexes Thema ist, kann man auch mal 45 oder 60 draus machen, insbesondere wenn es der einzige Talk ist (wobei wir das ja schon lange nicht mehr gehabt haben).

Beim nächsten Mal betatesten, oder?

**Comment by phoet** [comment]
Publikum fragen finde ich nicht so schön, dass kann einen faden Beigeschmack für den Speaker geben. Ich würde dann eher darauf hinweisen, dass man bei Interesse natürlich mit dem Speaker noch mal das Thema auf einer späteren RUGHH vertiefen kann.

Der Organisator sollte die Timebox mit den Speakern abklären und dann auch die "Einhaltung" regeln. 5 oder 10 Minuten überziehen finde ich nicht schlimm, es muss nur ersichtlich sein, dass sich der Vortrag dem Ende zuneigt. Vielleicht können wir mit einfachen "noch 10 Minuten" Zetteln anfangen? Irgendwas sollten wir ausprobieren.

**Comment by titanoboa** [comment]
:+1: für verbindliche Absprachen mit den Vortragenden, Uhr oder 10-Minuten Zettel, und Einhaltung durchsetzen (natürlich nicht zu kleinlich, paar Minuten länger geht immer).

:-1: für Publikum fragen. Irgendwer will immer mehr sehen, insofern hilft das nicht. Ausserdem ist es komisch für die Speaker.

Generell bin ich eher für kürzere Sachen 30 Minuten statt 60, zumindest wenn es mehrere Talks gibt. Ganz egal ob wir streaming haben oder nicht. Es geht mir nicht darum, dass Leute aus Zeitmangel nen Talk verpassen - ein stream ist eh keine richtiger Ersatz für live dabeisein. Es sollte m.E. nach eher noch Zeit zum Fragen stellen ung Quatschen geben, ohne das dann Mitternacht wird.

Bisher wäre ich einfach nicht 'dazwischengegangen', da es bisher unüblich war. Selbst bei dem Typen, der dieses Zwiegespräch mit Hendrik im Januar hatte, gabs ja keine Anstalten das einzudämmen. 
Was mir den Eindruck vermittelt hat, dass die Art von Eingreifen unerwünscht wäre. (Habs im Januar dann trotzdem gemacht, als es echt unerträglich wurde, da war mir dann egal wie Ihr das findet, das ging einfach nicht mehr.)

**Comment by nesQuick** [comment]
Pro timebox, die vorher dem speaker klar kommuniziert ist, es wird nach ablauf der timebox dem speaker ein zeichen gegeben.Vorher finde ich persönlich immer derbe nervig, da ich mein timing selbst im griff habe. Andere ja aber manchmal auch nicht, dann gibts noch 10 minuten karenz zuschlag. Und dann einen harten abbruch durch die orga. Das alles sollte mmn. der machen, der das treffen organisiert. Um das evtl auch dem publikum zu kommunizieren geht evtl auch eine für alle anderen (evtl auch sogar nicht für den speaker) sichtbare Uhr.

**Comment by phoet** [comment]
jutjut, da sind wir ja alle quasi d'accord. wir haben natürlich gestern vergessen auszuklabüstern wer das nächste treffen organisiert... mein pseudo-random-generator hat folgendes ausgespuckt:

```
irb(main):002:0> %w(jan peter).shuffle.first
=> "jan"
```

:trollface:

**Comment by rubiii** [comment]
LOL das solltest du unbedingt ein gem draus machen!
