### ISSUE TITLE
maintaining the hamburg@onruby.de email address

### ISSUE THREAD

**Issue by phoet** [rughh/planning#80]
would be great if either @lindtdev or @janz93 could take care of checking and answering emails sent to out e-mail address. credentials for gmail can be found here https://github.com/rughh/logins/blob/master/README.md

usually there is about 1 email per week that needs some kind of attention.

**Comment by janz93** [comment]
@phoet there is a 2auth implemented so it would probably the best when we could meet up and do it together to have the second verification also checked

**Comment by phoet** [comment]
<img width="417" alt="screen shot 2017-06-18 at 21 33 09" src="https://user-images.githubusercontent.com/48745/27263620-c185b0b2-546d-11e7-9c16-fe6ebcb31e59.png">

**Comment by janz93** [comment]
Oder so

**Comment by janz93** [comment]
Still not working
![image](https://user-images.githubusercontent.com/5300559/27263654-3545417a-546e-11e7-9f93-689a6c860cc7.png)

**Comment by phoet** [comment]
there was no 2fa activated in the first place. this is just google "security". please try again and see if you can login now.
<img width="516" alt="screen shot 2017-06-19 at 07 49 33" src="https://user-images.githubusercontent.com/48745/27271256-01e7b906-54c4-11e7-8ac5-9c87295d1907.png">

**Comment by phoet** [comment]
@janz93 were you able to login successfully?

**Comment by janz93** [comment]
I haven't tested again.

**Comment by janz93** [comment]
No, I still get the same message as before attached above as screenshot.
I clicked now on the verification via SMS.
You should have received a verification code now on your cell phone.
I would need that code in order to get access to the account.

**Comment by janz93** [comment]
Otherwise, I think it would be the best to finish it at the next meetup.

**Comment by phoet** [comment]
ok, let's skip this until we meet next time

Jan Zaydowicz <notifications@github.com> schrieb am Fr., 30. Juni 2017,
12:48:
