### ISSUE TITLE
August Event 09.08.2107

### ISSUE THREAD

**Issue by phoet** [rughh/planning#81]
09.08.2017 19:00

- [x] Location
- [x] [Event anlegen](http://hamburg.onruby.de/admin/)
- [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
- [x] Promo auf Twitter
- [x] [Push-Notification für iOS app senden](http://hamburg.onruby.de/admin/dashboard)
- [x] [Slides anpassen](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)
- [ ] [Door Sign anpassen](https://docs.google.com/presentation/d/1IQfnE3TbG3EU5zRnNKdG3kzxdYjT1ryWNWs4WWgpE04/edit?usp=sharing)
- [ ] [Gather slide-decks and other material](http://hamburg.onruby.de/admin/materials/new)

**Comment by phoet** [comment]
mindmatters will be hosting the usergroup.

discussion on twitter: https://twitter.com/mindmatters/status/874980874160414721

and confirmation via email:

> Hallo Peter,
> 
> wie schon auf Twitter erwähnt, können wir gern wieder die Usergroup am 09.08. hosten. Passt das für euch? 
> 
> Ich werde zu der Zeit im Urlaub sein. Claudia und Tim kümmern sich an dem Tag um die Organisation und Kommunikation (Claudia hier in cc).
> 
> Du kannst ja mal kurz Rückmeldung geben.
> 
> Liebe Grüße,
> Steffi
> 
> Stefanie Liebner

**Comment by halfbyte** [comment]
@janz93 @lindtdev Wie siehts aus, braucht Ihr noch was? Werde morgen anwesend sein, denke ich. Haben wir nur den einen Talk bis jetzt? Gibts noch irgendwelche Kandidaten?

**Comment by janz93** [comment]
@halfbyte ja haben wir.
Daher werde ich noch einen geben.
War aber irgendwie nicht verlinkt.
Habe es nun getan.
