### ISSUE TITLE
September Event 

### ISSUE THREAD

**Issue by lindtdev** [rughh/planning#83]
13.09.2017 19:00

- [x] Location
- [x] [Event anlegen](http://hamburg.onruby.de/admin/)
- [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
- [x] Promo auf Twitter
- [x] [Push-Notification für iOS app senden](http://hamburg.onruby.de/admin/dashboard)
- [x] [Slides anpassen](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)
- [x] [Door Sign anpassen](https://docs.google.com/presentation/d/1IQfnE3TbG3EU5zRnNKdG3kzxdYjT1ryWNWs4WWgpE04/edit?usp=sharing)
- [ ] [Gather slide-decks and other material](http://hamburg.onruby.de/admin/materials/new)

**Comment by phoet** [comment]
@tobstarr is proposing a talk http://hamburg.onruby.de/topics/build-your-own-travis

**Comment by janz93** [comment]
@phoet okay perfect.
I added to the next event :)

**Comment by tobstarr** [comment]
@janz93 :+1:

**Comment by halfbyte** [comment]
@lindtdev @phoet @janz93 Ich weiss, SEHR kurzfristig, aber ich habs heute tagsüber verrafft:

Ich habe Anfang der Woche den Orga von der London Ruby Unconference getroffen und er hat uns einen kleinen Rabatt gewährt. Ich packe das in die Präsentation und packe einen Kommentar dazu. 

Infos hier: https://www.eventbrite.com/e/london-ruby-unconference-tickets-36286901098

**Comment by janz93** [comment]
@halfbyte Vielleicht wäre dazu ein Tweet morgen oder so nochmal nicht schlecht

**Comment by janz93** [comment]
@halfbyte hast du schon die Gelegenheit gehabt, einen Tweet darüber abzusetzen?
