### ISSUE TITLE
October Event

### ISSUE THREAD

**Issue by phoet** [rughh/planning#84]
11.10.2017 19:00

- [x] Location
- [x] [Event anlegen](http://hamburg.onruby.de/admin/)
- [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
- [x] Promo auf Twitter
- [x] [Push-Notification für iOS app senden](http://hamburg.onruby.de/admin/dashboard)
- [x] [Slides anpassen](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)
- [x] [Door Sign anpassen](https://docs.google.com/presentation/d/1IQfnE3TbG3EU5zRnNKdG3kzxdYjT1ryWNWs4WWgpE04/edit?usp=sharing)
- [ ] [Gather slide-decks and other material](http://hamburg.onruby.de/admin/materials/new)

**Comment by halfbyte** [comment]
@lindtdev @janz93 I would love use the October event to have an open discussion, request for comment whatever on the Euruko thing, if you're still up for organising one in the future. I have a couple of ideas (some of which I shared with you at Euruko such as hosting a smaller event next year to learn and find a team). This could be one of the talk slots.

I would love to talk to you two in private before that - Do you have time on either Mo/Tue evening or at least a lunch or something?

**Comment by halfbyte** [comment]
Should we do a group roundup of Euruko 2017? Who would be up for that? @LAndreas?

**Comment by lindtdev** [comment]
@halfbyte I was actually just thinking of preparing a short talk on "giving a talk in general" for Wednesday, also in connection to EuRuKo. Sure let's meet Monday or Tuesday, I'm available on both evenings after around 19:00 (lunch might be trickier)

**Comment by janz93** [comment]
@halfbyte Yes I was thinking to present that pitch as well on Wednesday. To meet before is defiantly a great idea to get some more details from you (some with experiences). I would prefer Monday evening as for lunch my time schedule is also quite full already. On Tuesday lunch or dinner would work out for me.

**Comment by lindtdev** [comment]
@halfbyte @janz93 OK so let's meet tomorrow evening then? When and where do you suggest?

**Comment by janz93** [comment]
@lindtdev @halfbyte because of the situation of the Deutsche bahn I am tomorrow stranded in Bremen. Therefore I would like to meet up on Tuesday. The where and when doesn't quite matter to me. If you guys insist on tomorrow I could be there remotely

**Comment by lindtdev** [comment]
Oh man didn't know it was still that bad with DB. Tuesday, then.

**Comment by halfbyte** [comment]
@lindtdev @janz93 Let's do Tuesday then. Shall we take this to private email? ;)

**Comment by LAndreas** [comment]
@halfbyte sorry, i'm out. I can't make it to the next meetup. :/

**Comment by janz93** [comment]
@entropywtf Can you sent me the video you made during our pitch at the euruko 2017?

**Comment by entropywtf** [comment]
oh yeah right sorry sorry sorry
one moment
