### ISSUE TITLE
Wer liefert was Hosting offer

### ISSUE THREAD

**Issue by janz93** [rughh/planning#85]
> Moin moin Jungs,
>
>hiermit möchten wir (Entwickler von "Wer liefert was? GmbH") gerne unsere DEV-Space anbieten! >Dafür haben wir Erlaubnis und Budget bekommen.
>Wir bitten Beer, Snacks und unsere DEV-Space für Ruby Usergroup Vorträge, wie sieht Ihr das?
>
>VG,
>Vladimir Glusic

Vielen Dank nochmal für euer Angebot.

**Comment by exsemt** [comment]
Moin moin,

die Anfrage ist von mir, für alle weitere Fragen stehe ich euch gerne zur Verfügung!

VG,
Vladimir

**Comment by phoet** [comment]
witzig, die anfrage kam am selben tag an dem ich unabhängig von einander zwei alte kollegen von wlw getroffen habe... zufälle gibt es immer!

**Comment by lindtdev** [comment]
Moin @exsemt, der nächste Termin (Mittwoch 8. November 19:00) passt für euch?

**Comment by exsemt** [comment]
Ja, passt gut! Das Bier ist schon da, Snacks müssen wir noch organisieren ))

**Comment by lindtdev** [comment]
Ja super! Können Jan und ich in der Woche davor einmal kurz vorbeikommen? Wann passt es für euch?

**Comment by exsemt** [comment]
Ich kann euch Mi. (01.11), Do. (02.11), oder Fr. (03.11) nach 16:00 Uhr anbieten. Wann passt euch besser?

**Comment by lindtdev** [comment]
Wie wäre es dann am 1.11 nach Feierabend, so 18:30?

**Comment by exsemt** [comment]
Ja, das passt

**Comment by exsemt** [comment]
Sorry, ich muss leider am 01.11 freue Feierabend machen, hab ein Termin um 19:00 Uhr. Können wir auf Do. 02.11 um 18:30 Uhr verschieben?

**Comment by lindtdev** [comment]
Ja, das passt!

**Comment by lindtdev** [comment]
Kurzer Reminder dass wir heute vorbeikommen ;)
