### ISSUE TITLE
Rabatt  London Ruby Unconference

### ISSUE THREAD

**Issue by janz93** [rughh/planning#86]
@halfbyte hatte dies als Kommentar in dem #39 beiläufig erwähnt.
>@lindtdev @phoet @janz93 Ich weiss, SEHR kurzfristig, aber ich habs heute tagsüber verrafft:
>
>Ich habe Anfang der Woche den Orga von der London Ruby Unconference getroffen und er hat uns >einen kleinen Rabatt gewährt. Ich packe das in die Präsentation und packe einen Kommentar dazu.
>
>Infos hier: https://www.eventbrite.com/e/london-ruby-unconference-tickets-36286901098

Ich habe es auf dem Meetup weitergegeben. Da aber nicht so viele Leute bei dem Meetup waren, würde ich es gut finden, wenn man dazu nach einen kurzen tweet erstellen kann.
@halfbyte es wäre super, wenn du dies machen könntest, da du alle Einzelheiten kennst. Alternative kannst du mir das kurz auch hier schreiben und ich erstelle den Tweet.
ps. Ich habe hierfür der übersichtshalber ein neues Issue eröffnet.

**Comment by halfbyte** [comment]
Conf is over :)
