### ISSUE TITLE
Hanse Ventures hosting offer

### ISSUE THREAD

**Issue by janz93** [rughh/planning#87]
@aLamprecht Vielen Dank für die Reminder email.
Ich werde mich darum und auch schon mit Lynda geschrieben.
Für das Oktober Meetup sind noch intern einige Punkte zu besprechen, was aber bis Anfang nächster Woche getan ist.
Ich werde mich daher Montag bei euch melden.

**Comment by aLamprecht** [comment]
Hey, 
Lynda ist noch bis 2.10. im Urlaub, deswegen habe ich jetzt nochmal nachgefragt. Aber sehr cool, wenn ihr uns noch auf'm Schirm habt. Dann können wir gerne nächste Woche nochmal schreiben. 

Grützie,
Anne

**Comment by janz93** [comment]
@aLamprecht ich habe eben mit der Julia abgesprochen, dass ich mich am Mittwoch nochmal melden werde und dann alle Details von Zeitpunkt( es gibt im Moment 2 Anfragen zum hosten im Oktober) bis hin zu den Anforderungen besprechen werde.

**Comment by janz93** [comment]
@aLamprecht @lindtdev Wie gestern mit Julia besprochen werden ich und @lindtdev Donnerstag den 05.10.2017 zu euch kommen um die Details für das Oktober am Meetup 11.10.2017 zu besprechen.
Wir freuen uns sehr, dass wir das Ruby Meetup bei euch hosten dürfen.
