### ISSUE TITLE
Talk Ideas (for the "revitalization effort")

### ISSUE THREAD

**Issue by halfbyte** [rughh/planning#88]
@phoet @lindtdev @janz93 Let's collect some ideas of interesting talk topics we could offer to people here.

**Comment by halfbyte** [comment]
## Some basic talks on popular things almost every Rails app needs

- File Uploaders in comparison and ActiveStorage in Rails 5.2
- Authentication and Authorization, what gems for what, comparison
- Testing (Could be a RSpec vs. minitest thing where two proponents argue)
- A comprehensive look at i18n, from simple yml to a system like PhraseApp or similar (maybe Tobi from PhraseApp would like to do one?)
- HTTP library shootout
- Deployment options from small to large (From Heroku to Kubernetes oder so)
- How Webpack works in Rails 5.1 (would love to get a demo of that with a popular framework)

## Some advanced concepts

- Did we have a GraphQL talk yet?

**Comment by janz93** [comment]
- Ruby not just for websites
- hanami-cli a new command line toolbox

**Comment by lindtdev** [comment]
- I worked with Go these past ~5-6 months and would like to do one on building web apps with Go vs Rails 
- D3.js for data visualisation
- I'd like to hear more about NoSql solutions: Redis/Memcache etc
- transitioning from standard Rails to using a SPA frontend

**Comment by tobstarr** [comment]
@lindtdev dependent on the time/date I would always be available

**Comment by JoschkaSchulz** [comment]
@janz93 I just working currently with artoo Ruby on Robtics... and also planned to create a RUGHH Talk for that :3 Already have digispark controller and an arduino running with that

**Comment by janz93** [comment]
@JoschkaSchulz Cool I would love to hear about it. Could you [submit](http://hamburg.onruby.de/topics/new?) the talk proposal?

**Comment by kkostrebic** [comment]
my 2 cents...

Since RoR is not acing in terms of performance, maybe to present some ruby alternatives to rails, possible some of the existing microframeworks or projects, especially stuff from Jeremy Evans - like Roda+Sequel with erubi (which is now default template engine in Rails).

**Comment by wwwbruno** [comment]
I like to talk about the Rails architecture, especially about MCV and how it can make you create an unbreakable monolith.

I would talk about some personal experiences but based on this [video](https://www.youtube.com/watch?v=WpkDN78P884) and this [post](https://8thlight.com/blog/uncle-bob/2012/08/13/the-clean-architecture.html) from Uncle Bob.

**Comment by halfbyte** [comment]
@wwwbruno Sounds good - I'm not a huge fan of Robert Martin, but that doesn't mean that this wouldn't be a good talk. When could you give that talk? I assume this week is a bit on short notice?

**Comment by wwwbruno** [comment]
@halfbyte this week I really can't get it ready. But for the next meetup, I'm pretty sure that would be possible!

**Comment by janz93** [comment]
@wwwbruno how is the progress of your talk going. Should we put you up for our meetup next week?

**Comment by wwwbruno** [comment]
@janz93 sure! I just submitted [here](http://hamburg.onruby.de/topics/new?) my talk proposal.
