### ISSUE TITLE
ruby unconf

### ISSUE THREAD

**Issue by phoet** [rughh/planning#89]
@halfbyte @lindtdev @janz93 i would like to use this issue to give people that are interested in helping out a place to get in touch.

**Comment by phoet** [comment]
as far as i recall, the general idea was this:

in order to prepare for hosting a big ruby conference in hamburg like maybe euruko 2019, it would be a great excercise to organize a leaner event like an unconf.

borrowing ideas and knowledge from php and jsunconf, it should be an easier start into the right direction.

**Comment by phoet** [comment]
i'm going to meet with @robin-drexler in order to talk about using [boot ev](https://www.bootev.org/) as a vehicle to get this party started.

**Comment by janz93** [comment]
@coma2nd Thanks for your [help](https://twitter.com/tt_developers/status/918455672198615041). Here in this issue you can contact us and find any informations regarding the ruby unconf.

**Comment by phoet** [comment]
@fabrik42 offered help and sponsorship

**Comment by fabrik42** [comment]
Yes, lurking here right now!

**Comment by sr189** [comment]
Hi, perfect. @farson is with us as well.

**Comment by janz93** [comment]
@phoet @fabrik42 @sr189 @halfbyte @lindtdev Thanks for the help. Now it's time to start with the actual planning. Therefore I would like to get together and make a really really long todo list for the ruby unconf. Maybe next week on Tuesday lunch or dinner at a bar or company with some drinks.
The day can be adjusted if needed but should be within the next 2 weeks to have a basic plan ready be the end of October

**Comment by halfbyte** [comment]
@janz93 ACK.

I would rather prefer a living room, though, or even an office (Whiteboards!) - I think it makes sense to have more of a working atmosphere.

Also, I don't think a lunch break will be enough time, so I vote for an evening. Next Tuesday works for me.

@tobstarr offered their (PhraseApp) offices for planning (on the twitters), but of course we should check for availability first.

**Comment by janz93** [comment]
@halfbyte Thanks for the tip. So evening it will be. Let's see what @tobstarr will say about the availability.

**Comment by sr189** [comment]
We can use our office on tuesday as well if you like and if necessary. Conference room or tech room should be available.

**Comment by p0wl** [comment]
Hey, I'm late to the party but I would also love to help, if you need some more!

**Comment by phoet** [comment]
if thursday it is, i'm not available. so please go ahead without me. @halfbyte and i already reached out a bit to get more outside help. you can find it documented here: https://docs.google.com/document/d/1XlKD86T7ib7kph8zik4NoNc8oyY0LSP5OX7bayFv0zA/edit?usp=sharing

**Comment by phoet** [comment]
i still have some material from organizing railscamp 2010 and 2011, but except for the (obvious) list of sponsors and some pricepoints, i don't think it's worth looking into.

**Comment by halfbyte** [comment]
@phoet Who talked about thursday? :)

**Comment by phoet** [comment]
ah, nobody, great!

**Comment by sr189** [comment]
Hi, is tomorrow fix then? And do we know when and where already?

**Comment by janz93** [comment]
@sr189 Yes I would say tomorrow 18:30 - 19:00 at your place if the offer is still available.

**Comment by sr189** [comment]
Yes, sure :) The address is Ferdinandstraße 29-33 on the 4th level.

**Comment by halfbyte** [comment]
See y'all at ~18:30 then. Shall we order something like Pizza together?

**Comment by sr189** [comment]
Sure, i think we can order when we are here or should we order beforehand?

**Comment by halfbyte** [comment]
Nah, that's fine. I'm just hungry already, that's all :)

**Comment by janz93** [comment]
@halfbyte I am hungry as well. So I would suggest the ordering  being our first task today.

**Comment by phoet** [comment]
![screen shot 2017-10-24 at 17 56 55](https://user-images.githubusercontent.com/48745/31954047-ca21d242-b8e4-11e7-9f19-0a85adfbf7d2.png)

i'm not sure i can make it, the commute is too long 😄

**Comment by phoet** [comment]
we started a slack-channel to do the internal planning communication. everyone who is interested, just ping me and i'll send you an invite.
