### ISSUE TITLE
Meeting Apr 2015

### ISSUE THREAD

**Issue by titanoboa** [rughh/planning#9]
* [x] Location
* [x] Talks / Format
* [x] Promo auf Twitter
* [x] [Push-Notification für iOS app senden](http://hamburg.onruby.de/admin/dashboard)
* [x] [Slides anpassen](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)

@skade hat den Rust-Talk zugesagt

**Comment by titanoboa** [comment]
Wir haben es schon wieder verpennt gestern festzulegen, wer im April mit der Orga dran ist. Vielleicht @halfbyte ?

**Comment by LAndreas** [comment]
Moin moin,
Protonet würde euch gerne die Location fürs nächste Treffen stellen! :-)

**Comment by halfbyte** [comment]
@titanoboa Kann ich machen.

**Comment by halfbyte** [comment]
@skade Termin haste auf der Reihe, ja? :)

**Comment by halfbyte** [comment]
Location sage ich dann mal "Protonet". Ich nehme an, dass meint "Der Raum über dem Makerhub", richtig, @LAndreas?

**Comment by halfbyte** [comment]
Ich überlege selber einen Vortrag über mein BASIC-Parser-Experiment zu halten, also zu zeigen, wie man mit parslet einen Parser baut. Bis dahin sollte da auch zeigbarer Code da sein.

Weitere Ideen?

**Comment by skade** [comment]
@halfbyte Yup. Notfallmedikamente für wiederholte Krankheit liegen auch bereit :).

**Comment by phoet** [comment]
scheint so als ob da noch ne ganze meute aus berlin kommt! @peterlih @defsprite

**Comment by LAndreas** [comment]
@halfbyte jap! "Der Raum über dem Makerhub".

**Comment by rngtng** [comment]
ich schliess mich @peterlih und  @defsprite an und stell gern mal http://vizard.io vor...

**Comment by phoet** [comment]
@rngtng guck mal bitte [in diese wiki-seite](https://github.com/rughh/planning/wiki/Speaker-Checklist) und gib uns dann feedback.

**Comment by rngtng** [comment]
@phoet:
- Timebox: 10-20min
- Sprache: En/De
- Q&A: En/De
- Timebox für Q&A: 10min
- onruby: 'You think UML Diagrams are tedious and overhead? Well, meet vizard.io'

**Comment by phoet** [comment]
thx! ([onruby thema ist hier eingetragen](http://hamburg.onruby.de/topics/vizard-io))

**Comment by halfbyte** [comment]
Event auf onruby erstellt, @rngtng's Talk eingetragen. @skade magst Du bei Gelegenheit entweder hier oder [dort](http://hamburg.onruby.de/topics/new) eine Kurzbeschreibung reinwerfen? Danke!

**Comment by titanoboa** [comment]
@halfbyte die Kurzbeschreibung zum talk von @skade gibts doch schon vom letzten Anlauf, hab ich jetzt mal dem April zugeordnet

**Comment by skade** [comment]
Falls Sorgen bestehen: ich bin da. Eventuell brauch ich nen Schlafplatz, aber das ist noch nicht sicher :).

**Comment by robinboening** [comment]
@skade ich bin im pacific hotel am neuen Pferdemarkt: http://www.hotel-pacific.de/

**Comment by robinboening** [comment]
@halfbyte Ich würde gerne einen 5min lightning-talk halten. Passt das?

Hintergrund: Wir haben nun, finally, einen Vertrag mit Parallels unterschrieben die ein Open Source Projekt finanzieren. Es geht darum ruby beginnern den Einstieg zu erleichtern. Wie das im Detail aussehen wird, wird sich nach der 1. Phase (Kommunikation sowohl mit Beginnern als auch Maintainer bestehender Lösungen/Ansätze (railsinstaller, tokaido, rvm, docker, ...) herausstellen.

**Comment by halfbyte** [comment]
@robinboening *sehr* gerne. Magst Du das noch schnell [als Thema eintragen](http://hamburg.onruby.de/topics/new), dann verlinke ich das noch fix mit?

**Comment by halfbyte** [comment]
@skade Ich vermute, da sollte sich auch kurzfristig was finden lassen.
(Sorry wegen der Doppelthemenanfrage und Dank an @titanoboa für den awesome Save. Mein Gehirn besteht immer noch zu 50% aus gelbem Schleim...)

**Comment by halfbyte** [comment]
Apropos Schleim: Ich würde den Talk von Florian ungern verpassen, aber es besteht durchaus eine gewisse Chance, dass ich morgen nicht da bin. Heads up an @titanoboa und @phoet dass eventuell jemand anders die Einleitung machen muss.

**Comment by halfbyte** [comment]
@phoet: Ich habs schon wieder vergessen. Wann sendet man diese Push-Notification am besten so?

**Comment by phoet** [comment]
![push](https://cloud.githubusercontent.com/assets/48745/7028791/90dcbe4e-dd58-11e4-8418-65c58cce7b0f.png)

**Comment by halfbyte** [comment]
![meeting_apr_2015_ _issue__9_ _rughh_planning](https://cloud.githubusercontent.com/assets/299/7028912/8a4454ba-dd59-11e4-9844-3d299fe54f14.png)

**Comment by halfbyte** [comment]
@phoet: Ich bin mir nicht ganz sicher, ob ich *danach* nicht die Frage gestellt hätte *wo* man die verschickt. :-P

**Comment by phoet** [comment]
:D hab nur die halbe nachricht in der notification gelesen!

ASAP trifft es da wohl am besten? sobald wir die leute informieren wollen, also ich denke mal nachdem der termin eingestellt ist und wir location und talks geplant haben. quasi dann wenn man auch twitter promo machen würde... was sagt denn der @mnin dazu. benutzen das überhaupt leute?

**Comment by mnin** [comment]
@halfbyte @phoet am besten so früh wie möglich um allen die gelegenheit zu geben am event teilzunehmen, ich würde sagen, so bald man einen termin hat kann man das per push notification bekannt geben.

ich hatte mit @phoet diskutiert, ob man nicht eher einen sandkasten-modus benötigt in dem man ein event editieren kann bis man ihn auf der webseite veröffentlicht. und beim veröffentlichen könnte man dann gleichzeitig die push notification versenden.

**Comment by halfbyte** [comment]
Isch hab da uffn Knopp jedrückt und der GEHT!!!

**Comment by halfbyte** [comment]
Danke, Tschüss.
