### ISSUE TITLE
November event

### ISSUE THREAD

**Issue by lindtdev** [rughh/planning#90]
08.11.2017 19:00 bei Wer liefert was

- [x] Location
- [x] [Event anlegen](http://hamburg.onruby.de/admin/)
- [ ] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
- [ ] Promo auf Twitter
- [ ] [Push-Notification für iOS app senden](http://hamburg.onruby.de/admin/dashboard)
- [ ] [Slides anpassen](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)
- [ ] [Door Sign anpassen](https://docs.google.com/presentation/d/1IQfnE3TbG3EU5zRnNKdG3kzxdYjT1ryWNWs4WWgpE04/edit?usp=sharing)
- [ ] [Gather slide-decks and other material](http://hamburg.onruby.de/admin/materials/new)

**Comment by halfbyte** [comment]
Bascht, who organizes UG Munich and RubyOnIce (the conference) asked if we could advertise the conference at the next meeting. I can do that (I'm also speaking there, so that kinda makes sense)

**Comment by janz93** [comment]
Yes sure

**Comment by phoet** [comment]
@halfbyte i expect they do the same in return for the unconf

**Comment by phoet** [comment]
i won't be there on wednesday, have to take care auf paulchen

**Comment by dariusgm** [comment]
I wont finish the talk about the parallel gem till tomorrow. probably next time?

**Comment by lindtdev** [comment]
OK! Someone from wer-liefert-was was thinking about giving a talk as well, did anything come of that?

**Comment by dariusgm** [comment]
yeah, this one was me -

**Comment by halfbyte** [comment]
@johanness No worries!

**Comment by johanness** [comment]
The talk will just be about 20min if this helps for the planning...

**Comment by halfbyte** [comment]
@lindtdev @janz93 Bin unfassbar spät dran, bitte wartet nicht auf mich, die Sache mit der RubyOnIce kann ich auch noch nach dem Vortrag erzählen.
