### ISSUE TITLE
December Meetup (Glühwein-Usergroup)

### ISSUE THREAD

**Issue by phoet** [rughh/planning#91]
13.12.2017 19:00

- [x] Location
- [x] [Event anlegen](http://hamburg.onruby.de/admin/)
- [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
- [x] Promo auf Twitter
- [x] [Push-Notification für iOS app senden](http://hamburg.onruby.de/admin/dashboard)
- [x] [Slides anpassen](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)
- [x] [Door Sign anpassen](https://docs.google.com/presentation/d/1IQfnE3TbG3EU5zRnNKdG3kzxdYjT1ryWNWs4WWgpE04/edit?usp=sharing)
- [ ] [Gather slide-decks and other material](http://hamburg.onruby.de/admin/materials/new)

**Comment by phoet** [comment]
mindmatters is offering to host the rughh christmas edition with mulled wine and waffles:

> Hi Peter,
> 
> habt ihr schon einen Host für die Usergroup im Dezember? Ich hörte, da gibt es immer Glühwein und Waffeln. 
> 
> Mein Kollege Joschka möchte zudem bald einen Talk bei euch halten und da wäre es natürlich für uns klasse, wenn die Usergroup mal wieder bei mindmatters stattfindet.
> 
> Ich bin gespannt auf deine Rückmeldung.
> 
> Liebe Grüße,
> Stefanie

**Comment by lindtdev** [comment]
That sounds great

**Comment by stefanieliebner** [comment]
Hi all,
awesome. We'll take care of the catering. We can as well promote the usergroup via mindmatters social media accounts up front. 
Let us know when you have an exact date in mind.

**Comment by phoet** [comment]
@stefanieliebner date is already set, it's wednesday 13th of december. i just corrected the date in the description.

**Comment by JoschkaSchulz** [comment]
I would like to hold this Talk (http://hamburg.onruby.de/topics/ruby-on-robotics-artoo-io-565#show-last-Point) on that Dezember Group... :)

**Comment by phoet** [comment]
@JoschkaSchulz 👍

**Comment by JoschkaSchulz** [comment]
@phoet yep I will try to finish the most of it this and next weekend and can tell them how long it will take

**Comment by janz93** [comment]
@dariusgm Would you like to give you talk next week?

**Comment by JoschkaSchulz** [comment]
Nebenbei zum Ruby on Robotics Talk wäre es übrigens folgendes:
```
Speaker-Checklist:
timebox: 20m (also eher kürzerer Talk)
sprache: bevorzugt deutsch, notfalls auch englisch
q&a: klar
```

**Comment by dcarral** [comment]
Just came across this issue: below is the “speaker checklist” related to the [“Tools, tools everywhere” proposal](http://hamburg.onruby.de/topics/tools-tools-everywhere-571) @ [_onruby_](http://hamburg.onruby.de):

- Wie lange dauert der Vortrag? 
Mal 20 Minuten sagen (40 mit ein bisschen “hands-on”, auch gerne, wie ihr wollt).

- Ist es ok den Vortrag evtl. in englisch zu machen?
Auf jeden fall, eigentlich würde ich es empfehlen: mein Deutsch ist noch zu schwach um ein Talk zu machen ;)

- Dürfen nach dem Vortrag Fragen gestellt werden? In welcher Sprache? 
Gerne! Beide Englisch & Deutsch klappen, wie lange als ihr wollt ;)

- Kurze Vortragsankündigung auf http://hamburg.onruby.de/topics/new (inkl. Angaben zum Thema Sprache)
Die Vortragsankündigung ist schon @ [_onruby_](http://hamburg.onruby.de) verfügbar: http://hamburg.onruby.de/topics/tools-tools-everywhere-571.

**Comment by phoet** [comment]
@dcarral danke! wir freuen uns auf deinen Besuch!

**Comment by lindtdev** [comment]
That was once again a great meetup at Mindmatters!

**Comment by stefanieliebner** [comment]
It was a pleasure to have you guys over. See you in 2018!

**Comment by janz93** [comment]
@JoschkaSchulz kannst du uns noch deine slides schicken? Ich würde die dann gerne mit verlinken.

**Comment by JoschkaSchulz** [comment]
klar @janz93 hier: https://slides.com/joschkaschulz/ruby-on-robotics/
