### ISSUE TITLE
Januar Meetup

### ISSUE THREAD

**Issue by lindtdev** [rughh/planning#92]
10.01.2018 19:00

- [x] Location
- [x] [Event anlegen](http://hamburg.onruby.de/admin/)
- [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
- [x] Promo auf Twitter
- [x] [Push-Notification für iOS app senden](http://hamburg.onruby.de/admin/dashboard)
- [ ] [Slides anpassen](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)
- [ ] [Door Sign anpassen](https://docs.google.com/presentation/d/1IQfnE3TbG3EU5zRnNKdG3kzxdYjT1ryWNWs4WWgpE04/edit?usp=sharing)
- [ ] [Gather slide-decks and other material](http://hamburg.onruby.de/admin/materials/new)

**Comment by lindtdev** [comment]
Wir haben aktuell noch keine Location!

**Comment by lindtdev** [comment]
Xing hat sich bereit erklärt, uns im Januar zu hosten :) danke an @mlammers

**Comment by janz93** [comment]
@wwwbruno would you be able to present your talk next week?

**Comment by wwwbruno** [comment]
@janz93 sure! I have it ready!

**Comment by janz93** [comment]
@wwwbruno 👍 please have a look at our small speaker checklist https://github.com/rughh/planning/wiki/Speaker-Checklist

**Comment by lindtdev** [comment]
@wwwbruno @mgharbik
thanks again for your talks! could you perhaps share the slides with us so I can add them to hamburg.onruby.de?

**Comment by wwwbruno** [comment]
Thank you @lindtdev, here is the [link](https://www.slideshare.net/wwwbruno/how-to-not-create-an-unbreakable-rails-monolith) for my presentation.

**Comment by mgharbik** [comment]
@lindtdev Thank you too for having us! Here are my [slides](https://www.slideshare.net/MohammedGharbi/rails-engines-86105438).

**Comment by phoet** [comment]
@wwwbruno could you be so nice and ping me via email? phoetmail@googlemail.com
