### ISSUE TITLE
February Meetup 

### ISSUE THREAD

**Issue by lindtdev** [rughh/planning#93]
14.02.2018 19:00

- [x] Location
- [x] [Event anlegen](http://hamburg.onruby.de/admin/)
- [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
- [x] Promo auf Twitter
- [ ] [Push-Notification für iOS app senden](http://hamburg.onruby.de/admin/dashboard)
- [ ] [Slides anpassen](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)
- [ ] [Door Sign anpassen](https://docs.google.com/presentation/d/1IQfnE3TbG3EU5zRnNKdG3kzxdYjT1ryWNWs4WWgpE04/edit?usp=sharing)
- [ ] [Gather slide-decks and other material](http://hamburg.onruby.de/admin/materials/new)

**Comment by timschro** [comment]
We'll host the event at our Drugstore (2nd floor of our office building)
_Location:_ Publicis Pixelpark, Gerhofstr. 1, 20354 Hamburg, https://goo.gl/maps/khfs6WK9hTn 
Entrance on the right side of the Tchibo store.

Beer, non-alcoholics and maybe some snacks will be provided. Bigscreen setup for presentations available (HDMI).

**Comment by lindtdev** [comment]
@timschro could @janz93 and me drop by for a short visit on February 7th in the evening? Something like shortly after 18? It's a Wednesday.

**Comment by timschro** [comment]
@lindtdev I'm out of office next week Tue-Fri (6-9 Feb that is). Would it somehow be possible this week or on Monday?

**Comment by lindtdev** [comment]
Monday 05.02 then? Also shortly after 18?

**Comment by timschro** [comment]
@lindtdev 05.02. 6pm is perfektly fine.

**Comment by timschro** [comment]
@lindtdev @janz93 If our front desk is already unmanned (and no one is opening) please give me a call. I'll send the number to your gmail accounts.
