### ISSUE TITLE
June Meetup

### ISSUE THREAD

**Issue by lindtdev** [rughh/planning#97]
13.06.2018 19:00

- [x] Location
- [x] [Event anlegen](http://hamburg.onruby.de/admin/)
- [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
- [x] Promo auf Twitter
- [x] [Push-Notification für iOS app senden](http://hamburg.onruby.de/admin/dashboard)
- [ ] [Slides anpassen](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)
- [ ] [Door Sign anpassen](https://docs.google.com/presentation/d/1IQfnE3TbG3EU5zRnNKdG3kzxdYjT1ryWNWs4WWgpE04/edit?usp=sharing)
- [ ] [Gather slide-decks and other material](http://hamburg.onruby.de/admin/materials/new)

**Comment by tisba** [comment]
Servus! Ich hätte einen Themenvorschlag: (Lexer und) Parser für/in Ruby an einem praktischen Beispiel. Das habe ich letzte Woche beim Kölner Ruby Meetup gemacht - weniger als Talk, mehr als ich zeige Code und man diskutiert und redet drüber.

**Comment by janz93** [comment]
@dariusgm are you still wanting to give your talk about the seed gem at the usergroup?

**Comment by lindtdev** [comment]
@tisba das klingt super cool

**Comment by janz93** [comment]
@tisba wärst du immer noch bereit das Thema vorzustellen?
Dann würde ich dies nun in unsere Meetup Agenda eintragen
