### ISSUE TITLE
Host August

### ISSUE THREAD

**Issue by akimthedream** [rughh/planning#98]
Hola liebes Team 👋 

Ich hatte mit Jan bezüglich einer möglichen Ausrichtung bei uns in der Firma (REBELLE - StyleRemains GmbH) gesprochen. Wir hatten den Juli angepeilt, allerdings schaffen wir das nicht weil wir letzten Freitag mit dem Büro umgezogen sind. Wir befinden uns immer noch in der Hafencity, nur eine Hausnummer weiter jetzt. Von daher würde ich unsere Location für den August anbieten 🙂 Einen Talk könnten wir auch stellen, ich habe ein paar Themengebiete und schaue mal, was sich am besten eignen würde. 

Liebe Grüße, Achim

**Comment by phoet** [comment]
@akimthedream danke für das angebot.

@janz93 @lindtdev gibt es schon einen organisator für das juli meetup #99 ?

**Comment by janz93** [comment]
@akimthedream Moin ist die Address:  Brooktorkai 4, 20457 Hamburg noch aktuell?

**Comment by janz93** [comment]
Look at #101  for further communication
